### ISSUE TITLE
Crashes in release mode

### ISSUE THREAD

**Issue by krille-chan** [gunschu/jitsi_meet#1]
In debug mode it is working like a charm. Great job!!

Only in release mode, when building an APK with --release it seems to crash. I will try to collect some logs and more informations.

### Steps to reproduce:
1. Build with `flutter build apk --release`
2. Install apk on your Android device
3. Start a Jitsi session
-> App crashes and exit

#### Flutter Doctor:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale de_DE.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/krille/Lokal/HADTF/flutter_linux_v1.2.1-stable/flutter
    • Framework revision 0b8abb4724 (vor 7 Wochen), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/krille/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/84/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/84/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by ladislaoo** [comment]
Yes, i try to install , 
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [VersiÃ³n 10.0.18362.720], locale es-MX)
    • Flutter version 1.12.13+hotfix.8 at D:\flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\CasaNovo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.4
    • Flutter plugin version 41.0.4
    • Dart plugin version 192.7402

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\CasaNovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • SM A605GN • c8b7e468 • android-arm • Android 9 (API 28)

• No issues found!

**Comment by tuantvu** [comment]
I was able to reproduce crashes. Although I wasn't able to install an apk on the emulator like you both did, because Flutter is unable to create an x86 apk, so I installed onto my phone. I hope the crash is the same as yours. To fix it, I had to add some proguard settings. I've uploaded version 0.1.3+1 with README instructions for proguard. Please try that out and comment back here. We can close the issue after the fix helps you both.

**Comment by ladislaoo** [comment]
Yes, fix my problem with release APK, with proguard files, thanks a lot

Best Regards.

**Comment by krille-chan** [comment]
Seems to be fixed now. Thank you.

**Comment by mnomanmemon** [comment]
Facing this again in v0.4.1. Though video meeting is working fine. Issue in release mode apk creation. Cannot able to do that

This is the output:

```
/Users/muhammadnoman/.gradle/caches/transforms-2/files-2.1/f131eebe81054cd12fff93b3418218b5/jetified-react-native-0.61.5-jitsi.1-runtime.jar: R8: Type com.facebook.react.bridge.ReactMethod is defined multiple times: /Users/muhammadnoman/.gradle/caches/transforms-2/files-2.1/f131eebe81054cd12fff93b3418218b5/jetified-react-native-0.61.5-jitsi.1-runtime.jar:com/facebook/react/bridge/ReactMethod.class, /Users/muhammadnoman/Apps/learningSoda/mobile_app/build/stripe_payment/intermediates/runtime_library_classes/release/classes.jar:com/facebook/react/bridge/ReactMethod.class
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:minifyReleaseWithR8'.                   
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 43s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      46.9s
[!] The shrinker may have failed to optimize the Java bytecode.
    To disable the shrinker, pass the `--no-shrink` flag to this command.
    To learn more, see: https://developer.android.com/studio/build/shrink-code
Gradle task assembleRelease failed with exit code 1
```

**Comment by rohitprajapatii** [comment]
I've added proguard files but still my app crashes when jitsi starts.

**Comment by Manjunath-VM** [comment]
> I was able to reproduce crashes. Although I wasn't able to install an apk on the emulator like you both did, because Flutter is unable to create an x86 apk, so I installed onto my phone. I hope the crash is the same as yours. To fix it, I had to add some proguard settings. I've uploaded version 0.1.3+1 with README instructions for proguard. Please try that out and comment back here. We can close the issue after the fix helps you both.

Hi, can u guide me what is the fix

**Comment by Manjunath-VM** [comment]
> Yes, fix my problem with release APK, with proguard files, thanks a lot
> 
> Best Regards.

what is the fix can u guide me ,facing the same issue here. @ladislaoo @tuantvu @ChristianPauly

**Comment by SyedHuzaifaAli-1998** [comment]
@Manjunath-VM They added Progard File to their app level
you can find the progard text at
[https://raw.githubusercontent.com/gunschu/jitsi_meet/master/jitsi_meet/example/android/app/proguard-rules.pro](url)

if it fix kindly let me know and if not also mention me
