### ISSUE TITLE
How to close the call automatically when single user remained at room after conversation?

### ISSUE THREAD

**Issue by cihanfiliz** [gunschu/jitsi_meet#100]
I don't want to keep single user alone at room after conversation. When other users finished the meeting and left the room, the last user should left automatically also.

**Comment by tuantvu** [comment]
I'm not seeing a "room subscription" type functionality that Jitsi provides as documented in their developer handbook. You could open a feature request with JitsiMeet team to see if they will add it to their mobile sdks, then we can integrate with it in this plugin.  https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-start
