### ISSUE TITLE
Need Video call meeting with a group of more than 5 members in same time

### ISSUE THREAD

**Issue by ShohidulProgrammer** [gunschu/jitsi_meet#102]
Is it possible to make a video call with more than 5 members in a group conferencing/ meeting at the same time?

**Comment by TBG-FR** [comment]
I do not understand the issue, Jitsi potentially provides everything to do a conference with an (virtually) unlimited amount of people, with or without video. Have you encountered issues while trying a conference with >5 people enabling their camera ?

**Comment by jimmyjose-dev** [comment]
If you are looking for Whatsapp like group video calling, thats not currently supported.
It's more like Zoom video conference, where first user/admin creates the room and other users join that room.

**Comment by tuantvu** [comment]
@ShohidulProgrammer Please see questions above and provide an answer.
