### ISSUE TITLE
support for prevent screen capture && screen rec.

### ISSUE THREAD

**Issue by Joseph-Nathan** [gunschu/jitsi_meet#104]
support for prevent screen capture && screen rec.

**Comment by jimmyjose-dev** [comment]
This is currently not supported by this framework, but you can achieve the same by adding flutter_windowmanager package

**Comment by tuantvu** [comment]
Good info about the flutter_windowmanager package! I didn't know that existed.

@Joseph-Nathan Please close the issue if this will solve your problem. Thanks.

**Comment by jimmyjose-dev** [comment]
The package only works for android .... 
For the sake of completeness I am sharing iOS code too

_In AppDelegate.m_
```

- (void)applicationWillResignActive:(UIApplication *)application{
    self.window.hidden = YES;
}

- (void)applicationDidBecomeActive:(UIApplication *)application{
    self.window.hidden = NO;
}
```


For Android doing the same without package
In MainActivityClass

```
@Override
protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  
  getWindow().addFlags(LayoutParams.FLAG_SECURE); 
  
}
```

**Comment by Joseph-Nathan** [comment]
@Snapworks  thanks bro for you help ,and your fast answer .
but i'm secure my app with( LayoutParams.FLAG_SECURE ) and app go well , 
when i used ( jitsi_meet ) sdk it's go out from my app , and show in screen rec. 



my  MainActivityClass :

====================================
` 
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        if (!setSecureSurfaceView()) {
           
        }

    }


    private fun setSecureSurfaceView(): Boolean {
        val content = findViewById<ViewGroup>(android.R.id.content)
        if (!isNonEmptyContainer(content)) {
            return false
        }
        val splashView = content.getChildAt(0)
        if (!isNonEmptyContainer(splashView)) {
            return false
        }
        val flutterView = (splashView as ViewGroup).getChildAt(0)
        if (!isNonEmptyContainer(flutterView)) {
            return false
        }
        val surfaceView = (flutterView as ViewGroup).getChildAt(0)
        if (surfaceView !is SurfaceView) {
            return false
        }
        //chromium
        surfaceView.setSecure(true)
       
        surfaceView.setZOrderMediaOverlay(true)
        this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
        return true
    }

    private fun isNonEmptyContainer(view: View): Boolean {
        if (view !is ViewGroup) {
            return false
        }
        if (view.childCount < 1) {
            return false
        }
        return true
    }
}
`
====================================

![Screenshot_2020-09-13-00-03-44-03 1](https://user-images.githubusercontent.com/60202661/93005857-a2c3fd00-f555-11ea-8c16-9d7b1c8ee355.jpg)

Pic.  take in a real device OPPO F11
Android 10



is there is something in my code ,
thanks for ios code ,
Are you now how to do prevent screen capture in Window , please ?

**Comment by jimmyjose-dev** [comment]
Try with PIP disabled..

Prevent screen capture in Window ? you mean Windows OS ? Application Window ?... didn't get you

**Comment by Joseph-Nathan** [comment]
@Snapworks  thanks for your replay .

i try it with PIP disabled in a full screen mode it is a same issue ,

yes , i mean Prevent screen capture  in flutter Application  run on Windows OS .

**Comment by RohithKilaparthi** [comment]
@Snapworks Can you with the code for AppDelegate.swift as well?

**Comment by jimmyjose-dev** [comment]
```
func applicationWillResignActive(_ application: UIApplication) {
    self.window?.hidden = true
}

func applicationDidBecomeActive(_ application: UIApplication) {
    self.window?.hidden = false
}
```
You can also present your own view controller instead of hiding the window
If you are using Scene delegate then these appdelegates wont be called .. then instead of applicationDidBecomeActive use sceneDidBecomeActive etc ... hope this makes sense.

**Comment by RohithKilaparthi** [comment]
Would this stop screen recording or screen shot in iOS? I see that only when the app gets minimised, the screen will get blurred. What if the screen gets recorded when the app is active?

**Comment by tuantvu** [comment]
@Joseph-Nathan @RohithKilaparthi There's a plugin that supports both Android and IOS. I haven't tried it but take a look. Regardless, these solutions seem to suggest this configuration be at the app level rather than at the Jitsi Meet plugin level.
