### ISSUE TITLE
Solved: Error: Config no longer needed!

### ISSUE THREAD

**Issue by dhruv1710** [gunschu/jitsi_meet#105]
Config was loaded and in second time its giving error as below :-
 Conference terminated: {error=Error: Config no longer needed!, event=onConferenceTerminated, url=https://meet.jit.si/4AT7N2}

**Comment by jimmyjose-dev** [comment]
Would need more details to comment on this... could you share the complete function of your join meeting.

**Comment by dhruv1710** [comment]
try {
      var stopwatch = Stopwatch();
      // Enable or disable any feature flag here
      // If feature flag are not provided, default values will be used
      // Full list of feature flags (and defaults) available in the README
      Map<FeatureFlagEnum, bool> featureFlags =
      {
        FeatureFlagEnum.WELCOME_PAGE_ENABLED : false,
        FeatureFlagEnum.ADD_PEOPLE_ENABLED : true,
        FeatureFlagEnum.CALENDAR_ENABLED :false,
        FeatureFlagEnum.INVITE_ENABLED : false,
        FeatureFlagEnum.MEETING_PASSWORD_ENABLED: false,
        FeatureFlagEnum.TOOLBOX_ALWAYS_VISIBLE : false,
        FeatureFlagEnum.PIP_ENABLED : true, 
      };

      // Here is an example, disabling features for each platform
      if (Platform.isAndroid)
      {
        // Disable ConnectionService usage on Android to avoid issues (see README)
        featureFlags[FeatureFlagEnum.CALL_INTEGRATION_ENABLED] = false;
      }
      else if (Platform.isIOS)
      {
        // Disable PIP on iOS as it looks weird
        featureFlags[FeatureFlagEnum.PIP_ENABLED] = false;
      }

      // Define meetings options here
      var options = JitsiMeetingOptions()
        ..room = widget.room
        ..subject = subjectText
        ..userDisplayName = nameText
        ..iosAppBarRGBAColor = "#0080FF80"
        ..audioOnly = false
        ..audioMuted = false
        ..videoMuted = false
        ..featureFlags.addAll(featureFlags);

      debugPrint("JitsiMeetingOptions: $options");
      await JitsiMeet.joinMeeting(options,
          listener: JitsiMeetingListener(onConferenceWillJoin: ({message}) {

            debugPrint("${options.room} will join with message: $message");
          }, onConferenceJoined: ({message}) {
            stopwatch.start();
            debugPrint("${options.room} joined with message: $message");
          }, onConferenceTerminated: ({message})async{
            var doc = await FirebaseFirestore.instance.collection('Teacher').doc(prefs.getString('KKPhone')).get();
        doc.reference.update({'meeting':'no',});
            stopwatch.stop();
            debugPrint("${options.room} terminated with message: $message,time = ${stopwatch.elapsed.abs().inSeconds}");
            await AuthService_teacher().handleAuth(context);
          }),
          // by default, plugin default constraints are used
          //roomNameConstraints: new Map(), // to disable all constraints
          //roomNameConstraints: customContraints, // to use your own constraint(s)
      );
    } catch (error) {
      debugPrint("error: $error");
    }

**Comment by dhruv1710** [comment]
I have used it from the pub.dev example.The problem is that the config.js was already loaded.

**Comment by dhruv1710** [comment]
The code works on hot restart and does not work on Hot reload

**Comment by dhruv1710** [comment]
> Would need more details to comment on this... could you share the complete function of your join meeting.

Hi Jimmy Jose,
Can you response on the error.

**Comment by jimmyjose-dev** [comment]
Create a sample app and use our updated version which is 0.4.1, we have also removed the support for  ..iosAppBarRGBAColor = "#0080FF80"  
start off with the example we have provided and work your way through.. change the join meeting settings to the one you need and see if that works.

Please follow this template to report issues as it helps us understand the situation a little better. 

Platform: specify one or both: [iOS, Android] 
Device Physical or Simulator: [Physical, Simulator]
Device Model: specify model
Device OS Version: specify Android or iOS version

Flutter Doctor: run flutter doctor and paste results below:
--- flutter doctor results here ---

Steps to recreate: detailed step by step on how to recreate below:
1. Step 1
2. Step 2
...

Error logs:
--- paste error logs here if any ---

**Comment by dhruv1710** [comment]
Have solved it.The problem was i kept the firestore listener on and did not cancel it.
