### ISSUE TITLE
Loading Screen Color and Loading Text Customization

### ISSUE THREAD

**Issue by litzbalane2017** [gunschu/jitsi_meet#110]
Good Day.

Is there a way to customize the loading screen color and loading text below?

![Screenshot_20200913-114502](https://user-images.githubusercontent.com/33191152/93009842-2d3d4880-f5b8-11ea-8f4d-0b9ff8087007.png)

 I am trying to integrate jitsi on my app and would like to make the UI to be as close to as possible with my app.

Thank you.

**Comment by TBG-FR** [comment]
The loading screen is part of the Jitsi Meet SDK. In order to modify it, you'd need to modify and recompile the SDK, and then modifiy the setting in the plugin so the Flutter plugin uses your custom SDK
