### ISSUE TITLE
QUESTION: how to start with back camera by default

### ISSUE THREAD

**Issue by alexlovar** [gunschu/jitsi_meet#111]
hello, there are any flag to alternate the camera and start with back camera by default?

thanks

**Comment by wahyu-handayani** [comment]
hi.. me too, I would like to do the same.. anyone knows?

**Comment by tuantvu** [comment]
@alexlovar @wahyu-handayani Doesn't look like Jitsi Meet supports this right now: https://github.com/jitsi/jitsi-meet/issues/6566
