### ISSUE TITLE
Support platform - Web

### ISSUE THREAD

**Issue by sidrao2006** [gunschu/jitsi_meet#113]
The plugin currently supports only android and iOS.The jitsi meet api supports the web and is stable as well. According to the official [documentation](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe), jitsi meet has an I-frame api.
I believe, with some JS interop and some html code (for iframe) to be added by the user, this feature can be implemented without breaking current user's functionality.

**Comment by TBG-FR** [comment]
Duplicate of #66 (and #95).
You can also check that fork made for WEB : https://github.com/lennhv/jitsi_meet_plugin

**Comment by sidrao2006** [comment]
@TBG-FR thank you
