### ISSUE TITLE
Black background while pictute in picture ios

### ISSUE THREAD

**Issue by syedzahed** [gunschu/jitsi_meet#114]
![Simulator Screen Shot - iPhone 11 Pro - 2020-09-17 at 13 31 08](https://user-images.githubusercontent.com/6910533/93438728-537e2380-f8eb-11ea-8f1b-de51da8cfc79.png)

jitsi_meet: ^0.4.1
flutter: 1.20.3
ios: 13.7
xcode 11.7

**Comment by jimmyjose-dev** [comment]
https://github.com/gunschu/jitsi_meet/issues/120#issuecomment-704934715
