### ISSUE TITLE
Support for screen share

### ISSUE THREAD

**Issue by RohithKilaparthi** [gunschu/jitsi_meet#116]
Hi

The plugin is working great and I seriously appreciate the efforts. There are few things which I would like to know

1) Can we know which users have joined the room?
2) Can we control the mute/video status of participants? If yes, how?
3) Do we have the functionality to share screen? How do we do it?
4) Can we stream the room directly to youtube?

**Comment by RohithKilaparthi** [comment]
@Snapworks 
adding for quick response, thank you

**Comment by jimmyjose-dev** [comment]
1) It actually depends, if all users use your app, then answer is YES, but if you are using jitsi server and users join from web then maybe not. Need more details about the scenario to provide a better answer.

2) In Jitsi only the moderator can turn off the audio of the participant and this feature is only available if you use it from the website/iframe. It is currently not available in the original jitsi mobile sdk and hence not extended in this flutter framework.

_**I am actually working on this feature for their mobile part and hopefully push to the main Jitsi repo soon. Then eventually will port to flutter as well.**_

 Coming back to how it works...
 the moderator **cannot** turn the audio back on for the participant, Jitsi cites privacy concerns and hence wont merge 
 this feature in their sdk, you can however spin your own version (this needs a separate discussion)

_When the feature is made available, we can discuss more about moderators._


3) Share screen is currently **not** available for mobile, exists on web though. It's not on jitsi's priority list and I don't think it will be coming up anytime soon.

4)You can stream the room directly to youtube, you just need to schedule an event in youtube and enter the streamkey in the app. Youtube will start and stop the event automatically so you dont have to worry about that.

**Comment by RohithKilaparthi** [comment]
@Snapworks Thanks for the quick response

1) We have a mobile app through which we are allowing the host to create a room and the participants join the room once it is created. As of now, we are not planning for the web version of live. How do we get to know which participants are live at any point of time. 

2) That would be really helpful. According to what you have said, if the moderator uses the web version and the participants use our mobile app, both screen sharing and audio/video off will be possible. Please correct me if I am wrong.

**Comment by jimmyjose-dev** [comment]
_I will try to keep the discussion as high level as possible so the post doesn't get long._

1) You would need to store the data on a separate server, so flow will be something like this..
a)YourApp->UserLogsIn->BeforeJoin/CreateRoom->SendDataToYourServer->MarkUserAsAvailable->JoinTheCall.
b)JoinCallHasError->MarUserAsUnavailable
c)When UserDisconnects->SendDataToYourServer->MarkUserAsUnavialable
You can make use of the callbacks (if you use didjoinconfrence callback point b is not required)
 
2)Yes, from the web moderator can ONLY TURN OFF audio of all or single participant, moderator CANNOT turn it back ON.Screen sharing is available for all user types on web, you would need to take it out for guest users, its a simple config thing, its available in the docs.

_**Moderator in Jitsi:**_
1) When no authentication is used or you are using Jitsi server
When there is no authentication to identify a user entering the room, the first person to  join a room is elevated to Moderator and rest are guest...
So for example UserA creates room and he/she shares the room link with UserB and UserC, if UserB enters the room before UserA and UserC then UserB will be the moderator and UserA and UserC will be guest. _**Also when the moderator gets disconnected or ends call the next user who had joined the room becomes the moderator. If the previous moderator joins the room again he/she will be joined as Guest**_ The room will not be closed when the moderator disconnects you would have to do that on your own. 

2)If you are hosting jitsi on your own server you can look into prosody and create user/pass combo or use JWT, after this you can also enable waiting room module.
