### ISSUE TITLE
Using JitsiMeetView instead of Activity/Controller

### ISSUE THREAD

**Issue by nareshkatta99** [gunschu/jitsi_meet#117]
Is it possible to use JitsiMeetView instead of opening the JitsiMeetActivity/JitsiViewController?
We have to add few more views over the JitsiView for customizations.
So I want to use JitsiMeetView instead of JitsiMeetActivity/JitsiViewController in both Android and iOS.

**Comment by jimmyjose-dev** [comment]
As of now, Nope.
