### ISSUE TITLE
App Close Automatic in release mode

### ISSUE THREAD

**Issue by luckymehndiratta** [gunschu/jitsi_meet#119]
We integrate JITSI in our Flutter project and when we make a build for release and open JITSI sometime the app closes and sometimes App crash. Please suggest us to resolve this issue.

**Comment by hwnprsd** [comment]
Please follow the documentation
> Note
> If you do not create the proguard-rules.pro file, then your app will crash when you try to join a meeting or the meeting screen tries > to open but closes immediately. You will see one of the below errors in logcat.

**Comment by luckymehndiratta** [comment]
Proguard file already added

**Comment by tuantvu** [comment]
@luckymehndiratta Please follow the issue template from the README to give us more to work with:

Open an issue here. Use the following template:

Platform: specify one or both: [iOS, Android] 
Device Physical or Simulator: [Physical, Simulator]
Device Model: specify model
Device OS Version: specify Android or iOS version

Flutter Doctor: run flutter doctor and paste results below:
--- flutter doctor results here ---

Steps to recreate: detailed step by step on how to recreate below:
1. Step 1
2. Step 2
...

Error logs:
--- paste error logs here if any ---
