### ISSUE TITLE
lang: Korean translation

### ISSUE THREAD

**Issue by yjhgull** [gunschu/jitsi_meet#121]
Jisi has a problem with Korean translation.

I have registered the problem.
issue : https://github.com/jitsi/jitsi-meet/issues/7693

And I have registered a fix for the problem.
pull : https://github.com/jitsi/jitsi-meet/pull/7681

I am using jitsi_meet version 0.4.2, but the translation is not reflected.
Please let me know if there is any way to use the improved Korean version.

**Comment by jimmyjose-dev** [comment]
From what I can infer from the jitsi post, your PR hasn't made through for the main release.
If you prefer not to wait.. 

you would need to make changes in the gradle and podspec file.

Marked below are the entry points from where we pull our dependencies.
For android:
https://github.com/gunschu/jitsi_meet/blob/22bf4eba04d281719211dc5ef8e0bab30082bb7b/android/build.gradle#L20
you can add your local folder as well

For iOS
https://github.com/gunschu/jitsi_meet/blob/22bf4eba04d281719211dc5ef8e0bab30082bb7b/ios/jitsi_meet.podspec#L18
Ditto for iOS

**Comment by yjhgull** [comment]
Thank you so much for leaving a comment.
I've been working hard to solve the problem over the past two days, but I haven't found an answer yet.
I tried applying sdk version 2.10.0, but Korean language was not reflected.
Is there any other way of not using maven-repository?
Should I wait for sdk 2.10.1 or plugin 0.4.3?
Any advice would be appreciated.

**Comment by jimmyjose-dev** [comment]
Yes, as i mentioned above you can attach your local folder instead of remote repo.

Waiting for 2.10.1 is totally upto you .. as I wont be able to comment on their release date, it would be better to ask this on the main Jitisi repo and get some clarity on the timeline.

**Comment by yjhgull** [comment]
Thank you very much for your kind and detailed advice. :)

**Comment by jimmyjose-dev** [comment]
No problem brother :)
