### ISSUE TITLE
Introduce MUC in JitsiMeetingResponse

### ISSUE THREAD

**Issue by kleeb** [gunschu/jitsi_meet#125]
Would be great, and kind of senseful to have user's MUC or at least MUC nickname inside JitsiMeetingResponse

**Comment by tuantvu** [comment]
@kleeb Hi, could you spell out MUC and possibly give some examples? I'm not familiar with the acronym. Thanks.

**Comment by kleeb** [comment]
MUC is jitsi's user id, that is visible in the Jitsi SDK logs. Its passed from the jitsi/jicofo backend as a Member:

```
Jicofo 2020-11-04 09:29:16.328 INFO: [62] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member someone-de1icwlntym43uavolnkys@conference.jitsi.example.app/ef65a68c is leaving
```

it should be passed in the response, so that we are able to build a bridge between the server and the app (for instance to cover all situations where someone left the call without termination hook).

**Comment by jimmyjose-dev** [comment]
>  Hi, could you spell out MUC and possibly give some examples? I'm not familiar with the acronym. Thanks.

@tuantvu MUC(Multi User Chat) is a XMPP protocol that facilitates exchange of messages in the context of room or channel.
Jitsi's userid or jid is actually Jabber ID as it uses Jabber protocol.

**Comment by tuantvu** [comment]
@kleeb @Snapworks thanks for the explanation. I found multi user chat but didn't understand in the original context. I don't recall that value being returned back by the Jitsi Meet SDK though. Maybe it is and we aren't capturing, or we need to implement some listener and capture it?

**Comment by tuantvu** [comment]
@kleeb Any idea if the Jitsi Meet SDK sends back the id? If so, please link the documentation for us. Thanks.
