### ISSUE TITLE
Tap on down button in meet shows black screen

### ISSUE THREAD

**Issue by MysticalNobody** [gunschu/jitsi_meet#131]
![image](https://user-images.githubusercontent.com/20075647/97626540-0c7f6400-1a3b-11eb-8da5-730353bc8d7f.png)
![image](https://user-images.githubusercontent.com/20075647/97626555-130ddb80-1a3b-11eb-8547-ed1f7e4d4e1b.png)

**Dart code:**

```
Future<void> onJoin() async {
    final camera = await Permission.camera.request();
    final microphone = await Permission.microphone.request();
    if (camera.isGranted && microphone.isGranted) {
      onJoinMeeting.value = true;
      // ignore: unawaited_futures
      await JitsiMeet.joinMeeting(
        JitsiMeetingOptions()
          ..serverURL = server'
          ..room = 'room_name'
          ..featureFlags[FeatureFlagEnum.PIP_ENABLED] = Platform.isAndroid
          ..featureFlags[FeatureFlagEnum.TOOLBOX_ALWAYS_VISIBLE] = false
          ..featureFlags[FeatureFlagEnum.TILE_VIEW_ENABLED] = false
          ..featureFlags[FeatureFlagEnum.CLOSE_CAPTIONS_ENABLED] = false
          ..featureFlags[FeatureFlagEnum.CHAT_ENABLED] = false
          ..featureFlags[FeatureFlagEnum.WELCOME_PAGE_ENABLED] = false
          ..featureFlags[FeatureFlagEnum.INVITE_ENABLED] = false
          ..featureFlags[FeatureFlagEnum.MEETING_PASSWORD_ENABLED] = false
          ..featureFlags[FeatureFlagEnum.ADD_PEOPLE_ENABLED] = false
          ..featureFlags[FeatureFlagEnum.CALL_INTEGRATION_ENABLED] = false
          ..userDisplayName = userService.user.expert?.name ?? 'Имя не указано',
      );
      onJoinMeeting.value = false;
    }
  }
```

**Platform:** Android

Is it possible to remove this arrow or show the flutter app instead black screen?

**Update** FeatureFlagEnum.PIP_ENABLED false remove this arrow but PIP mode still works. I think it's wrong behavior

**Comment by tuantvu** [comment]
I don't get a black screen on Android. iOS seems to have issue, see #114. Can you confirm the black screen is for iOS and I will mark this as a duplicate.

**Comment by MysticalNobody** [comment]
> I don't get a black screen on Android. iOS seems to have issue, see #114. Can you confirm the black screen is for iOS and I will mark this as a duplicate.

Black screen was on android when I was clicked on the down button

**Comment by jimmyjose-dev** [comment]
@MysticalNobody do you still have this issue with the new version  ?

**Comment by nathansdev** [comment]
I am facing this issue in iOS @Snapworks . I have tried your suggestions like changing the color to .white from this comment [#218](https://github.com/gunschu/jitsi_meet/issues/218) . But still the same issue persist. Can you help me?

**Comment by jimmyjose-dev** [comment]
https://github.com/gunschu/jitsi_meet/issues/218#issuecomment-796646877
Did you do this thing as well... instead of fullscreen you have to use overCurrentContext...
then delete the app from simulator or device... and then build again.

PS: color  has to transparent and not white for #218 result

**Comment by MysticalNobody** [comment]
> @MysticalNobody do you still have this issue with the new version ?

Yes, issue was solved. Sorry for late reply
