### ISSUE TITLE
Screen sharing, tile view in aplhabetic order, avatar url

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#133]
Everything required is now there. Just add screen sharing to make it perfect as it is very important one. Then please order the participants alphabetically in tile view. Also please add avatar URL. You can also add whiteboard with screen sharing.

**Comment by NVQuan** [comment]
Me too. Please add avatar URL

IOS: in function joinMeeting of class SwiftJitsiMeetPlugin update

                    if let avatarURL = myArgs["userAvatarURL"] as? String {
                        self.jitsiViewController?.jistiMeetUserInfo.avatar = URL(string: avatarURL);
                    }
                    //                    let avatar = myArgs["userAvatarURL"] as? String,
                    //                    let avatarURL  = URL(string: avatar)
                    //                    jitsiViewController?.jistiMeetUserInfo.avatar = avatarURL;

It works for me. Please update the plugin. Thanks

**Comment by jagadish-pattanaik** [comment]
@NVQuan , what to do for Android? How to implement avatar url in flutter for android. Does this also work for Android???

**Comment by NVQuan** [comment]
> @NVQuan , what to do for Android? How to implement avatar url in flutter for android. Does this also work for Android???

https://github.com/gunschu/jitsi_meet/pull/135

It works for both ANDROID/IOS. In ANDROID did in the native(Java/Kotlin) plugin but the flutter not yet added a property userAvatarURL in JitsiMeetingOptions.

**Comment by jagadish-pattanaik** [comment]
@NVQuan can you please give a full example file so that i can get a clear idea how to implement it...Please

**Comment by NVQuan** [comment]
> @NVQuan can you please give a full example file so that i can get a clear idea how to implement it...Please



In lib/JitsiMeet function joinMeeting
.invokeMethod<String>('joinMeeting', <String, dynamic>{
          'room': options.room?.trim(),
          'serverURL': options.serverURL?.trim(),
          'subject': options.subject,
          'token': options.token,
          'audioMuted': options.audioMuted,
          'audioOnly': options.audioOnly,
          'videoMuted': options.videoMuted,
          'featureFlags': options.getFeatureFlags(),
          'userDisplayName': options.userDisplayName,
          'userEmail': options.userEmail,
         // Add this line: 'userAvatarURL': options.userAvatarURL,
        })

in class class JitsiMeetingOptions add property userAvatarURL

class JitsiMeetingOptions {
  ...
  String userEmail;
// Add this line: String userAvatarURL;
}

**Comment by jagadish-pattanaik** [comment]
@NVQuan Thanks Very Much!!! It worked like a charm!!!...Can you also tell how to add KICK_OUT_ENABLED to features flag as it is in the official JItsi Meet SDK but not in the plugin...can you help here in this matter?

**Comment by jimmyjose-dev** [comment]
Making changes to these two files will suffice.
```
lib/feature_flag/feature_flag_enum.dart
lib/feature_flag/feature_flag_helper.dart
```

**Comment by jagadish-pattanaik** [comment]
Thanks but I tried once it failed...let me try once again and see...if I get an error I will post it here...btw I did the same you told..have you tried it?

**Comment by jimmyjose-dev** [comment]
not this one though... but i had added other feature flags long time back...

#84 you may go through this PR for reference ... or if you can share what you tried, we might be able to resolve it faster.

**Comment by jagadish-pattanaik** [comment]
@Snapworks it didnt give an error but it doesnt work....the kick out option doesnt gets disabled...can you also try to add kick out to features flag?

**Comment by jimmyjose-dev** [comment]
Sure brother.. i will take a stab at it.. but it will be more faster to resolve your issue if you share what you are trying...
maybe somewhere along the lines of making **`kick-out.enabled`** as True/False may work...

**Comment by jagadish-pattanaik** [comment]
Yeah I have shared what I had done in #138
