### ISSUE TITLE
Help option in more options in meeting

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#138]
**The help option in more options in meeting page take to the jitsi help website for developers**. Is there any way to hide that option or disable it or even redirect to another site on clicked ? 

If it can be removed by plugin update then please do something about it.

**Comment by jimmyjose-dev** [comment]
If you are using meet.jitsi server you may not be able to hide it from this framework. If you have deployed on your own server you can change that in the config file.

Alternatively, I can share overview of steps if you want to recompile the framework on your own and remove Help option. It will require react code tinkering.

**Comment by jagadish-pattanaik** [comment]
Ok please share the steps...but is it really difficult and unstable? Or can't we have something like redirecting to another link if the jitsi help link is launched?

**Comment by jimmyjose-dev** [comment]
You can redirect or hide it easily if you are hosting jitsi on your own server....

First method .. try feature flags ..
**`help-view.enabled`** as True/False in the feature flags, taking the discussion forward from here #133 


Seconds method ... involves 
1) Downloading jitsi source code, 
2) Installing npm. 
3) Editing source code
4) Building package
5) Adding custom path to gradle
Going down this path for every new Jitsi update you would need to update the source code and follow the process again and you wont be able to use our package ...
There are other drawbacks as well... but if you still want to proceed I will write the steps... The explanation will be pretty long so I want to make sure you want to go through this path... I wouldn't recommend it but I am not aware how critical this feature removal is for you....

**Comment by jagadish-pattanaik** [comment]
The first method is not working.... and also `help-view.enabled` is not in official jitsi meet features flag list.

I tried following:
feature_flag_enum.dart 
`HELP_ENABLED,`// added this line

feature_flag_helper.dart
`FeatureFlagEnum.HELP_ENABLED: 'help-view.enabled', ` // added this line

joinMeeting Function
`FeatureFlagEnum.HELP_ENABLED: false,` //added

The same i tried with kick out enabled but it also didnt work

**Comment by jagadish-pattanaik** [comment]
@Snapworks kick out worked!!

**Comment by jimmyjose-dev** [comment]
🤝, I will be doing a PR for kick out feature later... the help option i am afraid needs update from officially jitsi team.

**Comment by jagadish-pattanaik** [comment]
yes help needs as its not in the list of official features flag but kick out worked

**Comment by jimmyjose-dev** [comment]
Closing this for now

**Comment by maheshperi19** [comment]
> 2\. Installing npm

I have added HELP_ENABLED related properties in dart files. It didn't work for me. For second method, how to download jitsi server and install ?

Can you please explore it with some link to download and install ? 

I am not aware of server code as i am frontend developer.

It is correctly printing arguments list as true or false for help-view.enabled.

arguments: {videoMuted=false, subject=null, serverURL=null, audioOnly=false, userAvatarURL=null, audioMuted=false, userDisplayName=Star, userEmail=null, room=Star, token=null, featureFlags={raise-hand.enabled=false, kick-out.enabled=false, ios.recording.enabled=false, pip.enabled=false, help-view.enabled=false, welcomepage.enabled=false, toolbox.alwaysVisible=true, video-share.enabled=false, server-url-change.enabled=false, tile-view.enabled=true, add-people.enabled=false, conference-timer.enabled=true, meeting-password.enabled=false, recording.enabled=false, live-streaming.enabled=false, call-integration.enabled=false, chat.enabled=true, invite.enabled=false, calendar.enabled=false, meeting-name.enabled=false, close-captions.enabled=false}}

**Comment by jimmyjose-dev** [comment]
@MaheshPeri19 Though we can share the steps but it would be better if you post custom Jitsi related queries on the main Jitsi repo page or check out their developer forum.

Help_enabled currently doesn't work.

**Comment by maheshperi19** [comment]
Okay Thank you.

**Comment by Muhammad-Ullah** [comment]
FeatureFlagEnum.KICK_OUT_ENABLED is not working? Any one please
