### ISSUE TITLE
IOS Build Pod Error

### ISSUE THREAD

**Issue by saichon-toiem** [gunschu/jitsi_meet#14]
when run app in android studio i found this error please help.

//- added in info.plist --------
    <key>CFBundleName</key>
    <string>jitsi_meet</string>
//---------

//- Error-------------
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `barcode_scan` from `.symlinks/plugins/barcode_scan/ios`
    -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_core_web` from `.symlinks/plugins/firebase_core_web/ios`
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    -> Fetching podspec for `firebase_storage` from `.symlinks/plugins/firebase_storage/ios`
    -> Fetching podspec for `flutter_plugin_android_lifecycle` from `.symlinks/plugins/flutter_plugin_android_lifecycle/ios`
    -> Fetching podspec for `flutter_tts` from `.symlinks/plugins/flutter_tts/ios`
    -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `geolocator` from `.symlinks/plugins/geolocator/ios`
    -> Fetching podspec for `google_api_availability` from `.symlinks/plugins/google_api_availability/ios`
    -> Fetching podspec for `image_downloader` from `.symlinks/plugins/image_downloader/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `jitsi_meet` from `.symlinks/plugins/jitsi_meet/ios`
    -> Fetching podspec for `keyboard_visibility` from `.symlinks/plugins/keyboard_visibility/ios`
    -> Fetching podspec for `location` from `.symlinks/plugins/location/ios`
    -> Fetching podspec for `multi_image_picker` from `.symlinks/plugins/multi_image_picker/ios`
    -> Fetching podspec for `open_file` from `.symlinks/plugins/open_file/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `path_provider_macos` from `.symlinks/plugins/path_provider_macos/ios`
    -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `ringtone` from `.symlinks/plugins/ringtone/ios`
    -> Fetching podspec for `share` from `.symlinks/plugins/share/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `trust_fall` from `.symlinks/plugins/trust_fall/ios`
    -> Fetching podspec for `uni_links` from `.symlinks/plugins/uni_links/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `url_launcher_macos` from `.symlinks/plugins/url_launcher_macos/ios`
    -> Fetching podspec for `url_launcher_web` from `.symlinks/plugins/url_launcher_web/ios`
    -> Fetching podspec for `vibration` from `.symlinks/plugins/vibration/ios`
    -> Fetching podspec for `youtube_api` from `.symlinks/plugins/youtube_api/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "jitsi_meet":
      In Podfile:
        jitsi_meet (from `.symlinks/plugins/jitsi_meet/ios`)

    Specs satisfying the `jitsi_meet (from `.symlinks/plugins/jitsi_meet/ios`)` dependency were found, but they required a higher minimum deployment target.

    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/resolver.rb:91:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:909:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:907:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:114:in `analyze'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `10.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11 Pro Max.
//------------

**Comment by buzzwin** [comment]
Please set iOS version no. to 11.0 or higher and retry.

**Comment by saichon-toiem** [comment]
> Please set iOS version no. to 11.0 or higher and retry.
> […](#)
> Sent from my iPhone
> On Apr 11, 2020, at 7:55 PM, Saichon To-iem ***@***.***> wrote: ﻿ when run app in android studio i found this error please help. //- added in info.plist -------- CFBundleName jitsi_meet //--------- //- Error------------- Launching lib/main.dart on iPhone 11 Pro Max in debug mode... Running pod install... CocoaPods' output: ↳ Preparing Analyzing dependencies Inspecting targets to integrate Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``) Fetching external sources -> Fetching podspec for `Flutter` from `Flutter` -> Fetching podspec for `barcode_scan` from `.symlinks/plugins/barcode_scan/ios` -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios` -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios` -> Fetching podspec for `firebase_core_web` from `.symlinks/plugins/firebase_core_web/ios` -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios` -> Fetching podspec for `firebase_storage` from `.symlinks/plugins/firebase_storage/ios` -> Fetching podspec for `flutter_plugin_android_lifecycle` from `.symlinks/plugins/flutter_plugin_android_lifecycle/ios` -> Fetching podspec for `flutter_tts` from `.symlinks/plugins/flutter_tts/ios` -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios` -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios` -> Fetching podspec for `geolocator` from `.symlinks/plugins/geolocator/ios` -> Fetching podspec for `google_api_availability` from `.symlinks/plugins/google_api_availability/ios` -> Fetching podspec for `image_downloader` from `.symlinks/plugins/image_downloader/ios` -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios` -> Fetching podspec for `jitsi_meet` from `.symlinks/plugins/jitsi_meet/ios` -> Fetching podspec for `keyboard_visibility` from `.symlinks/plugins/keyboard_visibility/ios` -> Fetching podspec for `location` from `.symlinks/plugins/location/ios` -> Fetching podspec for `multi_image_picker` from `.symlinks/plugins/multi_image_picker/ios` -> Fetching podspec for `open_file` from `.symlinks/plugins/open_file/ios` -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios` -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios` -> Fetching podspec for `path_provider_macos` from `.symlinks/plugins/path_provider_macos/ios` -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios` -> Fetching podspec for `ringtone` from `.symlinks/plugins/ringtone/ios` -> Fetching podspec for `share` from `.symlinks/plugins/share/ios` -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios` -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios` -> Fetching podspec for `trust_fall` from `.symlinks/plugins/trust_fall/ios` -> Fetching podspec for `uni_links` from `.symlinks/plugins/uni_links/ios` -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios` -> Fetching podspec for `url_launcher_macos` from `.symlinks/plugins/url_launcher_macos/ios` -> Fetching podspec for `url_launcher_web` from `.symlinks/plugins/url_launcher_web/ios` -> Fetching podspec for `vibration` from `.symlinks/plugins/vibration/ios` -> Fetching podspec for `youtube_api` from `.symlinks/plugins/youtube_api/ios` Resolving dependencies of `Podfile` [!] CocoaPods could not find compatible versions for pod "jitsi_meet": In Podfile: jitsi_meet (from `.symlinks/plugins/jitsi_meet/ios`) Specs satisfying the `jitsi_meet (from `.symlinks/plugins/jitsi_meet/ios`)` dependency were found, but they required a higher minimum deployment target. /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/resolver.rb:91:in `resolve' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:909:in `block in resolve_dependencies' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:907:in `resolve_dependencies' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:114:in `analyze' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>' /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load' /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>' Error output from CocoaPods: ↳ [!] Automatically assigning platform `ios` with version `10.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `[https://guides.cocoapods.org/syntax/podfile.html#platform`](https://guides.cocoapods.org/syntax/podfile.html#platform%60). Error running pod install Error launching application on iPhone 11 Pro Max. //------------ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by saichon-toiem** [comment]
> Please set iOS version no. to 11.0 or higher and retry.
> […](#)
> Sent from my iPhone
> On Apr 11, 2020, at 7:55 PM, Saichon To-iem ***@***.***> wrote: ﻿ when run app in android studio i found this error please help. //- added in info.plist -------- CFBundleName jitsi_meet //--------- //- Error------------- Launching lib/main.dart on iPhone 11 Pro Max in debug mode... Running pod install... CocoaPods' output: ↳ Preparing Analyzing dependencies Inspecting targets to integrate Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``) Fetching external sources -> Fetching podspec for `Flutter` from `Flutter` -> Fetching podspec for `barcode_scan` from `.symlinks/plugins/barcode_scan/ios` -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios` -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios` -> Fetching podspec for `firebase_core_web` from `.symlinks/plugins/firebase_core_web/ios` -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios` -> Fetching podspec for `firebase_storage` from `.symlinks/plugins/firebase_storage/ios` -> Fetching podspec for `flutter_plugin_android_lifecycle` from `.symlinks/plugins/flutter_plugin_android_lifecycle/ios` -> Fetching podspec for `flutter_tts` from `.symlinks/plugins/flutter_tts/ios` -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios` -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios` -> Fetching podspec for `geolocator` from `.symlinks/plugins/geolocator/ios` -> Fetching podspec for `google_api_availability` from `.symlinks/plugins/google_api_availability/ios` -> Fetching podspec for `image_downloader` from `.symlinks/plugins/image_downloader/ios` -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios` -> Fetching podspec for `jitsi_meet` from `.symlinks/plugins/jitsi_meet/ios` -> Fetching podspec for `keyboard_visibility` from `.symlinks/plugins/keyboard_visibility/ios` -> Fetching podspec for `location` from `.symlinks/plugins/location/ios` -> Fetching podspec for `multi_image_picker` from `.symlinks/plugins/multi_image_picker/ios` -> Fetching podspec for `open_file` from `.symlinks/plugins/open_file/ios` -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios` -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios` -> Fetching podspec for `path_provider_macos` from `.symlinks/plugins/path_provider_macos/ios` -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios` -> Fetching podspec for `ringtone` from `.symlinks/plugins/ringtone/ios` -> Fetching podspec for `share` from `.symlinks/plugins/share/ios` -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios` -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios` -> Fetching podspec for `trust_fall` from `.symlinks/plugins/trust_fall/ios` -> Fetching podspec for `uni_links` from `.symlinks/plugins/uni_links/ios` -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios` -> Fetching podspec for `url_launcher_macos` from `.symlinks/plugins/url_launcher_macos/ios` -> Fetching podspec for `url_launcher_web` from `.symlinks/plugins/url_launcher_web/ios` -> Fetching podspec for `vibration` from `.symlinks/plugins/vibration/ios` -> Fetching podspec for `youtube_api` from `.symlinks/plugins/youtube_api/ios` Resolving dependencies of `Podfile` [!] CocoaPods could not find compatible versions for pod "jitsi_meet": In Podfile: jitsi_meet (from `.symlinks/plugins/jitsi_meet/ios`) Specs satisfying the `jitsi_meet (from `.symlinks/plugins/jitsi_meet/ios`)` dependency were found, but they required a higher minimum deployment target. /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/resolver.rb:91:in `resolve' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:909:in `block in resolve_dependencies' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:907:in `resolve_dependencies' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:114:in `analyze' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run' /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>' /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load' /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>' Error output from CocoaPods: ↳ [!] Automatically assigning platform `ios` with version `10.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `[https://guides.cocoapods.org/syntax/podfile.html#platform`](https://guides.cocoapods.org/syntax/podfile.html#platform%60). Error running pod install Error launching application on iPhone 11 Pro Max. //------------ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks you Works
