### ISSUE TITLE
onconferenceterminated no called

### ISSUE THREAD

**Issue by Nadee740** [gunschu/jitsi_meet#140]
Platform:[iOS, Android] 
Device Physical or Simulator: [Physical, Simulator]
Device Model: all model

Flutter Doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.22.0-12.2.pre, on Microsoft Windows [Version 10.0.19041.630], locale
    en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.51.1)
[√] Connected device (4 available)

Steps to recreate: detailed step by step on how to recreate below:
1. onconferenceterminate method is not being called while using the plugin
2. 
...

Error logs:
--- paste error logs here if any ---

**Comment by jimmyjose-dev** [comment]
could you share what you have done.. in terms of listener and the function.
