### ISSUE TITLE
Screen sharing not in version 1.1.0 ?

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#146]
Is screen sharing not there in version 1.0.1 or its some problem with me? Because I couldn't find in options to share screen...

**Comment by jimmyjose-dev** [comment]
Two things:
1) This is android only version
2) Delete the existing app from simulator/device and run again.

**Comment by jagadish-pattanaik** [comment]
@Snapworks  Yeah I am running it on Android and after updating the plugin version to 1.0.1...(not pr)  I  did flutter clean and deleted the old app for my device and then installed it. But after that also there is no option to share screen...

I used a tablet or testing...that is on Android 8.1.0

The only thing I found new was avatar url

**Comment by jimmyjose-dev** [comment]
Working fine with the new code..
<img src="https://dl.dropboxusercontent.com/s/stp5l4ieks1tj24/screenshare.jpg" />

**Comment by jagadish-pattanaik** [comment]
Okayy...is it because I was using a tablet for testing or it was android 8.1.0?

**Comment by jagadish-pattanaik** [comment]
@Snapworks  no its not showing... there is no option 'Start Screen sharing'. After trying on my tab then i tried on my phone too.. but there is no option.. are you showing me the pr version? because i am not getting it on vesion 1.1.0 stable. Please help

**Comment by jimmyjose-dev** [comment]
Please share the version you see at the bottom of bundle.gradle file
`implementation ('org.jitsi.react:jitsi-meet-sdk:2.11.0') { transitive = true }`

should be **2.11.0**

I have tested on Android 10, minimum sdk version for jitsi is 23.. so it should work on Android 6.0 and above.

**Comment by jimmyjose-dev** [comment]
@jagadish-pattanaik you are right brother.. the code was merged to the code base but was not released in 1.1.0, the sample example should have worked anyways as it has the latest version. [2.11.0](https://github.com/gunschu/jitsi_meet/blob/63b451934656ee7e804e940fdbb615c0356783c6/android/build.gradle#L53)

@tuantvu bro, please do the needful.

**Comment by jagadish-pattanaik** [comment]
So @Snapworks what should I do? Will adding this line work? `implementation ('org.jitsi.react:jitsi-meet-sdk:2.11.0') { transitive = true }` or should i wait for @tuantvu  to release an update by adding screen sharing? and will it take a lot of time?

By the way in bundle.gradle its` implementation ('org.jitsi.react:jitsi-meet-sdk:2.10.0') { transitive = true }` i.e 2.10.0

**Comment by jimmyjose-dev** [comment]
Change 2.10.0 to 2.11.0, delete app from device/simulator and run again. It should work for you... do confirm if it works.

We will hopefully release it soon ... I am not aware of his work schedule so wont be able to confirm anything.

**Comment by tuantvu** [comment]
I was trying to test but think I need to downgrade xcode. Will try to fix my workspace tomorrow.

**Comment by jagadish-pattanaik** [comment]
@Snapworks and @tuantvu  its working when change from 2.10.0 to this `implementation ('org.jitsi.react:jitsi-meet-sdk:2.11.0') { transitive = true }`

**Comment by tuantvu** [comment]
@jagadish-pattanaik 1.1.0 was for userAvatar. 1.2.0 just got published which was @Snapworks screensharing PR. I was unable to test it do to xcode, but trust everyone here did.
