### ISSUE TITLE
Access the raw audio during meeting

### ISSUE THREAD

**Issue by AdityaTaggar05** [gunschu/jitsi_meet#147]
I was trying to make something that would access the raw audio and process it to get some analytics about the meet and also to support some of the features that I have in my app. I want the audio of all the participants and want to know who has spoken what. But I can't figure out how to do the same?

**Comment by jimmyjose-dev** [comment]
Getting the real Raw audio using this package would be hard if not impossible.

Alternatively you can try this to get the audio, these are just suggestions take it with a pinch of salt.

1) For all meeting add your own extra member which captures audio over the web.. this can be done if you are using some kind of rest api to manage meeting status.

2) Start a recording session in the background of the moderator as soon as the meeting starts and process the audio when the meeting ends.

3) Start an audio session on every user if you want to identify them individually.

4) If you are hosting this at your own server, you may setup Jibri to handle recording. (Jibri instances needed = Number of simultaneous recordings you wanna do, which is an overkill). There are paid services that can handle this for you.

Hope this helps.

**Comment by jimmyjose-dev** [comment]
Please reopen this issue if needed....
