### ISSUE TITLE
Can not play youtube at android 10

### ISSUE THREAD

**Issue by ducnmhn** [gunschu/jitsi_meet#149]
Hi @Snapworks , @tuantvu ,

I have other issue with youtube share. When I share youtube in room, video can auto play ( tested at iOS, android 7 samsung A9 ).
But at android 10 ( tested pixel 3xl , samsung s10 ), youtube can not auto play, so I try touch to "play" button , video pause immediately...

I downloaded jitsi and check at play store and does not have any problem...

**Comment by jimmyjose-dev** [comment]
tried on Samsung S9 Plus.. Android 10... working fine.

Could you try deleting the app from device, restart the phone and try again...

**Comment by ducnmhn** [comment]
> tried on Samsung S9 Plus.. Android 10... working fine.
> 
> Could you try deleting the app from device, restart the phone and try again...

Sorry, I checked my issue because I not set "callIntegrationEnabled" at android.

`REMARK about Call integration Call integration on Android (known as ConnectionService) has been disabled on the official Jitsi Meet app because it creates a lot of issues. You should disable it too to avoid these issues.`

Thank for you help.
