### ISSUE TITLE
can not deploy app in app store

### ISSUE THREAD

**Issue by saichon-toiem** [gunschu/jitsi_meet#15]
Apple reply.
This app cannot be approved with CallKit functionality active in China. Please make the appropriate changes and resubmit this app for review.

If you have already ensured that CallKit functionality is not active in China, you may reply to this message in Resolution Center to confirm.

Voice over Internet Protocol (VoIP) call functionality continues to be allowed but can no longer take advantage of CallKit’s intuitive look and feel. CallKit can continue to be used in apps outside of China.

Please help.

**Comment by TBG-FR** [comment]
You can disable the usage of CallKit using the feature flag `call-integration.enabled`, so you may be able to publish your app

Description of this feature flag [found here](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js)
> Flag indicating if call integration (CallKit on iOS, ConnectionService on Android) should be enabled.

We faced the same issue and removed China from the allowed countries on Apple Store, but I guess that it's not what you want

**Comment by tuantvu** [comment]
@saichon-toiem Were you able to solve the issue?
