### ISSUE TITLE
No implementation found for method listen on channel jitsi_meet_events

### ISSUE THREAD

**Issue by pishguy** [gunschu/jitsi_meet#151]
> jitsi_meet: ^1.2.0

```
MissingPluginException(No implementation found for method listen on channel jitsi_meet_events)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:540:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:526:64)
...
════════════════


V/AudioManager(17112): playSoundEffect   effectType: 0
I/flutter (17112): JitsiMeetingOptions: JitsiMeetingOptions{room: nebrassRoom, serverURL: https://meet.jit.si/, subject: My Plugin Test Meeting, token: null, audioMuted: true, audioOnly: true, videoMuted: true, 
userDisplayName: Plugin Test User, userEmail: salam@email.com, userAvatarURL: null, featureFlags: {} }
I/flutter (17112): error: MissingPluginException(
No implementation found for method joinMeeting on channel jitsi_meet), 
type: MissingPluginException
```

**Comment by jimmyjose-dev** [comment]
Could you share the part of the code where you are initiating join meeting with feature flags

**Comment by pishguy** [comment]
I checked your source code which that's into sample directory

**Comment by jimmyjose-dev** [comment]
Just did a quick test on iPhone 12 simulator with iOS 14.2, worked fine for me... are you getting this error on android ?

Could you share the steps to reproduce this error ?

**Comment by pishguy** [comment]
> 
> 
> Just did a quick test on iPhone 12 simulator with iOS 14.2, worked fine for me... are you getting this error on android ?
> 
> Could you share the steps to reproduce this error ?

Yes i get this error on Android,
i think problem solved after changing repository to `github`

**Comment by pNAIA** [comment]
> > Just did a quick test on iPhone 12 simulator with iOS 14.2, worked fine for me... are you getting this error on android ?
> > Could you share the steps to reproduce this error ?
> 
> Yes i get this error on Android,
> i think problem solved after changing repository to `github`

Where is this change in github done? Please elaborate, we are facing the same issue. Thanks

**Comment by Muhammad-Ullah** [comment]
Same problem. Event the code is from official flutter jitsi_meet repo.
Any solution?

**Comment by pishguy** [comment]
@pNAIA 
@Muhammad-Ullah 

instead of installing from repository please use github source code

**Comment by Muhammad-Ullah** [comment]
Thanks it worked @pNAIA .
