### ISSUE TITLE
Feature disable toolbox

### ISSUE THREAD

**Issue by pishguy** [gunschu/jitsi_meet#154]
in bottom of meeting `Activity` we have some feature such as `Mute Audio`, `Close`, `Mute Video`, how can we disable or hide them?

![Screenshot_20201125-192807](https://user-images.githubusercontent.com/6617583/100252245-e7581580-2f54-11eb-8625-f70044ac5251.jpg)

**Comment by jimmyjose-dev** [comment]
Currently this is not supported using this package.
