### ISSUE TITLE
chanage featureFlag during meeting

### ISSUE THREAD

**Issue by pishguy** [gunschu/jitsi_meet#155]
as we know, we have some `featureFlag` when we want to start new meeting, how can i change `featureFlag` parameters during meeting? such as `resolution`, is any options?

**Comment by jimmyjose-dev** [comment]
That feature is currently available only in web browsers, the best you can do right now is choose the low bandwidth mode from the options during the meeting..

Before the meeting you may use these values of resolution to override server settings
`LD_RESOLUTION for 180p, MD_RESOLUTION for 360p, SD_RESOLUTION for 480p(SD), HD_RESOLUTION for 720p(HD) `
