### ISSUE TITLE
[BUG]: Activity opened by PIP does not get deleted after the meeting has ended

### ISSUE THREAD

**Issue by frencojobs** [gunschu/jitsi_meet#156]
If I would enter into the PIP mode from a call and close the app, and then get back into the call from the PIP widget, the call would be in an entirely different activity. I can't go back into my app from that activity. Even when I end the call, the activity history would be preserved. The activity should be completely removed when the call has ended.

## Reproduction

1. make a call
2. get into the PIP mode
3. close the app with the PIP floating widget still
4. get into the call from the PIP floating widget
5. end the call

It can be seen that the activity for the call is not removed in the recent view. Clicking the activity will lead the user back into the call again.

---

I don't think it is an expected/intentional manner. The call shouldn't be in a new activity when the user maximizes from PIP. Even if the call has to have a separate activity, that activity should be removed when the call has ended.

**Comment by jagadish-pattanaik** [comment]
Yes please solve this problem...

**Comment by Belohun** [comment]
Same issue :( 
Also can't turn off Picture in Picture mode using  FeatureFlagEnum.PIP_ENABLED: false which only disable button for entering PiP.
I menaged to turn it off with work-around adding to AndroidManifest:
`<activity android:name="com.gunschu.jitsi_meet.JitsiMeetPluginActivity"
            tools:replace="android:supportsPictureInPicture"
            android:supportsPictureInPicture="false"></activity>`
but it's not the best way, beacuse it crashes app if video call is minimalized more than one time

**Comment by paulinaurbas** [comment]
I have the same issue :(

**Comment by Omar300HP** [comment]
Yes please solve this problem it is still happening

**Comment by jagadish-pattanaik** [comment]
This pip problem is actually big one even if I end the meeting and close the app. I can find the meeting screen in recent widgets. Please solve this prob. Or is there any way to turn off pip? As feature flags method in not working.

**Comment by jagadish-pattanaik** [comment]
Is the project active any more? I don't see any responses neither new versions?
