### ISSUE TITLE
Where is the recorded meeting video in the device?

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#157]
I started recording a meeting and then after I stopped I check my files but couldn't find any recorded video.

**Comment by jimmyjose-dev** [comment]
Jitsi recordings are handled by Jibri and the files are saved based on the path specified in the script/config file (always a remote server)... nothing is saved on any local device.

alternatively you may try this #147

**Comment by jagadish-pattanaik** [comment]
Then how will a user get the recording of his or her meeting...then recording is useless if we can't get the video

**Comment by jimmyjose-dev** [comment]
To get the recording you have three options:

1. Buy their commercial product 8x8.
2. Host Jitsi on your own server and add Jibri.
3. Its open source, you are free to add the missing piece.
