### ISSUE TITLE
Custom iOS SDK

### ISSUE THREAD

**Issue by nareshkatta99** [gunschu/jitsi_meet#158]
How to import iOS SDK build from our own sources?

**Comment by jimmyjose-dev** [comment]
You would get better assistance for custom SDK on the official Jitsi forum and repo.

But here it is in a nutshell...

After you have run the script to compile the code, you will find a _link_ to the framework inside ios/sdk folder. Follow the link to get the original file, you can drag and drop in your project as any other framework.. make sure to add the webrtc framework as well.

**Comment by nareshkatta99** [comment]
There are some changes I have to do to flutter framework as well.
I generated the frameworks using the commands given in Jitsi documentation website.
I'm finding it hard to use them.
I tried to copy them to jitsi_meet/ios folder but it is not being used.
Can someone help me to use them in the gunschu/jitsi_meet/ios folder, not the jitsi_meet/example/ios folder?
