### ISSUE TITLE
how to disable the settings icon in the meeting

### ISSUE THREAD

**Issue by realjatinpandey** [gunschu/jitsi_meet#159]
Please tell how to disable the three dot icon in the app, I know it is done through changing in the SDK source code, but can you please provide a step by step detailed solution on how to disable the three dot menu button in the app.

**Comment by jimmyjose-dev** [comment]
This would require changes in the react native code, while we can share steps to do it... it will make more sense if you post this on the main Jitsi developer forum.

**Comment by realjatinpandey** [comment]
@Snapworks i did find a solution on the main Jitsi developer forum, https://community.jitsi.org/t/how-to-how-to-customize-meeting-options/74665 but that can be done by adding `#config.prejoinPageEnabled=true&config.remoteVideoMenu.disableKick=true` code like this at the end of the meeting url, but the issue is how do I add this at the end of the meeting url? If we add this thing in the dart file,(in the variable options) `..room = 'example#config.prejoinPageEnabled=true&config.remoteVideoMenu.disableKick=true'` , it shows an error `ror: 'package:jitsi_meet/jitsi_meet.dart': Failed assertion: line 64 pos 13: 'constraint.checkConstraint(options.room)': Only alphanumeric, dash, and underscore chars allowed` So how do I add this code at the end of the meeting url?

**Comment by jimmyjose-dev** [comment]
Those are get params valid only for web, to remove the 3 dots completely will require modifying the react native code.
maybe you wanted to post this on your other post #160 ... i will answer this there...

**Comment by realjatinpandey** [comment]
@Snapworks  Thanks a lot for the help! Can you provide the link to the code which I need to change to hide the 3 dot menu button. As per this https://community.jitsi.org/t/how-can-i-remove-hide-option-buttons-from-overflowmenu/22567/2 the issue seems to be fixed by the modification of these two files  https://github.com/jitsi/jitsi-meet/blob/master/react/features/toolbox/components/native/Toolbox.js https://github.com/jitsi/jitsi-meet/blob/master/react/features/toolbox/components/native/OverflowMenu.js

But then how do I modify this, and rebuild the SDK and then make a flutter plugin out of this so that I can use it on my flutter app? (I am not using any custom servers)

**Comment by jimmyjose-dev** [comment]
If you follow this path you wont be able to use our package in your project.... secondly this might not be the appropriate place for this query but i will nudge you in the right direction and you can take it forward from there.

**Jitisi code rebuilding currently supports only MAC OS**
1) Install Latest Node, NPM and Xcode on your system
2) Download the latest source code from Jitsi repo
3) Open the file `react/features/toolbox/components/native/Toolbox.js` in your editor
4) Comment line `118-120`, and save it.
5) Rum `npm install`
6) To build the framework for android run the script inside the android folder `./android/scripts/release-sdk.sh <full path to where the new framework is to be saved >`
7) For iOS `xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive` this should work
8) To build for flutter add the full path of the new saved framework(step 5) instead of the maven repo for jitsi, inside the gradle file
9) In iOS instead of jitsi podspec use the framework from step 7.
10) Follow the same process to edit in other files for #160 

The three dots in Jitsi is called `overflow menu`

**Comment by realjatinpandey** [comment]
@Snapworks does this process requires buying a custom server, or it can be done in the meet.jit.si servers also?

**Comment by jimmyjose-dev** [comment]
Yes brother it will work with meet.jit.si server

**Comment by realjatinpandey** [comment]
@Snapworks Thanks a lot for solving this issue. I think now I will be able to do it. Closing this for now.

**Comment by yevgeniaronov** [comment]
> If you follow this path you wont be able to use our package in your project.... secondly this might not be the appropriate place for this query but i will nudge you in the right direction and you can take it forward from there.
> 
> **Jitisi code rebuilding currently supports only MAC OS**
> 
> 1. Install Latest Node, NPM and Xcode on your system
> 2. Download the latest source code from Jitsi repo
> 3. Open the file `react/features/toolbox/components/native/Toolbox.js` in your editor
> 4. Comment line `118-120`, and save it.
> 5. Rum `npm install`
> 6. To build the framework for android run the script inside the android folder `./android/scripts/release-sdk.sh <full path to where the new framework is to be saved >`
> 7. For iOS `xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive` this should work
> 8. To build for flutter add the full path of the new saved framework(step 5) instead of the maven repo for jitsi, inside the gradle file
> 9. In iOS instead of jitsi podspec use the framework from step 7.
> 10. Follow the same process to edit in other files for #160
> 
> The three dots in Jitsi is called `overflow menu`



> If you follow this path you wont be able to use our package in your project.... secondly this might not be the appropriate place for this query but i will nudge you in the right direction and you can take it forward from there.
> 
> **Jitisi code rebuilding currently supports only MAC OS**
> 
> 1. Install Latest Node, NPM and Xcode on your system
> 2. Download the latest source code from Jitsi repo
> 3. Open the file `react/features/toolbox/components/native/Toolbox.js` in your editor
> 4. Comment line `118-120`, and save it.
> 5. Rum `npm install`
> 6. To build the framework for android run the script inside the android folder `./android/scripts/release-sdk.sh <full path to where the new framework is to be saved >`
> 7. For iOS `xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive` this should work
> 8. To build for flutter add the full path of the new saved framework(step 5) instead of the maven repo for jitsi, inside the gradle file
> 9. In iOS instead of jitsi podspec use the framework from step 7.
> 10. Follow the same process to edit in other files for #160
> 
> The three dots in Jitsi is called `overflow menu`

hi, i have the same issue.. i want to remove the overflow menu from screen.
how can i do so without a mac?

**Comment by jimmyjose-dev** [comment]
Thanks for your patience buddy... I don't think the build system currently supports Windows OS.
