### ISSUE TITLE
fatal error: module 'jitsi_meet' not found  @import jitsi_meet; IOS Devices

### ISSUE THREAD

**Issue by gurungsuraaj** [gunschu/jitsi_meet#16]
Jitsi is working fine on IOS simulator but I m having problem while running it on physical device.

Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/navrajsharma/Desktop/my_project_name/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'jitsi_meet' not found
    @import jitsi_meet;
     ~~~~~~~^~~~~~~~~~
    1 error generated.
    /Users/navrajsharma/Desktop/my_project_name/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'jitsi_meet' not found
    @import jitsi_meet;
     ~~~~~~~^~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

**Comment by grupoinnovar** [comment]
same error but trying to run on a physical android phone:


FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'jitsi_meet'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by nelsonrosa3** [comment]
does some one know how to fix this issue?

**Comment by gurungsuraaj** [comment]
> does someone know how to fix this issue?
These errors are due to naming error in the ios files.
For IOS, open the file which is causing the header not found and in the import, section replaces jitsi_meet to jitsi_meet_plugin and try again. Hope it might work. Also, try to replace jisti_meet.h file in ios file to jisti_meet_plugin.h, I tried different ways, and it works out for me.

**Comment by parvinder-isp** [comment]
@gurungsuraaj 
can you please share a zip file so that we can check

**Comment by piyushrathodIn** [comment]
I am having same issue, even I can not run demo app by @gunschu in iOS, I am using Xcode 11.3.

**Comment by piyushrathodIn** [comment]
It's not working on Simulator either : 
![image](https://user-images.githubusercontent.com/60957238/81548821-82afe180-939b-11ea-9017-eba7a5cca752.png)

**Comment by buzzwin** [comment]
Just tested and released a new version yesterday .. I had no issues with Xcode 11.3.

    On Monday, May 11, 2020, 04:33:21 AM CDT, Piyush Rathod <notifications@github.com> wrote:  
 
 


I am having same issue, even I can not run demo app by @gunschu in iOS, I am using Xcode 11.3.

**Comment by orkwizard** [comment]
> Just tested and released a new version yesterday .. I had no issues with Xcode 11.3.

Could you share the config you used ?

Cocoapods version, flutter et all 

Thanks

Regards

**Comment by piyushrathodIn** [comment]
> mail directly, view it on GitH

I used latest version of the plugin i.e. 0.2.0 but still getting same error. I am using iPhone Simulator. I don't know where I am making mistakes.

**Comment by piyushrathodIn** [comment]
> > mail directly, view it on GitH
> 
> I used latest version of the plugin i.e. 0.2.0 but still getting same error. I am using iPhone Simulator. I don't know where I am making mistakes.

In addition, my app is built by using Objective-C.

**Comment by rwbr** [comment]
I had the same problem: the project built successfully for the simulator `flutter build ios --simulator`, but failed with the error `fatal error: module 'jitsi_meet' not found`, when building for the device.

I had to open the Runner.xcworkspace in Xcode and go to the Genera tab to set the **Deployment Target version to 11.0**:
<img width="663" alt="Bildschirmfoto 2020-05-18 um 21 27 01" src="https://user-images.githubusercontent.com/144948/82251880-51f91a80-994e-11ea-9eb6-6b63e3130586.png">

After that I was able to successfully compile it for both simulator and device.

BTW: The example project in the example folder of the jitsi_meet repository also has the target version set to 11.0

**Comment by piyushrathodIn** [comment]
I've solved the issue by using lower version of JistiMeet SDK for Xcode11.3

**Comment by tuantvu** [comment]
@gurungsuraaj Latest version supports Xcode 11.4 now. Are you still having the issue?
