### ISSUE TITLE
how to disable participant options in the meeting

### ISSUE THREAD

**Issue by realjatinpandey** [gunschu/jitsi_meet#160]
Please tell how to disable this(image attached below) participant menu screen in the app, when we long click a participant name. I know it is done through changing in the SDK source code, but can you please provide a step by step detailed solution on how to disable that menu for the participants in the app.
![Screenshot_2020-11-27-23-16-30-39_deac82631cadc78707327e04ced022c6](https://user-images.githubusercontent.com/61503868/100479104-39df3080-3113-11eb-944b-176fa20dcf81.png)

**Comment by jimmyjose-dev** [comment]
#159

**Comment by jimmyjose-dev** [comment]
Continuing from your reply on #159 ...
The equivalent for config params is called Feature Flags and you can find all the options on the readme page...
You would have to do something like this...
```
FeatureFlag featureFlag = FeatureFlag();
featureFlag.kickOutEnabled = false;
```

This will hide kick out option... mute all appears only for admin user

Send private message.... you can use chatEnabled = false, I am not sure if it will hide this option but will remove the chat icon besides the mic icon.

To remove the option view completely, you would need to change the react native code.

**Comment by realjatinpandey** [comment]
Moved that reply from #159 to #160

@Snapworks i did find a solution on the main Jitsi developer forum, https://community.jitsi.org/t/how-to-how-to-customize-meeting-options/74665 but that can be done by adding `#config.prejoinPageEnabled=true&config.remoteVideoMenu.disableKick=true` code like this at the end of the meeting url, but the issue is how do I add this at the end of the meeting url? If we add this thing in the dart file,(in the variable options) `..room = 'example#config.prejoinPageEnabled=true&config.remoteVideoMenu.disableKick=true'` , it shows an error `I/flutter ( 4037): error: 'package:jitsi_meet/jitsi_meet.dart': Failed assertion: line 64 pos 13: 'constraint.checkConstraint(options.room)': Only alphanumeric, dash, and underscore chars allowed`


So how do I add this code at the end of the meeting url and use these https://github.com/jitsi/jitsi-meet/blob/master/config.js meeting options ?

**Comment by jimmyjose-dev** [comment]
I just realized, feature flags code has been merged but the package hasn't been released for pubspec yet. 
You would have to download the code from Github and try.

**Comment by jimmyjose-dev** [comment]
> Moved that reply from #159 to #160
> 
> @Snapworks i did find a solution on the main Jitsi developer forum, https://community.jitsi.org/t/how-to-how-to-customize-meeting-options/74665 but that can be done by adding `#config.prejoinPageEnabled=true&config.remoteVideoMenu.disableKick=true` code like this at the end of the meeting url, but the issue is how do I add this at the end of the meeting url? If we add this thing in the dart file,(in the variable options) `..room = 'example#config.prejoinPageEnabled=true&config.remoteVideoMenu.disableKick=true'` , it shows an error `I/flutter ( 4037): error: 'package:jitsi_meet/jitsi_meet.dart': Failed assertion: line 64 pos 13: 'constraint.checkConstraint(options.room)': Only alphanumeric, dash, and underscore chars allowed`
> 
> So how do I add this code at the end of the meeting url and use these https://github.com/jitsi/jitsi-meet/blob/master/config.js meeting options ?

https://github.com/gunschu/jitsi_meet/issues/160#issuecomment-735216195

**Comment by jimmyjose-dev** [comment]
https://github.com/gunschu/jitsi_meet/issues/159#issuecomment-735355004

**Comment by chandrabezzo** [comment]
This need change code in React Native, because jitsi built using react native. We must add optional variable to show / hide options meeting.
