### ISSUE TITLE
Is whiteboard available inside meeting in Jitsi Meet?

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#161]
Can we have whiteboard like we got screen sharing?

**Comment by jimmyjose-dev** [comment]
Currently whiteboard like feature is available through another plugin integration such as Etherpad and Etherdraw, meet.jitsi server doesn't have this enabled by default and is only available through custom hosting.

When you enable Etherpad/Etherdraw you will see something like this...settings are picked from server config and no change is required in the flutter package.

<img src = "https://dl.dropboxusercontent.com/s/mgv9h9yxasurf6b/etherpad.jpg"/>

**Comment by jagadish-pattanaik** [comment]
How to enable that? Please share the steps and required links and will screen sharing be still there after adding whiteboard? Will it harm in any way?

**Comment by jimmyjose-dev** [comment]
It involves buying a server and deploying Jitsi on it, so it is beyond the scope of this repo, the main Jitsi repo and developer forum would be more apt place for this. 
You might face some error during this phase of development and your queries can be addressed by multiple people at a faster rate over there. 


Yes, screen sharing and whiteboard can coexist.

**Comment by jagadish-pattanaik** [comment]
Thank you! I will try...if any further update about whiteboard then please reopen this one.

**Comment by jimmyjose-dev** [comment]
Sure brother
