### ISSUE TITLE
reduce apk size

### ISSUE THREAD

**Issue by pishguy** [gunschu/jitsi_meet#162]
when i build release sample code in this repository apk size is over than 100MB

how can i reduce size of apk?

**Comment by jimmyjose-dev** [comment]
**First step is, stop using apk**

Maybe these will help but YMMW

Apk are zip files.. extract it and go to lib folder... remove the arch you dont support, for ex: armeabi-v7a, after changes zip it back and rename with .apk

Gradle settings: (search for)
1) Minifyenabled
2) Shrink resources
3) Progaurd settings
4) enableR8

**Comment by sernocturno** [comment]
the best way to reduce apk size is build the app as appbundle [check this](https://developer.android.com/topic/performance/reduce-apk-size)
