### ISSUE TITLE
Jitsi crashes when using a JWT token; works without any issues otherwise

### ISSUE THREAD

**Issue by manjukiranp** [gunschu/jitsi_meet#163]
Platform: Android
Device Physical or Simulator: Simulator
Device Model: Pixel 2
Device OS Version: API 28

Flutter Doctor: run flutter doctor and paste results below:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-IN)

    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.51.1)
[√] Connected device (1 available)
! Doctor found issues in 1 category.

Steps to recreate: detailed step by step on how to recreate below:
1. Setup a custom jitsi server with authentication set to token.
2. With the example provided, connect to the server using a JWT token.

Got:
Jitsi video screen open buts immediately results ni a 'Something went wrong..Trying to reconnect'. It doesn't wait for any user input. It termiantes right after and returns.
Tried changing the server to 'anonymous' auth and connecting without token, it works perfectly fine.

Error logs:
JitsiMeetSDK(29445): [modules/xmpp/xmpp.js] JID a4d3409f-a628-400c-b973-02531e785d47@meet.schoolelement.in/hifPfvew using MUC nickname a4d3409f
I/JitsiMeetSDK(29445): [modules/xmpp/ChatRoom.js] Joined MUC as pncc-wa9hdd0lh4-394@conference.meet.schoolelement.in/a4d3409f
I/JitsiMeetSDK(29445): [modules/e2eping/e2eping.js] Initializing e2e ping; pingInterval=10000, analyticsInterval=60000.
I/JitsiMeetSDK(29445): [modules/connectivity/ParticipantConnectionStatus.js] RtcMuteTimeout set to: 10000
W/JitsiMeetSDK(29445): [JitsiConference.js] No VAD Processor was provided. Noisy microphone detection service was not initialized!
I/JitsiMeetSDK(29445): [modules/statistics/AvgRTPStatsReporter.js] Avg RTP stats will be calculated every 15 samples
I/JitsiMeetSDK(29445): [JitsiConference.js] backToP2PDelay: 5
D/JitsiMeetSDK(29445): [modules/videosipgw/VideoSIPGW.js] creating VideoSIPGW
I/JitsiMeetSDK(29445): [JitsiConference.js] _doReplaceTrack - no JVB JingleSession
I/JitsiMeetSDK(29445): [JitsiConference.js] _doReplaceTrack - no P2P JingleSession
I/JitsiMeetSDK(29445): [JitsiConference.js] _doReplaceTrack - no JVB JingleSession
I/JitsiMeetSDK(29445): [JitsiConference.js] _doReplaceTrack - no P2P JingleSession
D/JitsiMeetSDK(29445): [features/base/lastn] There is no active conference, not updating last N
I/JitsiMeetSDK(29445): [modules/xmpp/moderator.js] Focus jid set to:  undefined
I/JitsiMeetSDK(29445): [modules/xmpp/moderator.js] Session ID: null machine UID: 650ebf5f5dd2bbff85c3f6bf27852369
I/JitsiMeetSDK(29445): [features/base/redux] redux state persisted. 8ae5cd0689b3668b13557a4960f8583e -> 5e5075d711ded037cc1fc8914bc9c731
D/EGL_emulation(29445): eglMakeCurrent: 0xe4605720: ver 2 0 (tinfo 0xcbb03270)
D/EGL_emulation(29445): eglMakeCurrent: 0xe4605720: ver 2 0 (tinfo 0xcbb03270)
I/JitsiMeetSDK(29445): [modules/xmpp/moderator.js] Focus jid set to:  focus@auth.meet.schoolelement.in
I/JitsiMeetSDK(29445): [modules/xmpp/moderator.js] Authentication enabled: false
I/JitsiMeetSDK(29445): [modules/xmpp/moderator.js] External authentication enabled: false
I/org.webrtc.Logging(29445): SurfaceEglRenderer: : surfaceChanged: format: 4 size: 1074x1914
I/org.webrtc.Logging(29445): EglRenderer: setLayoutAspectRatio: 0.5611285
I/JitsiMeetSDK(29445): [modules/xmpp/moderator.js] Sip gateway enabled:  false
W/JitsiMeetSDK(29445): [modules/xmpp/ChatRoom.js] onPresError  { _nsMap: { '': 'jabber:client' },
:
I/JitsiMeetSDK(29445):     deviceId: 'audio-1' } ]
D/JitsiMeetSDK(29445): [modules/RTC/RTCUtils.js] Available devices:  [ { kind: 'videoinput',
D/JitsiMeetSDK(29445):     label: '0',
D/JitsiMeetSDK(29445):     groupId: '',
D/JitsiMeetSDK(29445):     deviceId: '0',
D/JitsiMeetSDK(29445):     facing: 'environment' },
D/JitsiMeetSDK(29445):   { kind: 'videoinput',
D/JitsiMeetSDK(29445):     label: '1',
D/JitsiMeetSDK(29445):     groupId: '',
D/JitsiMeetSDK(29445):     deviceId: '1',
D/JitsiMeetSDK(29445):     facing: 'front' },
D/JitsiMeetSDK(29445):   { kind: 'audioinput',
D/JitsiMeetSDK(29445):     label: 'Audio',
D/JitsiMeetSDK(29445):     groupId: '',
D/JitsiMeetSDK(29445):     deviceId: 'audio-1' } ]
I/JitsiMeetSDK(29445): [features/base/conference] JitsiConference.leave() rejected with: Error(Error){"message":"The timeout for the confirmation about leaving the room expired."}

**Comment by jimmyjose-dev** [comment]
are you able to access meet.schoolelement.in in the browser with JWT token ?

**Comment by manjukiranp** [comment]
I should have updated the bug. My token generation logic had a flaw. Fixing
the flaw made it work.

However, giving an invalid token shouldn't crash Jitsi. Please look into
that.

Thanks and Regards,
-Manjukiran

**Comment by jimmyjose-dev** [comment]
Sure, will run a test. Thanks for the update... closing this issue now.
