### ISSUE TITLE
How to secure conference room to avoid unknown persons ?

### ISSUE THREAD

**Issue by maheshperi19** [gunschu/jitsi_meet#164]
Hi,

I have created room name dynamically. Currently i am connecting to only one person. But after joining the call, so many unknown persons are joining in my call. How to avoid unknown persons and how to secure my room and call ?

Please give me suggestions for this.

**Comment by jimmyjose-dev** [comment]
There are couple of ways to approach this situation,
If using default jitsi server:
1) Generate a room name that is long and is preferably not a dictionary word... think of like choosing a password.
or
2) Create room name as before and after meeting has started, from the settings choose the option Add Password , every user who tries to enter will have to enter this password

If you have your own server
1) Enable Username/Password at prosody level
or
2) Enable JWT
or
3) Use the steps mentioned above (default jitsi server)

**Comment by maheshperi19** [comment]
Okay. I dont want password enabled for this. So i can look into long room name as you suggested in point no 1. Thank you.
