### ISSUE TITLE
Show number of participants in the meeting on the meeting screen.

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#165]
How to know how many participants are there in the meeting while in the meeting. Is there anything which shows number of participants?

**Comment by jimmyjose-dev** [comment]
Call stats info is available only on the web when more than two person are in the room.
In the app you may use the delegate method `onConferenceJoined` to add and `onConferenceTerminated` to remove count on your server

**Comment by jagadish-pattanaik** [comment]
Yeah but where will I show in the meeting even if I have the number of participants...there is no text widget for showing number of participants on meeting screen

**Comment by jimmyjose-dev** [comment]
Correct, there is no inbuilt widget currently supporting this, I didn't realize you want to display it on the screen as well.

This is beyond the scope of this repository .... but here is something that will get you started... 

<img src="https://dl.dropboxusercontent.com/s/ndnhkuhlrz3lb7c/custom_text.jpg" />
Look into my code for close meeting #73 and you can update the label in the same way.

**Please note our future version release might erase your changes.**

**Comment by jagadish-pattanaik** [comment]
Thanks I will try it but are there any possibility that in future jitsi SDK will have option to show participants number?

**Comment by jimmyjose-dev** [comment]
Yes, a PR was submitted for a similar feature couple of months back... it has not been merged though.... if the request for this feature increases they might merge the code and release it soon.

**Comment by jagadish-pattanaik** [comment]
Yeah please merge it soon and see if whiteboard and custom help link can also be added. And yes if possible see if background colour can be change to complete black it will look better than the present deep blue gradient color background.

**Comment by jimmyjose-dev** [comment]
That depends on the Jitsi team, we dont have any control over it.

**Comment by jagadish-pattanaik** [comment]
Yeah I know, but anything you can do to make it faster or make them know or throw some light on the topic to highlight it then please do...

**Comment by jimmyjose-dev** [comment]
I wish i could but thats not how it works 🙂.... 

please close this issue... if there are no further questions...

**Comment by jagadish-pattanaik** [comment]
Okay
