### ISSUE TITLE
Can't see any close captioning or subtitles option in the menu even if it is enabled (default)

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#167]
I can't see any subtitles option in the menu

![Screenshot_2020-12-02-16-23-08-963](https://user-images.githubusercontent.com/74181131/100863556-baf34a80-34ba-11eb-8423-8a7cb487a086.jpeg)

**Comment by jimmyjose-dev** [comment]
Close captioning in jitsi needs Jigasi transcribing option set to true.. and is not available on their default server.

**Comment by jagadish-pattanaik** [comment]
Ok thank you...I am closing this issue here if any updates then please reopen this one.
