### ISSUE TITLE
How to make a Jitsi meet like website with same functions and custom ui or migrating my app to flutter web

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#168]
I want a website for my app which is similar to Jitsi meet and has all the same functions and as well as default server but I don't want the watermark and change the ui. If not possible then how to migrate my app to flutter web?

**Comment by jimmyjose-dev** [comment]
To integrate in your website -> https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe
To make custom UI for web.. look into self hosting
Jitsi Flutter web support. #66

**Comment by jagadish-pattanaik** [comment]
After integration into website does it will recieve meeting links like the official website does as meet.jit.si/id and id is set as the meeting id. Will it work the same on Integra also. As I want all the same things as in official website but just want to remove the jitsi watermark.

**Comment by jimmyjose-dev** [comment]
receiving meeting links ?
For customizing jitsi, it would be better if to direct your queries over to the main jitsi repo/forum.

**Comment by jagadish-pattanaik** [comment]
Ok thanks..share the link please of the forum or repo

**Comment by jimmyjose-dev** [comment]
google jitsi forum

please close this issue... if there are no further questions...

**Comment by jagadish-pattanaik** [comment]
Thank you
