### ISSUE TITLE
Undefined symbols for architecture armv7. Error while running physical IOS devices

### ISSUE THREAD

**Issue by gurungsuraaj** [gunschu/jitsi_meet#17]
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    ld: warning: ignoring file /Users/navrajsharma/Desktop/my_project_name/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet, missing
    required architecture armv7 in file /Users/navrajsharma/Desktop/my_project_name/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet (2
    slices)
    ld: warning: ignoring file /Users/navrajsharma/Desktop/my_project_name/build/ios/Debug-iphoneos/jitsi_meet/jitsi_meet.framework/jitsi_meet, building
    for iOS-armv7 but attempting to link with file built for iOS-arm64
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_JitsiMeetPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

**Comment by buzzwin** [comment]
What Xcode version are you using ?... we have issues compiling  in 11.4.


Sent from Yahoo Mail for iPhone


On Tuesday, April 14, 2020, 1:29 AM, gurungsuraaj <notifications@github.com> wrote:




Error output from Xcode build:
↳
** BUILD FAILED **

Xcode's output:
↳
ld: warning: ignoring file /Users/navrajsharma/Desktop/my_project_name/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet, missing
required architecture armv7 in file /Users/navrajsharma/Desktop/my_project_name/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet (2
slices)
ld: warning: ignoring file /Users/navrajsharma/Desktop/my_project_name/build/ios/Debug-iphoneos/jitsi_meet/jitsi_meet.framework/jitsi_meet, building
for iOS-armv7 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture armv7:
"OBJC_CLASS$_JitsiMeetPlugin", referenced from:
objc-class-ref in GeneratedPluginRegistrant.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using new build system
note: Planning build
note: Constructing build description

Could not build the precompiled application for the device.

**Comment by gurungsuraaj** [comment]
Thanks for the response. Yes the problem was with the xcode version 11.4 so I downgraded to 11.3.1
