### ISSUE TITLE
App crashing many times with "JitsiMeet.closeMeeting()" - FATAL EXCEPTION - Shutting down VM

### ISSUE THREAD

**Issue by maheshperi19** [gunschu/jitsi_meet#170]
App crashing many times when calling "JitsiMeet.closeMeeting()"

#144 Same issue for me also. But it is happening frequently 1 out 3 or 4 times .

Here is the complete logs :  

D/AndroidRuntime(20373): Shutting down VM
E/AndroidRuntime(20373): FATAL EXCEPTION: main
W/JitsiMeetSDK(16474): [features/base/sounds] _REMOVE_AUDIO_ELEMENT: no sound for id: INCOMING_MSG_SOUND
E/AndroidRuntime(16474): FATAL EXCEPTION: main
E/AndroidRuntime(16474): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(16474): 	at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:139)
E/AndroidRuntime(16474): 	at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35)
E/AndroidRuntime(16474): 	at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114)
E/AndroidRuntime(16474): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(16474): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16474): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(16474): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(16474): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16474): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(16474): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(16474): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(16474): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16474): 	at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135)
E/AndroidRuntime(16474): 	... 9 more
E/AndroidRuntime(16474): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jitsi.meet.sdk.JitsiMeetView org.jitsi.meet.sdk.JitsiMeetFragment.getJitsiView()' on a null object reference
E/AndroidRuntime(16474): 	at org.jitsi.meet.sdk.JitsiMeetActivity.getJitsiView(JitsiMeetActivity.java:110)
E/AndroidRuntime(16474): 	at org.jitsi.meet.sdk.JitsiMeetActivity.leave(JitsiMeetActivity.java:126)
E/AndroidRuntime(16474): 	at org.jitsi.meet.sdk.JitsiMeetActivity.finish(JitsiMeetActivity.java:99)
E/AndroidRuntime(16474): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onConferenceTerminated(JitsiMeetActivity.java:223)
E/AndroidRuntime(16474): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onConferenceTerminated(JitsiMeetPluginActivity.kt:88)
E/AndroidRuntime(16474): 	... 11 more
E/JitsiMeetSDK(16474): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK(16474): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:139)
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35)
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114)
E/JitsiMeetSDK(16474): 	at android.os.Handler.handleCallback(Handler.java:938)
E/JitsiMeetSDK(16474): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/JitsiMeetSDK(16474): 	at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK(16474): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/JitsiMeetSDK(16474): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(16474): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(16474): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(16474): Caused by: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK(16474): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135)
E/JitsiMeetSDK(16474): 	... 9 more
E/JitsiMeetSDK(16474): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jitsi.meet.sdk.JitsiMeetView org.jitsi.meet.sdk.JitsiMeetFragment.getJitsiView()' on a null object reference
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.JitsiMeetActivity.getJitsiView(JitsiMeetActivity.java:110)
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.JitsiMeetActivity.leave(JitsiMeetActivity.java:126)
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.JitsiMeetActivity.finish(JitsiMeetActivity.java:99)
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onConferenceTerminated(JitsiMeetActivity.java:223)
E/JitsiMeetSDK(16474): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onConferenceTerminated(JitsiMeetPluginActivity.kt:88)
E/JitsiMeetSDK(16474): 	... 11 more
E/JitsiMeetSDK(16474):
E/JitsiMeetSDK(16474): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:139)
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35)
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114)
E/JitsiMeetSDK(16474): 	at android.os.Handler.handleCallback(Handler.java:938)
E/JitsiMeetSDK(16474): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/JitsiMeetSDK(16474): 	at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK(16474): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/JitsiMeetSDK(16474): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(16474): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(16474): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(16474): Caused by: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK(16474): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135)
E/JitsiMeetSDK(16474): 	... 9 more
E/JitsiMeetSDK(16474): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jitsi.meet.sdk.JitsiMeetView org.jitsi.meet.sdk.JitsiMeetFragment.getJitsiView()' on a null object reference
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.JitsiMeetActivity.getJitsiView(JitsiMeetActivity.java:110)
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.JitsiMeetActivity.leave(JitsiMeetActivity.java:126)
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.JitsiMeetActivity.finish(JitsiMeetActivity.java:99)
E/JitsiMeetSDK(16474): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onConferenceTerminated(JitsiMeetActivity.java:223)
E/JitsiMeetSDK(16474): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onConferenceTerminated(JitsiMeetPluginActivity.kt:88)
E/JitsiMeetSDK(16474): 	... 11 more
V/MediaPlayer(16474): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(16474): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(16474): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(16474): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/JitsiMeetSDK(16474): [features/base/sounds] _REMOVE_AUDIO_ELEMENT: no sound for id: LIVE_STREAMING_OFF_SOUND
I/org.webrtc.Logging(16474): NetworkMonitor: Stop monitoring with native observer -382682544
I/org.webrtc.Logging(16474): NetworkMonitorAutoDetect: Unregister network callback
I/JitsiMeetSDK(16474): [features/base/redux] redux state persisted. 9a0acd44b31e78bfadefc5cd0fe8f755 -> 220722bcbfa59b049d230ab0b5ff8ddc
V/MediaPlayer(16474): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(16474): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(16474): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(16474): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/JitsiMeetSDK(16474): [features/base/sounds] _REMOVE_AUDIO_ELEMENT: no sound for id: LIVE_STREAMING_ON_SOUND
I/Process (16474): Sending signal. PID: 16474 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by jimmyjose-dev** [comment]
#144 duplicate...

It is advisable to update your finding in the issue if it already exists, and if its closed you may reopen them.

As for the solution for this issue, we have already commented in #144.
