### ISSUE TITLE
Issue using jitsi_meet with stripe_payment

### ISSUE THREAD

**Issue by NifalNizar** [gunschu/jitsi_meet#171]
I have already using **stripe_payment: ^1.0.9**
When I try to use **jitsi_meet: ^2.0.0** getting following issue.

Type com.facebook.react.bridge.ReactMethod is defined multiple times

R8: Program type already present: com.facebook.react.bridge.ActivityEventListener
                                                                        
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithR8ForRelease'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 38s

**Comment by NifalNizar** [comment]
Type com.facebook.react.bridge.ReactMethod is defined multiple times

**Comment by mnomanmemon** [comment]
Hi @NifalNizar, facing the same issue. Any update? or have you come up with any alternative solution?

**Comment by tuantvu** [comment]
Haven't tried this out, but we use Stripe for another app and am using stripe_sdk with no problems. I'm guessing since both jitsi and stripe_payment use ReactNative, it' may not play nice together.

**Comment by NifalNizar** [comment]
@mnomanmemon I have changed the plugins from **stripe_payment** to **stripe_sdk**
Now everything works fine.

  jitsi_meet: ^2.0.0
  stripe_sdk: ^4.0.2

**Comment by subhra9326** [comment]
again stripe and Jitsi meet not working together with the latest version
my version is
flutter_stripe: ^1.0.2
  jitsi_meet: ^4.0.0
, can anyone please tell me the reason why it's happening and what is the solution for that.

**Comment by ektapadaliya** [comment]
@subhra9326 
Did you solve issue ?

**Comment by denes16** [comment]
Same for me anyone found a solution?
