### ISSUE TITLE
Picture in Picture not working in IOS but working in Android 

### ISSUE THREAD

**Issue by Amansingla97** [gunschu/jitsi_meet#173]
In IOS : 
![IMG_5327](https://user-images.githubusercontent.com/20012612/101844117-b3ded300-3b71-11eb-94d4-17284501f6be.PNG)
Whenever PIP is enabled, video goes into pip mode but the background is always black.

**Comment by jimmyjose-dev** [comment]
#120 the thread

or specific comment https://github.com/gunschu/jitsi_meet/issues/120#issuecomment-704934715

**Comment by tuantvu** [comment]
Closing due to OS working as designed.

**Comment by nsumithradeveloper** [comment]
> In IOS :
> ![IMG_5327](https://user-images.githubusercontent.com/20012612/101844117-b3ded300-3b71-11eb-94d4-17284501f6be.PNG)
> Whenever PIP is enabled, video goes into pip mode but the background is always black.

Does this happened in phone or in simulator

**Comment by aartiaparekh** [comment]
@Amansingla97 You got any solution? I am also stuck in same flow in ios.

**Comment by jimmyjose-dev** [comment]
#218
