### ISSUE TITLE
How to change settings for jitsi meet website

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#174]
I had set settings in my app like participants are not given kick out feature but in Jitsi meet web participants can kick out and accept people in lobby. How to change the settings?

**Comment by jagadish-pattanaik** [comment]
For example meet.jit.si/12345678900 is the meeting link can we have settings data in it? Like meet.jit.si/12345678900/record=false or something like that. Or is there any way to change settings in the meeting on pc in the website?

**Comment by steveny909** [comment]
Hi @jagadish-pattanaik, I'm interested in this as well.   How to match jitsi web settings to match jitsi_meet flutter settings?

**Comment by jagadish-pattanaik** [comment]
I still cant get it now to do so, but I asked in Jitsi repo they said jitsi web doesn't has any settings

**Comment by tuantvu** [comment]
This sounds like a jitsi web + how you design your website problem, which this plugin doesn't support yet.
