### ISSUE TITLE
Prevent users from accepting lobby requests

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#176]
How to **prevent users to accept or deny lobby requests**. Or not even show the options at the top of the screen.

**Comment by jagadish-pattanaik** [comment]
Can it be added to feature flags? so that it can be disabled and enabled when needed like other features.

**Comment by tuantvu** [comment]
@jagadish-pattanaik Please be aware this plugin is mostly calling the underlying Android and iOS SDK to enable functionality. If those SDK do not have the functionality, this plugin will not also. We'll research if the SDKs do, but if you notice something that they support but this plugin doesn't, please link so your requests is done faster. Thanks
