### ISSUE TITLE
[FEATURE]: Add mute unmute to feature flags

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#177]
**add mute, unmute and mute everyone except options to features flag** so that it can be disabled and enabled according to need like other options in feature flags.

**Comment by tuantvu** [comment]
@jagadish-pattanaik Could you provide link to where this is supported in the official ios and android sdks? That would help us implement this faster.

**Comment by tuantvu** [comment]
@jagadish-pattanaik These are not feature flags as far as I can find. Mute everyone already exists in the option menu. Mute and Unmute programmatically, are new actions exposed by the API, not feature flags. I've added a new issue #233 to add this action. Closing this.
