### ISSUE TITLE
Custom layout

### ISSUE THREAD

**Issue by marcoberetta96** [gunschu/jitsi_meet#178]
I read that customizing the layout is currently not possible.
Is it on roadmap to have the possibility to bring the own layout (colors, widget positions, ...) ?

**Comment by jagadish-pattanaik** [comment]
Yeah I am also looking upto that...as I also want to change the background colour to black and many other things.

**Comment by IggyBlob** [comment]
I'm interested in that, too. More specifically, I'm trying to restrain Jitsi to a certain area of the screen such that parts of the host app are still visible. Is there any way to achieve this?

**Comment by tuantvu** [comment]
I think there were attempts to make this a platformview, but not sure how successful it's been. Maybe check some of the forks of this project?

**Comment by tuantvu** [comment]
making this duplicate of #79
