### ISSUE TITLE
Access chat from app

### ISSUE THREAD

**Issue by steveny909** [gunschu/jitsi_meet#179]
Hi, just discovered jitsi meet and loving it.   Wondering if there have been discussions on allowing chat to be accessible from the parent app.  Would be good if you can send or receive same chat as in jitsi meeting from flutter app used to call jitsi meet.

**Comment by tuantvu** [comment]
That's an interesting idea. As far as I know, I didn't see any APIs in the mobile SDKs to send or receive chat messages out of the meeting though. This probably needs an upgrade to the mobile SDKs owned by Jitsi meet team. Please correct me if this functionality exists now.

**Comment by tuantvu** [comment]
@steveny909 Please search or ask on https://community.jitsi.org/. If Jitsi provides this functionality, file a new feature request to us and we'll incorporate it.
