### ISSUE TITLE
Update minSDK to 21

### ISSUE THREAD

**Issue by blizzy312** [gunschu/jitsi_meet#18]
Hi, I've searched around and [found](https://community.jitsi.org/t/jitsi-meet-android-sdk-level-api-21/21496) that there's a solution to decrease min sdk version to 21. This implementation will have a really good impact, as phones on Android 5 and 6 are still widely used. 
P.s. really great plugin, thanks for your work!

**Comment by Lucas15andrade** [comment]
Hello, did you manage to update the minSDK to 21?

**Comment by TBG-FR** [comment]
Hello,

I think you can check that commit, it seems like someone did it : https://github.com/EdwinRomelta/jitsi_meet/commit/e12036531baa1cbd598e1fdd9766e937b054ea45
