### ISSUE TITLE
compileOptions for Java 1.8 aren't used in the example

### ISSUE THREAD

**Issue by nilsreichardt** [gunschu/jitsi_meet#180]
The [README.me](https://github.com/gunschu/jitsi_meet/blob/master/example/README.md) says that you should add compileOptions for Java 1.8. But the [example](https://github.com/gunschu/jitsi_meet/tree/master/example) doesn't added it.

From [README.me](https://github.com/gunschu/jitsi_meet/blob/master/example/README.md):
> Add Java 1.8 compatibility support to your project by adding the following lines into your build.gradle file:
> 
> ```groovy
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_1_8
> }
> ```

`build.gradle` of [example](https://github.com/gunschu/jitsi_meet/tree/master/example): https://github.com/gunschu/jitsi_meet/blob/master/example/android/build.gradle
`app/build.gradle` of [example](https://github.com/gunschu/jitsi_meet/tree/master/example): https://github.com/gunschu/jitsi_meet/blob/master/example/android/app/build.gradle

But the  [example](https://github.com/gunschu/jitsi_meet/tree/master/example) still runs. Is this setup step still necessary?

**Comment by tuantvu** [comment]
Good call. I think it changed when we went to Kotlin. Assigning to myself to update the documentation

**Comment by tuantvu** [comment]
Updated in null-safety branch, will release when that gets merged.
