### ISSUE TITLE
Jitsi meet bit code enable issue

### ISSUE THREAD

**Issue by mohamedshafeer** [gunschu/jitsi_meet#181]
Showing Recent Messages
'/Users/Shafeer/IdeaProjects/customer/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/Shafeer/IdeaProjects/customer/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' for architecture arm64

**Comment by tuantvu** [comment]
Please provide more info on how to reproduce as described in the readme https://github.com/gunschu/jitsi_meet#issues

**Comment by RohithKilaparthi** [comment]
@tuantvu , I face a similar issue. In am performing a build with ENABLE_BITCODE as 'YES' due to my requirements (of other plug-ins). When I perform a build, the build fails with saying the same error.

```
'/Users/rohithkilaparthi/Documents/Projects/flutter/classgrad-mobile-app/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' does not
    contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode
    for this target. file
    '/Users/rohithkilaparthi/Documents/Projects/flutter/classgrad-mobile-app/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' for
    architecture arm64
```

**Comment by tuantvu** [comment]
@RohithKilaparthi It is documented on official Jitsi's iOS handbook to set bitcode to NO, so I don't know how to get around it. https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk. Ask the question on community.jitsi.org and open up a feature request if you find a solution.
