### ISSUE TITLE
Deeplinking issue in iOS

### ISSUE THREAD

**Issue by tusharsonawanes** [gunschu/jitsi_meet#182]
Hello, how to enable deeplinks in iOS version of the same ?

**Comment by tuantvu** [comment]
@tusharsonawanes I'm unable to understand what it is you are needing.

**Comment by tuantvu** [comment]
duplicate of #184

**Comment by tusharsonawanes** [comment]
> @tusharsonawanes I'm unable to understand what it is you are needing.

@tuantvu what I want is, when the use clicks on the meeting link, the "app" should be opened. Got it ?
