### ISSUE TITLE
Deeplinking for mobile applications

### ISSUE THREAD

**Issue by tusharsonawanes** [gunschu/jitsi_meet#184]
Hello, I have an issue configuring deeplinking for android and iOS phones. I'll explain my entire scenario here.

Backend - docker-jitsi-meet-5142

Reference jitsi repository for android and iOS apps - https://github.com/gunschu/jitsi_meet

Issues.

**Android** ( 1 Issue )

**1.** When the user does **not** have the custom application ( made by using the above repository )  installed in the phone, on click of the link, it ( as expected ) opens the web where three options are prompted, '

- Join this meeting using the app
- Download the app
- Launch in web

The first two options, redirect to custom android application which is present android play store and the third options opens the web browser. This works perfectly well. The **issue** is, when the user installs the application, and then clicks the link, I can see the application listed in the **open with** section, but if I click on any mobile browser ( chrome or mozilla ), I am again prompted the above three options. When I click on the first option **- Join this meeting using the app**, **it again redirects to play store** whereas the **expected** behavior is, it should open the app installed in the phone. Is it a configuration issue in the app or **interface_config.js** file ?

**iOS** ( 2 issues )

**1.** From what I have read in the community page, I need to place the apple-app-association file in .well-known directory. Where exactly am I supposed to place this file  in my docker based backend ?

**2.** How to configure deeplinking for iOS ? The method that I am following is, mentioning URL Types in XCode. Is this the right way to configure deeplinking completely for iOS ?

Please let me know if you need any more information.

**Comment by tuantvu** [comment]
https://www.google.com/search?q=deeplinking+for+ios&sxsrf=ALeKk00lTIMkrWXCvivWlNLtycgBd77KSA%3A1617491833783&source=hp&ei=efdoYKukLaXO0PEPw5WPaA&iflsig=AINFCbYAAAAAYGkFicQ1hEk1iywHoasXa1fYG4NdgjKt&oq=deeplinking+for+ios&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHlChAlihAmCvBGgAcAB4AIABjgGIAY4BkgEDMC4xmAEAoAECoAEBqgEHZ3dzLXdpeg&sclient=gws-wiz&ved=0ahUKEwjrxLXRmuPvAhUlJzQIHcPKAw0Q4dUDCAk&uact=5
