### ISSUE TITLE
Add muteEveryoneEnabled and controlLobbyModeEnabled  to feature flags

### ISSUE THREAD

**Issue by techno-school** [gunschu/jitsi_meet#185]
As a developer, I would like to prevent participants from muting every one, and from enabling or disabling lobby mode.

**Comment by tuantvu** [comment]
@techno-school I don't see this feature on the android sdk site: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk. Please provide where the official Jitsi android and iOS SDK supports this.

**Comment by tuantvu** [comment]
You may be referring to this bug: https://github.com/jitsi/jitsi-meet/issues/8464. If so, please keep an eye on it and file a new feature request when they fix it in the mobile SDK and we will upgrade the version.
