### ISSUE TITLE
Trying to use the plugin to connect to Jitsi installed 

### ISSUE THREAD

**Issue by naveenbabusa** [gunschu/jitsi_meet#186]
We are trying to build a flutter app and use Jitsi for video calls. We are using the plugin . But struggling as we are getting below issue

I/flutter (11912): error: MissingPluginException(No implementation found for method joinMeeting on channel jitsi_meet), type: MissingPluginException

Pls guide

**Comment by pNAIA** [comment]
Yes! Please assist.

**Comment by tuantvu** [comment]
I've seen plugin issues like this happen when I install a new package, but didn't completely stop and restart my running app in debug.  If you've done so, please add snippets of your code so we can help troubleshoot.

**Comment by asynchronizd** [comment]
This is happening for me also. Works on debug though.

**Comment by tuantvu** [comment]
Please try to close all simulators and IDE, open IDE, remove the jitsi_meet plugin from pubspec, flutter clean, flutter pub get, add the plugin, flutter pub get, run.

**Comment by asynchronizd** [comment]
Downgrade/upgrade the gradle to doc mentioned version, it'll work.
