### ISSUE TITLE
Flutter app crashing when enabling features.

### ISSUE THREAD

**Issue by wakeyhazey** [gunschu/jitsi_meet#188]
Hi, the runtime loses connection to device when I try to only enable one option from the example code given in pub.dev or enabling an option during a call.

**The output:**

flutter: JitsiMeetingOptions: JitsiMeetingOptions{room: plugintestroom, serverURL: null, subject: My Plugin Test Meeting, token: null, audioMuted: true, audioOnly: true, videoMuted: false, userDisplayName: Plugin Test User, userEmail: fake@email.com, userAvatarURL: null, featureFlags: {welcomepage.enabled: false, pip.enabled: false} }
flutter: Jitsi Meet - broadcast event: {event: onConferenceWillJoin, url: https://meet.jit.si/plugintestroom}
flutter: _onConferenceWillJoin broadcasted with message: {event: onConferenceWillJoin, url: https://meet.jit.si/plugintestroom}
flutter: plugintestroom will join with message: {event: onConferenceWillJoin, url: https://meet.jit.si/plugintestroom}
flutter: Jitsi Meet - broadcast event: {event: onConferenceJoined, url: https://meet.jit.si/plugintestroom}
flutter: _onConferenceJoined broadcasted with message: {event: onConferenceJoined, url: https://meet.jit.si/plugintestroom}
flutter: plugintestroom joined with message: {event: onConferenceJoined, url: https://meet.jit.si/plugintestroom}
Lost connection to device.

**Comment by tuantvu** [comment]
@wakeyhazey I was unable to reproduce on my android simulator. Is this consistent? please provide flutter doctor.
