### ISSUE TITLE
Screen sharing works only when 2 users in meeting

### ISSUE THREAD

**Issue by RaviGaruda** [gunschu/jitsi_meet#189]
I have implement Jitsi sdk on my own server and also runs on android ios application.

Screen sharing is working properly on my own server and in application works only there is 2 users in meeting; when 3rd or more user join screen sharing stop showing mobile screen.

**Comment by bhagat-opskube** [comment]
@RaviGaruda I am also facing this problem. Have you got any solution?

**Comment by RaviGaruda** [comment]
sadly not yet!!!

**Comment by tuantvu** [comment]
@RaviGaruda Have you tried building the official Jitsi Android or iOS app without this plugin and does screen sharing working with 3 or more people on the official version? We're on Android SDK version 3.2.0 with this plugin now, maybe the issue has been fixed (IOS SDK version is still behind).

**Comment by rizkitriandani** [comment]
yes I also facing this issue, I already done solution from this https://community.jitsi.org/t/screen-sharing-glitch/27972 which we have to add  `enableLipSync: false` on config.js but it seems doesn't have any effect.
