### ISSUE TITLE
Connect to not trusted HTTPS server

### ISSUE THREAD

**Issue by nguyenhoangphuc289** [gunschu/jitsi_meet#19]
I created my own server with HTTPS (not certificate yet). But when I join meeting, it throws **Network request failed** to load `https://myserver.com.vn/config.js?room=myroom`.

But everything work well when I use default server `https://meet.jit.si/`.

How can I resolve this issue? Thank you

**Comment by gnusagit** [comment]
same issue here..

**Comment by DenisMrGnusa** [comment]
Is there any solution for this issue?

**Comment by nguyenhoangphuc289** [comment]
I used https and created a certificate. It's working well now
