### ISSUE TITLE
How to use self build jitsi framework?

### ISSUE THREAD

**Issue by nareshkatta99** [gunschu/jitsi_meet#190]
I generated the framework with the help of Jitsi Documentation from [Official documentation](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#building-it-yourself)
I'm finding it hard to use them from this point.
I tried to copy them to jitsi_meet/ios folder but it is not being used.
Can someone help me to use them in the gunschu/jitsi_meet/ios folder, not the jitsi_meet/example/ios folder?

**Comment by tuantvu** [comment]
What are you trying to accomplish? Is this a question meant for the official Jitsi meet community rather than this plugin?

**Comment by nareshkatta99** [comment]
I'm an Android and Flutter developer.
I made few changes to the library in react-native side (had to learn how to do that) and I want to use my framework in flutter.
In Android it was easy, I went to gunschu/jitsi_meet/android/build.gradle and gave my local folder path.
But in iOS I don't know how to use the framework I created.
I want to use the framework I created in this flutter plugin.
I cloned this repo and did the changes I wanted to do for Android but I wasn't able to do that in iOS.

**Comment by kleeb** [comment]
@nareshkatta99 there are 2 ways - build the project and user the local repo path or build the project and push to the forked maven repo, which later on you need to modify in Podfile

I am building the iOS like that:

```
mkdir /Users/vagrant/tmp
cd /Users/vagrant/tmp
# use your custom repo and branch
git clone https://github.com/jitsi/jitsi-meet
cd jitsi-meet
npm i
node_modules/react-native-webrtc/tools/downloadBitcode.sh
cd ios
pod install
cd ..
mkdir ../jitsi-meet-ios-sdk-releases
mkdir ../jitsi-meet-ios-sdk-releases/Frameworks
# TODO generate ../jitsi-meet-ios-sdk-releases/JitsiMeetSDK.podspec.tpl

# build 
SDK_VERSION=3.0.0
ios/scripts/release-sdk.sh
cp -a /Users/vagrant/tmp/jitsi-meet/ios/sdk/out/JitsiMeetSDK.xcframework ../jitsi-meet-ios-sdk-releases/Frameworks/
```

and the release is in /Users/vagrant/tmp/jitsi-meet-ios-sdk-releases/

There is one trick - they modified the framework file naming, which hasn't been yet pushed to this repo. It's from 3.0.0 version.

**Comment by nareshkatta99** [comment]
@kleeb thank you for the tutorial, 
How to generate JitsiMeetSDK.podspec.tpl file?
And how to use the local path?
I mean where I have to mention path for local repo?
I really appreciate you help.

**Comment by nareshkatta99** [comment]
I found some help in how to use local pod.
Only thing that is missing for me is the .tlp file
Can you please help me how to generate that?
Can I download that from [kleeb/jitsi-meet-ios-sdk-releases](https://github.com/kleeb/jitsi-meet-ios-sdk-releases/blob/master/JitsiMeetSDK.podspec.tpl)?

**Comment by kleeb** [comment]
here you have it, just change whatever you need (version, name, etc) or just leave it like it is https://github.com/jitsi/jitsi-meet-ios-sdk-releases/blob/master/JitsiMeetSDK.podspec.tpl

**Comment by nareshkatta99** [comment]
How to use the local path in the plugin?

**Comment by kleeb** [comment]
```
  s.source           = { :path => '/Users/vagrant/tmp/jitsi-meet-ios-sdk-releases' }
```

**Comment by nareshkatta99** [comment]
Hi after generating custom pod repo as you mentioned, I'm getting some weird issue now.

```
cannot find type 'PiPViewCoordinator' in scope
        fileprivate var pipViewCoordinator: PiPViewCoordinator?
```

Any suggestions @kleeb @tuantvu
