### ISSUE TITLE
IOS build is failing with Xcode 12.3 and swift 5.3.2 

### ISSUE THREAD

**Issue by nathansdev** [gunschu/jitsi_meet#192]
`    6_64-apple-ios-simulator.swiftinterface:23:41: error: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'
        public static func == (a: JitsiMeet.PiPViewCoordinator.Position, b: JitsiMeet.PiPViewCoordinator.Position) -> Swift.Bool
                                  ~~~~~~~~~ ^
    JitsiMeet.JitsiMeet:1:12: note: 'JitsiMeet' declared here
    open class JitsiMeet : NSObject {`
    
    I am getting error like above in 10+ places in while run "flutter run".
    
    I tried flutter clean, flutter pub repair cache commands as well.
    
    Tried reinstalling pod file and ran the app. still the same issue.
    
    Is any one facing this issue?

**Comment by Zeehshan** [comment]
same on my side i am using xcode 11.5 and jitsi_meet 2.0.0, kindly can anyone help please

**Comment by Zeehshan** [comment]
Hi, i got solution.
    Solution is that just remove JitsiMeet. from every point and rebuild it without clean, same for iso release

**Comment by Joseph-Nathan** [comment]
please can you provided steps

**Comment by tuantvu** [comment]
Closing as we're unable to reproduce this after many tries.
