### ISSUE TITLE
bug with featureFlag.chatEnabled?

### ISSUE THREAD

**Issue by steveny909** [gunschu/jitsi_meet#193]
Unless I'm missing something, it looks like setting chatEnabled=false removes the chat button the main screen, but it still lets you private chat by long pressing someone's thumbnail and choosing 'private chat' from the menu.   Is there another feature flag that disables private chat that I'm missing?

**Comment by tuantvu** [comment]
@steveny909 Were you able to find anything out? This is a good question to ask on the official forum: https://community.jitsi.org/. Please reopen or open a feature request if you discover a feature we haven't implemented.
