### ISSUE TITLE
Auto reconnect if internet drops for few seconds

### ISSUE THREAD

**Issue by ghost** [gunschu/jitsi_meet#195]
Is it possible to reconnect to jitsi call if the internet drops and comes back in few seconds

**Comment by tuantvu** [comment]
@nsumithradeveloper Elaborate please. What happens to Jitsi when the internet drops? Does it close? Or just pauses and resumes? After describing that, you need to describe what you would like to happen.

**Comment by ghost** [comment]
Once internet drops, I could see an alert in the attached image and it closes in two seconds instead of rejoining automatically. If internet resumes, Can you check why the alert is being closed immediately after it pops up.

![78013773-a705b080-734f-11ea-9c9e-78660530ee99](https://user-images.githubusercontent.com/76251625/115545027-f43d2300-a2c0-11eb-8add-613ad99fe9e8.jpg)

**Comment by ghost** [comment]
Any information on this?
