### ISSUE TITLE
Request to add listener for AUDIO_MUTED_CHANGED 

### ISSUE THREAD

**Issue by rizkitriandani** [gunschu/jitsi_meet#196]
I would like to have listener for AUDIO_MUTED_CHANGED (from the android jitsi sdk) so that I can add something when audio is muted or unmuted.

thank you.

source : https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk

**Comment by tuantvu** [comment]
Rolling this issue into #231
