### ISSUE TITLE
[UPGRADE]: Migrate to null safety

### ISSUE THREAD

**Issue by nilsreichardt** [gunschu/jitsi_meet#197]
## Description
We should migrate this package to null safety.

## Resources
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

**Comment by nilsreichardt** [comment]
I created a PR: #217

**Comment by tuantvu** [comment]
@nilsreichardt Pre-release is out: https://pub.dev/packages/jitsi_meet/versions/4.0.0-nullsafety.0. I'm going to close your PR and will create another one to merge after some time with the pre-release
