### ISSUE TITLE
Error trying to compile proyect

### ISSUE THREAD

**Issue by alienriquebm** [gunschu/jitsi_meet#2]
I have this problem when I try to compile the project.
I already added the lines on the configuration to the AndroidManifest:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.jitsi"
    xmlns:tools="http://schemas.android.com/tools"
    >
    <application
        tools:replace="android:label"
        android:name="io.flutter.app.FlutterApplication"
        android:label="jitsi"
        android:icon="@mipmap/ic_launcher">
        .
        .
        .
```
![image](https://user-images.githubusercontent.com/5152002/78069474-2bfcc400-7368-11ea-9af5-4eb845ffb7c6.png)

Any help? I'm running this on Android Emulator API 24.

**Comment by alienriquebm** [comment]
Ok i got the solution, I put on `android\app\build.gradle` the `minSdkVersion` to `24`

I think it will a be a great idea to include this on the README. Thanks!

**Comment by tuantvu** [comment]
That's a good idea. We will add the note to be at minSDK 24 in the README.
