### ISSUE TITLE
Reduce video Quality

### ISSUE THREAD

**Issue by vinodlee** [gunschu/jitsi_meet#20]
How can I reduce video Quality using jitsi

**Comment by tuantvu** [comment]
@vinodlee Several issues on Jitsi mention the mobile SDK ignores resolution settings at the moment. This will need to wait for the official SDK to update. Workaround is to fork the official SDK and fix that then fork this project to point to your fixed mobile SDK for now.

**Comment by jimmyjose-dev** [comment]
https://github.com/jitsi/jitsi-meet/blob/027cc1be96ff613f2faa831e2fae6b39dc90fe0f/react/features/base/flags/constants.js#L95
