### ISSUE TITLE
iOS 14.4 Option Button popup soft keyboard, no way to dismiss it

### ISSUE THREAD

**Issue by dragon2934** [gunschu/jitsi_meet#200]
Hi, there:
I am using  flutter 1.26
Flutter 1.26.0-2.0.pre.144 • channel master • https://github.com/flutter/flutter.git
Framework • revision f08b1ae637 (6 weeks ago) • 2020-12-28 14:39:02 -0800
Engine • revision 892034dc6a
Tools • Dart 2.12.0 (build 2.12.0-179.0.dev)

jit meet version is 2.0.0

when I click Option Menu,
![WechatIMG25](https://user-images.githubusercontent.com/20196597/107127649-7eaae480-6885-11eb-94ae-73c69f0526ca.jpeg)

 it pops up the soft keyboard, and no way to dismiss it. 

![WechatIMG26](https://user-images.githubusercontent.com/20196597/107127648-7e124e00-6885-11eb-9715-32dd46c60002.jpeg)

please  give me a hand to fix it.

Thanks

**Comment by tuantvu** [comment]
@dragon2934 I am not able to reproduce.
