### ISSUE TITLE
Cannot join meeting in apk release version

### ISSUE THREAD

**Issue by rizkitriandani** [gunschu/jitsi_meet#203]
I build a custom conferencing app using this library, it works fine on apk debug but when I switch to apk release it won't join the meeting.

**Comment by asynchronizd** [comment]
Figured out what's happening?

**Comment by asynchronizd** [comment]
I fixed the issue by downgrading to documentation gradle versions.

**Comment by asynchronizd** [comment]
`dependencies {
    classpath 'com.android.tools.build:gradle:3.6.3' 
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
}`

`
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip 
`

`compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
 `

**Comment by tuantvu** [comment]
@holy-dev Hi, are you recommending we need to upgrade something?

**Comment by asynchronizd** [comment]
@tuantvu Yes, I guess so, because downgrading to the doc mentioned gradle worked.

**Comment by tuantvu** [comment]
@holy-dev interesting. What was your setting before downgrading?

**Comment by asynchronizd** [comment]
@tuantvu I don't remember. Could be latest one as the project is new.

**Comment by tuantvu** [comment]
Going to upgrade gradle and update the documentation: #246
