### ISSUE TITLE
[FEATURE]: Add feature flags for audioMute, videoMute and overflowMenu, control tile-view, notifications, toolbox, filmstrip

### ISSUE THREAD

**Issue by AbdouEsi** [gunschu/jitsi_meet#205]
New Feature Request

We hope you will add these features from jitsi SDK :

Add feature flags for audioMute, videoMute and overflowMenu
New feature flags to control tile-view, notifications, toolbox, filmstrip

And other new features from SDK 
https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md

thank's

**Comment by tuantvu** [comment]
@AbdouEsi  Made the title more specific. Request features individually instead of linking the entire Jitsi change log.

**Comment by tuantvu** [comment]
https://jitsi.github.io/handbook/docs/dev-guide/mobile-feature-flags

**Comment by tuantvu** [comment]
Rolling this up into #235
