### ISSUE TITLE
show an error when try to join a metting

### ISSUE THREAD

**Issue by hedraadel1** [gunschu/jitsi_meet#206]
java.lang.VerifyError: Verifier rejected class com.facebook.react.uimanager.DisplayMetricsHolder: com.facebook.react.bridge.WritableNativeMap com.facebook.react.uimanager.DisplayMetricsHolder.getDisplayMetricsNativeMap(double) failed to verify: com.facebook.react.bridge.WritableNativeMap com.facebook.react.uimanager.DisplayMetricsHolder.getDisplayMetricsNativeMap(double): [0x23] register v1 has type Reference: com.facebook.react.bridge.WritableNativeMap but expected Reference: com.facebook.react.bridge.ReadableMap (declaration of 'com.facebook.react.uimanager.DisplayMetricsHolder' appears in /data/app/com.mediacity.eclass-WE2SMZiZLqdAJSjuaggsVw==/base.apk!classes49.dex)

**Comment by asynchronizd** [comment]
looks like multidex issue

**Comment by tuantvu** [comment]
@hedraadel1 Try a clean and build or a fresh install? Clear android build folders? Is this still happening?

**Comment by shalini-kad** [comment]
I'm getting the same error, did you find a fix for it? @hedraadel1  The error only occurs when the flutter_stripe package is also installed.
