### ISSUE TITLE
Trying to join In the Jitsi App or Apk with client URL, App automatically stopped. Can anyone please suggest the solution for the issue

### ISSUE THREAD

**Issue by hema107** [gunschu/jitsi_meet#209]
Error while running the Jitsi  Apk : Unable to set wss://localhost:8443/colibri-ws/<no value>/c85fadb5d36bd332/ef7844e8?pwd=5jiq235203890fkmnie1t82rqe as default origin header

**Comment by tuantvu** [comment]
@hema107 This is pretty vague. Why are you hitting localhost? Are you hosting a Jitsi server? Have you tried building an Android app based on Jitsi's official SDK and does this url work with that? If not, this is not a plugin issue but a server or Jitsi Android SDK issue. https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk
