### ISSUE TITLE
How to remove chat & other options?

### ISSUE THREAD

**Issue by tech4lyf** [gunschu/jitsi_meet#21]
Hi I'm using flutter_jitsi_meet,
I need some help in setting up.
How to remove chat and other options in more options?
Please help me ASAP

@gunschu thanks in Advance.

**Comment by dhsont** [comment]
I also want to customize menu,
want to bring hand raise button on main screen, How to do that ?
@gunschu  thanks in Advance.

**Comment by TBG-FR** [comment]
You can use feature flags for that :
-  [List of available feature flags here](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js)
- See [this commit](https://github.com/dreampowder/jitsi_meet/commit/7f54218b916b300572825320cfa9c057adcabdef) to see where and how to add them (search 'FeatureFlag'), for both Android and iOS

Can then enable or disable options, like chat, pip, raise hand. Disabling an option will make its button(s) disappear

**Comment by cihanfiliz** [comment]
I also need to remove the chat, other optins icons and blank bar ont top which has app name.  How can I customize the chat screen in flutter?

**Comment by TBG-FR** [comment]
Using feature flags you can remove options, including the chat. For the top bar, you can check some forks of this plugin, I remember some people removed it.

The chat screen is made by the Jitsi Meet SDK, so you would have to modify the SDK and compile it yourself, before "plugging" this Flutter plugin on it (instead of the official SDK build), I think.

Personnally, I would disable the chat using feature flags and make a new custom chat in another screen in the app, probably.

**Comment by rwbr** [comment]
To remove the chat, use the feature flags. See pull request https://github.com/gunschu/jitsi_meet/pull/48

**Comment by cihanfiliz** [comment]
Thank you @rwbr done for chat section. Are there any similar solution for the other settings icon? (vertical three dot) I would like to remove completetly three dot icon which is located on the bottom-right and the title bar completely. I am looking the pull requests but I just see some disabled subfeatures of it.

**Comment by rwbr** [comment]
I don‘t know any solution for hiding the settings icon. Like @TBG-FR suggested you would need to modify the Jitsi SDK and compile it yourself.

The SDK has some internal options for the user interface. Compare https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js#L40

**Comment by jasbin** [comment]
set chatEnabled to false to remove chat and true to add chat
```
var options = JitsiMeetingOptions()
        ..room = roomText.text
        ..serverURL = serverUrl
        ..subject = subjectText.text
        ..userDisplayName = nameText.text
        ..userEmail = emailText.text
        ..iosAppBarRGBAColor = iosAppBarRGBAColor.text
        ..audioOnly = isAudioOnly
        ..audioMuted = isAudioMuted
        ..videoMuted = isVideoMuted
        ..chatEnabled = true;
```

**Comment by tuantvu** [comment]
Chat disabling can be done through feature flags now. For other options to be disabled, it needs and SDK update, so we won't be officially supporting that until the official SDK is updated.

**Comment by tuantvu** [comment]
Consolidating issues like this to #22

**Comment by ramsmart-inno** [comment]
> set chatEnabled to false to remove chat and true to add chat
> 
> ```
> var options = JitsiMeetingOptions()
>         ..room = roomText.text
>         ..serverURL = serverUrl
>         ..subject = subjectText.text
>         ..userDisplayName = nameText.text
>         ..userEmail = emailText.text
>         ..iosAppBarRGBAColor = iosAppBarRGBAColor.text
>         ..audioOnly = isAudioOnly
>         ..audioMuted = isAudioMuted
>         ..videoMuted = isVideoMuted
>         ..chatEnabled = true;
> ```

Is it working?
