### ISSUE TITLE
[Question] Making custom layout

### ISSUE THREAD

**Issue by rikusen0335** [gunschu/jitsi_meet#210]
I'm searching for a while to fork the project to create custom layout on conference view.
Could anybody tell me? Thanks.

**Comment by RajKavadia** [comment]
I am searching for the same If found let me me know..

**Comment by rikusen0335** [comment]
@RajKavadia I was searching about this for a while, but this lib, is using WebView for conference view, like there's jitsi web but implemented by React/ReactNative code .
So you may be able to make some PlatformView (I don't know about this in detail) like you have to write some Native code.

**Comment by rikusen0335** [comment]
tl;dr
Unfortunately, there's no official method to implement custom layout, so you have to implement the custom layout with Native (Swift, Kotlin etc?) code

**Comment by tuantvu** [comment]
@rikusen0335 @RajKavadia 

If you're some how able to put the Jitsi view into a PlatformView, then it will behave like other widgets in Flutter. We haven't had time to explore this yet, but maybe you will have more luck. https://flutter.dev/docs/development/platform-integration/platform-views.

See #79
