### ISSUE TITLE
[FEATURE]: Add HELP_BUTTON_ENABLED to feature_flag_enum.dart

### ISSUE THREAD

**Issue by premy** [gunschu/jitsi_meet#212]
Currently not available through FeatureFlagEnum. I'm not connecting to meet.jit.si but to Jaas (8x8.vc)

**Comment by tuantvu** [comment]
May depend on #230

**Comment by tuantvu** [comment]
@premy Could you link to the Jitsi doc where this feature is supported? Thanks

**Comment by tuantvu** [comment]
@premy Nvm, I found it.

**Comment by tuantvu** [comment]
Rolling this up into #235
