### ISSUE TITLE
Add support for muted events

### ISSUE THREAD

**Issue by mahdidham** [gunschu/jitsi_meet#215]
Hi, I would like to request to unlock muted events feature in both Android and iOS based from [jitsi-android](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#supported-events) and[ jitsi-ios](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#audiomutedchanged) documentation to listen the action when meeting participant hit mute button.

**Comment by mahdidham** [comment]
#177 #196

**Comment by tuantvu** [comment]
Rolling this issue into #231
