### ISSUE TITLE
SOLVED - Obtain an updated library from the vendor

### ISSUE THREAD

**Issue by SS-Akash** [gunschu/jitsi_meet#216]
Hello, I am getting this kind of error when creating IPA please help.

'.../ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '.../ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' for architecture arm64

I have tried disabling bitcode for jitsi but still no luck.

Flutter version - 2.0.1
Xcode version - 12.4 (12D4e)
System - Apple Silicon (M1 Chip)

**Comment by steveny909** [comment]
I'm getting same error and have same versions of Flutter and Xcode.

**Comment by tabilkhaiyr** [comment]
Having the same error, cant continue development of my app without resolving it

**Comment by willwach** [comment]
Flutter version - 2.0.1
Xcode version - 12.4
System - Apple Silicon (M1 Chip)

Getting the same error here:

` ld: '...ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file ... /ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' for architecture arm64
                        clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by jimmyjose-dev** [comment]
At the end of the pod file try adding this:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
```

then do a `pod update`

**Comment by willwach** [comment]
Thanks to you, @Snapworks .
It works, but i have to add this line too 'flutter_additional_ios_build_settings(target)' like the following:

`post_install do |installer|
  installer.pods_project.targets.each do |target|
  flutter_additional_ios_build_settings(target)
     target.build_configurations.each do |config|
         config.build_settings['ENABLE_BITCODE'] = 'NO'
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
         config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
end`

I'm coming from Android-Development and this will become my first ios-app.
Could you please explain what these changes will do.
Will '['ENABLE_BITCODE'] = NO have an influence on the functionality?

**Comment by jimmyjose-dev** [comment]
Enable/Disable Bitcode wont effect app functionality.

When you Disable Bitcode, Xcode will make a pre compiled single binary file for all platform 32bit,64bit etc,
When you Enable Bitcode, Xcode will just make an architecture independent file which they call as "intermediate representation of an app" ... it is then compiled on the fly to 32bit or 64 bit or other architecture depending on the downloading device.
