### ISSUE TITLE
SOLVED - IOS PIP BLACK BACKGROUND 

### ISSUE THREAD

**Issue by aartiaparekh** [gunschu/jitsi_meet#218]
In ios when I open pip mode background is black, I already set my screen but still its black.
I can't solve and its urgent. Please help me

**Comment by jimmyjose-dev** [comment]
Could you share more insight with a screenshot or show code that you have tried....

If you just wanna change the pip background color to something else... you may look into this thread
https://github.com/gunschu/jitsi_meet/issues/120#issuecomment-704934715

If you are not able to see the small video preview for PIP mode.. by default its OFF for iOS... you may need to turn that flag ON.

**Comment by aartiaparekh** [comment]
In android its working fine when in pip. But in ios I can't see background screen when in pip its black screen in background.

**Comment by jimmyjose-dev** [comment]
@aartiaparekh Mam,

See my previous comment in addition to that change the `.fullScreen `thing to `.overCurrentContext`

https://github.com/gunschu/jitsi_meet/blob/22bf4eba04d281719211dc5ef8e0bab30082bb7b/ios/Classes/SwiftJitsiMeetPlugin.swift#L101

And you will achieve similar result
<img width="414" alt="Screenshot 2021-03-11 at 4 14 06 PM" src="https://user-images.githubusercontent.com/1427616/110775486-f903c580-8284-11eb-9c20-61d0570930fc.png">

**Comment by jimmyjose-dev** [comment]
After making the changes make sure you delete the app and build/run again.

If this gets enough votes... maybe I will take out some time and merge in the main library.

**Comment by aartiaparekh** [comment]
@Snapworks  Thank you so much to help me.

**Comment by bharathraj-e** [comment]
@Snapworks  It works within the app! But when i put the app in backgroud / minimize to home screen/  Switch to other app the pip also hides, but still in pip mode when i switch to jisti app

**Comment by saibotma** [comment]
It is fixed in my clone of the plugin: https://pub.dev/packages/jitsi_meet_wrapper
