### ISSUE TITLE
Is there a way to fully customize the conference widget?

### ISSUE THREAD

**Issue by MoacirSchmidt** [gunschu/jitsi_meet#22]
I would like to know if there is a way to fully customize the conference widget?

Congratulations for your job!

**Comment by buzzwin** [comment]
There is currently no way to customize the look and feel , if thats what you are asking

**Comment by vinodlee** [comment]
for customizing the conference UI, If any possibilities for Customize the UI?

**Comment by piyushrathodIn** [comment]
I guess we can not fully customise the widget but there options to enable/disable some features like chat feature etc.

**Comment by tuantvu** [comment]
See feature flags support for what Jitsi supports out of the box. For further customization, modifying the official Jitsi Mobile SDK is required.
