### ISSUE TITLE
Build jitsi error when update flutter 2.0

### ISSUE THREAD

**Issue by holland-hng** [gunschu/jitsi_meet#220]
Hello, please help me.

When I update flutter I have a problem when building jisti. This is an old error in some issues but now I can't handle it.

In the simulator it seems to work well, but when build in a real device...

```
gRPC-C++-gRPCCertificates-Cpp-dgazteahseswureooxaabpmlvteb
    ld: '/Users/hacnguyen/Documents/app/flutter/tingtong/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/hacnguyen/Documents/app/flutter/tingtong/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    gRPC-C++-gRPCCertificates-Cpp-dgazteahseswureooxaabpmlvteb
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
Could not build the precompiled application for the device.
```

![Screen Shot 2021-03-23 at 03 32 10](https://user-images.githubusercontent.com/40235483/112054535-4ab32680-8b88-11eb-838c-328e0b7e2909.png)

**Comment by ajw227** [comment]
+1

**Comment by asynchronizd** [comment]
Dude! this one occurred to me too! I forgot what I did. Try loggin in to xcode and attaching the account to the project. The team thing.

**Comment by tuantvu** [comment]
Have you tried this? https://stackoverflow.com/questions/32640149/disable-bitcode-for-project-and-cocoapods-dependencies-with-xcode-7.

**Comment by tuantvu** [comment]
@hacnguyen1412 Seems you logged a different issue and was able to solve this? If so, please close the issue. I've updated the documentation to include disabling bitcode per official Jitsi meet instructions.

**Comment by holland-hng** [comment]
in new version, everything work ok, thank all
