### ISSUE TITLE
Release version of apk becoming 100+MB

### ISSUE THREAD

**Issue by aayushkedawat** [gunschu/jitsi_meet#222]
On adding jitsi_meet SDK to my app, the size of the apk becomes 100+MB.

**Comment by tuantvu** [comment]
APKs contain all four types of builds: arm7, etc. The example apk is between 150 - 200 MB, but when I ran flutter build appbundle on the example app, it was cut down to 54 MB. The app size varies based on the device it is downloaded to ultimately.

<img width="639" alt="Screen Shot 2021-04-02 at 12 19 04 AM" src="https://user-images.githubusercontent.com/19482735/113392160-89479e80-9349-11eb-8355-e5a6a7405e64.png">

The Jitsi was also asked this, but closed their issues. See: 

- https://community.jitsi.org/t/jitsi-jitsi-meet-sdk-samples-apk-size-is-85-mb/55683
- https://github.com/jitsi/jitsi-meet/issues/7845
