### ISSUE TITLE
Extern microphones not compatible with the app

### ISSUE THREAD

**Issue by selenmann** [gunschu/jitsi_meet#223]
external microphones are not compatible with the jitsi app;  please insert a solution or a setting "use external microphone"

**Comment by tuantvu** [comment]
@selenmann Do you know if the official Jitsi.org app supports external microphones? https://jitsi.org/downloads/

**Comment by selenmann** [comment]
I don't know if that works, I can try.  I'll write back in a few days. 🌱

**Comment by selenmann** [comment]
I do not understand what to do. I have the app installed, but I can not connect a big microphone with an adapter and talk about it. This is my problem and you need just a setting "Use microphone via USB" and then turn off that you talk about the micro in the headlier and turn on that you talk to the USB

**Comment by selenmann** [comment]
And no, mikrophones are not compatible with the jitsi.org

**Comment by tuantvu** [comment]
We can only support functionality that jitsi supports. Please ask your question on community.jitsi.org and if they add the feature, you can open a feature request for this plugin.

**Comment by selenmann** [comment]
the website have this setting (USB Audio). the app not. please fix that.
