### ISSUE TITLE
[BUG]: jitsimeet.close() not working properly

### ISSUE THREAD

**Issue by Yogesh-333** [gunschu/jitsi_meet#224]
when the call is in pip mode jitsimeet.close works properly if not in pip then it forcely closes the entire app

**Comment by tuantvu** [comment]
Just published version 2.1.0. @Yogesh-333  please test and confirm fix.

**Comment by Yogesh-333** [comment]
Thanks for the quick response the problem jitsimeet.close() is fixed although even after closing the meet it stays in second screen in recent apps
