### ISSUE TITLE
[BUG]: Chat in IOS

### ISSUE THREAD

**Issue by holland-hng** [gunschu/jitsi_meet#238]
**jitsi_meet plugin version**
all version 

**Describe the bug**
Can not enter new message after sending the first message by click icon-button send.

**To Reproduce**

![image](https://user-images.githubusercontent.com/40235483/113633261-d18ef580-9696-11eb-949c-fe8455a27b68.png)

**Flutter doctor -v**
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (1 available)

**Smartphone (please complete the following information):**
 - iPhone 7 plus

**Additional context**
nothing

**Error Logs**
nothing

**Comment by holland-hng** [comment]
help me

**Comment by devAbdulAzizUmar** [comment]
I am facing the same issue.

**Comment by holland-hng** [comment]
hey, has anyone seen it?
