### ISSUE TITLE
Addition of MuteAll,Screen Sharing and Lobby mode in feature flags.

### ISSUE THREAD

**Issue by vikaskonaparthi** [gunschu/jitsi_meet#240]
**Description**
As a developer, I would like to enable and disable "mute for all" ,"screen sharing" and "lobby" feature flags in Flutter SDK because these are not available as feature flags and these features having the control to every user can mislead meeting.

**Is the feature supported by Jitsi?**
jitsi_meet Flutter plugin is dependent on the [Android](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk) and [iOS](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk) SDK from jitsi.org. If those SDKs do not support a feature, we also can not add it.
* [x] Yes
* [ ] No

**Describe the solution you'd like**
Adding "mute for all" ,"screen sharing" and "lobby" diable and enable.

    featureFlag.kickOutEnabled = true;
    featureFlag.meetingPasswordEnabled = true;
    featureFlag.videoShareButtonEnabled = true;
    featureFlag.liveStreamingEnabled = true;
    featureFlag.meetingPasswordEnabled=true;
    featureFlag.toolboxAlwaysVisible=false;

   To be added

   "
    featureFlag.muteAllEnabled=false;
    featureFlag.screenSharingEnabled=false;
    featureFlag.lobbyEnabled=false;
   "

**Comment by AmgadMahmoud** [comment]
I have same problem
it's very important to add featureflag for muteAll, lobbyMode, screenSharing

**Comment by tuantvu** [comment]
@Vikas-Konaparthi Did you add a link to Jitsi documentation that supports these features?

**Comment by vikaskonaparthi** [comment]
@tuantvu  Ya mute is available on the web [https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js). Moreover lobby feature and screen sharing are not necessary to be included. If feature flags are available then I can provide screen sharing and lobby to whoever to use that feature.

![Screenshot_20210410-102943](https://user-images.githubusercontent.com/44503709/114258954-fe6d4080-99e7-11eb-89fb-19291fa2a2fd.png)

We can have a glace on this screen as you can see the lobby,muteAll and screen sharing modes in flutter mobile SDK which does not have any feature flags.

**Comment by tuantvu** [comment]
#235 already addresses the AUDIO_MUTE_BUTTON_ENABLED flag. There is not a flag for mute all, lobby, and screen sharing in the constants file you linked. As stated in the feature request, we can not add a feature flag when the official Jitsi sdk doesn't have it. Ask for the feature on community.jitsi.org first.
