### ISSUE TITLE
[UPGRADE]: <dependency-name, eg Jitsi Android SDK> to <version-number, eg 3.2.0> please setting usb audio in the app

### ISSUE THREAD

**Issue by selenmann** [gunschu/jitsi_meet#242]
**Dependency Information**
Name:
Version:
Platform
* [x] Android
* [ ] iOS
* [ ] Web 

**Reason for upgrade**

**Provide additional context**

**Comment by selenmann** [comment]
the jitsi website has the USB audio setting.  but not in the app.  please add this function to the app.

**Comment by selenmann** [comment]
the jitsi website has the USB audio setting.  but not in the app.  please add this function to the app.

**Comment by tuantvu** [comment]
You did not include any information for this upgrade in the description nor title. Invalidating.

**Comment by selenmann** [comment]
you bastard
