### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by namavarafshin** [gunschu/jitsi_meet#25]
Could not determine the dependencies of task ':jitsi_meet:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':jitsi_meet:debugCompileClasspath'.
   > Could not resolve org.jitsi.react:jitsi-meet-sdk:2.5.1.
     Required by:
         project :jitsi_meet
      > Could not resolve org.jitsi.react:jitsi-meet-sdk:2.5.1.
         > Could not get resource 'https://github.com/jitsi/jitsi-maven-repository/raw/master/releases/org/jitsi/react/jitsi-meet-sdk/2.5.1/jitsi-meet-sdk-2.5.1.pom'.
            > Could not GET 'https://raw.githubusercontent.com/jitsi/jitsi-maven-repository/master/releases/org/jitsi/react/jitsi-meet-sdk/2.5.1/jitsi-meet-sdk-2.5.1.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by tuantvu** [comment]
@namavarafshin We are on Jitsi version 2.9.0 now. Are you still having the issue?
