### ISSUE TITLE
[BUG]: Manifest Merger failed

### ISSUE THREAD

**Issue by bharathmsd7** [gunschu/jitsi_meet#250]
**jitsi_meet plugin version**
 jitsi_meet: 4.0.0 

**Describe the bug**
This error is shown when I upgraded the minimum SDK version in android from 16 to 23 in build.gradle. Because jitsi_meet needs minimum SDK version of 23.

Build failed with an exception.

Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute application@label value=(flutterapp) from AndroidManifest.xml:4:9-35
  	is also present at [org.jitsi.react:jitsi-meet-sdk:3.3.0] AndroidManifest.xml:34:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:3:4-40:19 to override.

**To Reproduce**
I tried to use jitsi_meet plugin in my Flutter project

**Flutter doctor -v**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Linux, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] Connected device (2 available)

• No issues found!

**Smartphone (please complete the following information):**
 - Device: Redmi Note 7 pro
 - Physical 
 - OS: android 
 - Version: 29

**Error Logs**
Launching lib/main.dart on Redmi Note 7 Pro in debug mode...
Running Gradle task 'assembleDebug'...
/home/bharath/jitsiflutter/egnaromeet/android/app/src/debug/AndroidManifest.xml:4:9-35 Error:
	Attribute application@label value=(flutterapp) from AndroidManifest.xml:4:9-35
	is also present at [org.jitsi.react:jitsi-meet-sdk:3.3.0] AndroidManifest.xml:34:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:3:4-40:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute application@label value=(flutterapp) from AndroidManifest.xml:4:9-35
  	is also present at [org.jitsi.react:jitsi-meet-sdk:3.3.0] AndroidManifest.xml:34:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:3:4-40:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1

**Code **
https://pub.dev/packages/jitsi_meet/example

**Comment by tuantvu** [comment]
Did you follow android manifest instructions in readme? https://github.com/gunschu/jitsi_meet#androidmanifestxml

**Comment by bharathmsd7** [comment]
Thanks for that @tuantvu 
It works fine.
Another doubt for me
I have a local Jitsi server setup in my machine
why i tried to join already started meet It works fine,
But when I tried to join the meet which has not started It asks me to login to be a host. I gave the host credentials but its not working.
Sorry I am new to this.

**Comment by tuantvu** [comment]
I can't help with this since I haven't tried to connect to my own server yet.

**Comment by tuantvu** [comment]
Gonna close this bug since it is resolved. You may try with the official jitsi app for your other issue and see if it exists there. If so, bring it up with community.jitsi.org
