### ISSUE TITLE
[BUG]: not able to find recorded file in android phone

### ISSUE THREAD

**Issue by Dhawansumit** [gunschu/jitsi_meet#253]
Hi,
I have used Jitsi Meet in one of my android project.
Now if I start the meeting and start recording of that ..it is working fine. and after stoping recording it's stoped recording.
but where I can find that recorded video file in my android phone. I was not able to do that.

please help me.

**Comment by DenisMrGnusa** [comment]
same problem,

**Comment by sarmiladhandapani** [comment]
same problem, I couldn't find the recorded video in the mobile (Developed using flutter)
