### ISSUE TITLE
How can i remove minimize icon button inside jitsi_meet screen

### ISSUE THREAD

**Issue by vinodlee** [gunschu/jitsi_meet#26]
How can I remove the minimize icon button inside the jitsi_meet screen?
If anybody knows please share your knowledge, it's useful for me :)

**Comment by TBG-FR** [comment]
You can fully disable PIP (Picture in Picture) mode, which is what this button is useful for.
If this is what you need, just look at the comments on issue #8 !

**Comment by tuantvu** [comment]
@vinodlee Please see disabling PIP mode. If this solves your issue, please close this.

**Comment by vinodlee** [comment]
Thanks for your quick response
