### ISSUE TITLE
[FEATURE]: Custom UI (embedded view)

### ISSUE THREAD

**Issue by JValderramaN** [gunschu/jitsi_meet#260]
**Description**
Hi!

Thanks for a huge job porting Jitsi to us in flutter. 
What we would like, is to attach the UI of the call (not modify that, no necessary) into a custom UI, preventing cover all screen!

**Is the feature supported by Jitsi?**
We don't know if is possible, is a simple concept request but understand that this plugging is constrained. 

**Describe the solution you'd like**
We want to put the UI Call into a custom UI (I understand is possible in web, from the example), basically to not cover all screen on mobiles.

We need to allow the user touch another button outside jitsi.

**Describe alternatives you've considered**
Can we present alerts or similars during the Jitsi Call? 

-- 

Thanks in advance for any advice

**Comment by Leptopoda** [comment]
isn't this the same as #79 ?
