### ISSUE TITLE
[BUG]:  userAvatarURL not working anymor on itsi_meet: ^4.0.0

### ISSUE THREAD

**Issue by momoleu** [gunschu/jitsi_meet#262]
**jitsi_meet plugin version**

**Describe the bug**

**To Reproduce**

**Screenshots**

**Flutter doctor -v**

**Web (please complete the following information):**
 - OS: [e.g. Mac, Windows, Linux]

**Smartphone (please complete the following information):**
 - Physical or Emulator

**Additional context**

**Error Logs**

**Comment by AbdouEsi** [comment]
same issue

**Comment by ahmadf20** [comment]
I'm having the same issue!
