### ISSUE TITLE
[BUG]: Screen share does not work in iOS

### ISSUE THREAD

**Issue by aniketshinde007** [gunschu/jitsi_meet#265]
Screen share in iOS devices is not working.

**Comment by Faisalkc4u** [comment]
any solutions?

**Comment by surveshoeb** [comment]
Any update?

**Comment by saibotma** [comment]
Did anyone find a solution to this?

**Comment by saibotma** [comment]
Is working in my clone of the plugin: https://pub.dev/packages/jitsi_meet_wrapper
