### ISSUE TITLE
[BUG]: Unable to start meeting on web

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#267]
While initializing at init state I am getting the following error:
```
Adding listeners
Jistsi instance not exists event can't be attached
```

When tried to start meeting on the web am getting the following error:
```
JitsiMeetingOptions: JitsiMeetingOptions{room: 12332323245, serverURL: null, subject: Just Meet, token: null, audioMuted: true, audioOnly: true, videoMuted: true, userDisplayName: JAGUWEB, userEmail: jaguweb1234@gmail.com, iosAppBarRGBAColor :null, featureFlags: {FeatureFlagEnum.CALL_INTEGRATION_ENABLED: false, FeatureFlagEnum.INVITE_ENABLED: false, FeatureFlagEnum.TOOLBOX_ALWAYS_VISIBLE: false, FeatureFlagEnum.MEETING_PASSWORD_ENABLED: true, FeatureFlagEnum.PIP_ENABLED: false, FeatureFlagEnum.WELCOME_PAGE_ENABLED: false, FeatureFlagEnum.RAISE_HAND_ENABLED: true, FeatureFlagEnum.RECORDING_ENABLED: true, FeatureFlagEnum.LIVE_STREAMING_ENABLED: true, FeatureFlagEnum.CHAT_ENABLED: true} }
{"roomName":"12332323245","width":"100%","height":"100%","enableWelcomePage":false,"chromeExtensionBanner":null,"userInfo":{"displayName":"JAGUWEB"}}
null
error: NoSuchMethodError: invalid member on null: 'appendChild'
```
My code:
added this in index.html
`<script src="https://meet.jit.si/external_api.js" type="application/javascript"></script>`

my join meeting page: here I have tried to show the room name text field and join button on full screen when not in meeting and as soon as the user joins meeting the jitsiconferencing widget is shown on full screen. I don't like it as the example was shown with half screen meetConfig and the other with jitsiconferencing widget.
```
...
body: SafeArea(
          child: inMeeting ? SizedBox(
            width: double.maxFinite,
            height: double.maxFinite,
            child: JitsiMeetConferencing(
              extraJS: [
                // extraJs setup example
                '<script>function echo(){console.log("echo!!!")};</script>',
                '<script src="https://code.jquery.com/jquery-3.5.1.slim.js" integrity="sha256-DrT5NfxfbHvMHux31Lkhxg42LY6of8TaYyK50jnxRnM=" crossorigin="anonymous"></script>'
              ],
            ),
          ) : Container(
....
```
joinfunction:
```
...
await JitsiMeet.joinMeeting(
            options,
            listener: JitsiMeetingListener(onConferenceWillJoin: (message) {
              setState(() {
                inMeeting = true;
              });
              debugPrint("${options.room} will join with message: $message");
            }, onConferenceJoined: (message) async {
              debugPrint("${options.room} joined with message: $message");
            }, onConferenceTerminated: (message) {
              setState(() {
                inMeeting = false;
              });
              debugPrint("${options.room} terminated with message: $message");
            }
...
```

**Comment by jagadish-pattanaik** [comment]
Solved it!

**Comment by talski** [comment]
> Solved it!

What was your problem? I'm facing the same `error: NoSuchMethodError: invalid member on null: 'appendChild'`

**Comment by jagadish-pattanaik** [comment]
Use the joinMeeting code in the example of the jitsi meet plugin and also if are creating the jitsiconferencing widget just before meeting then just delay it by some milli seconds. 
But are you facing thus problem also #268 ? Am facing it please try and let me know. 

If the above method doesn't solve your problem then the issue has to be reopened.

**Comment by talski** [comment]
Could not get it working, I've ended up using a webview (webviewx package)

```dart
WebViewX(
  height: 505,
  initialContent: """
      <!DOCTYPE html>
      <body style="margin: 0;">
          <div id="meet"></div>
          <script src='https://meet.domain.com.br/external_api.js'></script>
          <script>
              const domain = 'meet.domain.com.br';
              const options = {
                  roomName: '${room}',
                  userInfo: {
                    displayName: '${username}'
                  },
                  width: '100%',
                  height: 500,
                  parentNode: document.querySelector('#meet')
              };
              const api = new JitsiMeetExternalAPI(domain, options);
          </script>
      </body>
      </html>""",
  initialSourceType: SourceType.HTML,
)
```

**Comment by jagadish-pattanaik** [comment]
Is using webview better than the jitsiconferencing widget?  
To get it working remove your old joinMeeting code and instead of that use the code in the plugin example and ensure that the jitsiconferencing widget is built before you call the function, use the delay function if required.

**Comment by mizukageyama** [comment]
@jagadish-pattanaik I am also experiencing this during InitState on flutter web:
Adding listeners
Jistsi instance not exists event can't be attached

May I ask how you solved it?

**Comment by cgowthamanmca** [comment]
@jagadish-pattanaik how to solve this

**Comment by jagadish-pattanaik** [comment]
To get it working remove your old joinMeeting code and instead of that use the code in the **plugin example** **(As there is a difference between example on Github and at Pub.dev**) 

If done the above one correctly then ensure that the jitsiconferencing widget is built before you call the function, **use the delay function if required.**

> @jagadish-pattanaik how to solve this

**Comment by okless71** [comment]
> Solved it!

Can you send what you've done? Need an example

**Comment by sushmoyr** [comment]
I am still facing the same problem. I am not using conference widget.
