### ISSUE TITLE
Unable to install apk

### ISSUE THREAD

**Issue by nvamsi214** [gunschu/jitsi_meet#27]
Im unable to install the apk if i build it with **jitsi_meet**.

Im getting this error when i try to install apk form adb :

`Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl1829908907.tmp/base.apk has no certificates at entry AndroidManifest.xml]
`

**Comment by prasenjitpickcel** [comment]
I am also getting the same issue, the issue comes when the app is signed

**Comment by tuantvu** [comment]
I'm not able to reproduce this issue and haven't seen it from others.
