### ISSUE TITLE
[FEATURE]: Differentiate host from participants

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#270]
The only problem in jitsi is the meeting is not secured any participant can do anything and has similar powers like host, please do something so that the host is over powered in the meeting and participants are under him/her. For example  like zoom and google meet.

**Comment by SushantGautam** [comment]
This is required and very relevant in the case of self-hosted servers.
There should be an option to disable some buttons there. #274 is relevant.

**Comment by jagadish-pattanaik** [comment]
Till now the provided feature flags don't work on the web, it's really causing problems. First, they need to be solved before adding these features.

**Comment by SushantGautam** [comment]
Do you mean that currently working flags are upstreamed from ([Jitsi Web Flags](https://jitsi.github.io/handbook/docs/user-guide/user-guide-advanced))?
Actually,
For the latest versions for self-hosted servers, "Lobby Feature' has been disabled by defaults. 
However, it can be made to display in Web UI via proper configs.

You mean, there should be something like: https://meet.jit.si/SheerHistoriesMistakeHalfway**?Lobby=Disable**, right?

Does this library depend on Web Version or Mobile SDKs?

**Comment by SushantGautam** [comment]
![image](https://user-images.githubusercontent.com/16721983/121859900-031be100-cd18-11eb-8d91-29c9a91fe597.png)
There is **toggleLobby** in https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe to hide that button from UI on web.

**Comment by jagadish-pattanaik** [comment]
I meant the feature flags given in this plugin when configured as per example don't work when joining on flutter web...they are not at all effective and the default settings are considered

**Comment by Achin-verma** [comment]
Hi @jagadish-pattanaik, I am also looking for the solution you asked. I have compiled the example and I found that any participant can do anything and has similar powers to the host. 
Let's say, I am the host and I have invited 5 people to a meeting and I want to hide the mute option to participants. How can I do in the current example?

I am not using any self-hosted server and I am using Defaults to Jitsi Meet's servers.

**Comment by jagadish-pattanaik** [comment]
@Achin-verma I have been able to increase host controls and powers to some extent in the meeting as well as outside the meeting through different ways which are not the most efficient ones, but I have not succeeded in doing it completely because in the plugin some feature flags aren't working in the latest version, so am still waiting for them to fix it. 

I have done what you want in my app [Just Meet](https://play.google.com/store/apps/details?id=com.jaguweb.jagu_meet) . Check it out if this is what you want. If yes I can provide you the repo link because it's too much to explain, if you still won't be able to get it then I will explain.

**Comment by Achin-verma** [comment]
> @Achin-verma I have been able to increase host controls and powers to some extent in the meeting as well as outside the meeting through different ways which are not the most efficient ones, but I have not succeeded in doing it completely because in the plugin some feature flags aren't working in the latest version, so am still waiting for them to fix it.
> 
> I have done what you want in my app [Just Meet](https://play.google.com/store/apps/details?id=com.jaguweb.jagu_meet) . Check it out if this is what you want. If yes I can provide you the repo link because it's too much to explain, if you still won't be able to get it then I will explain.

Thanks for your reply. Yes you can share the Just Meet repo for flutter.

**Comment by jagadish-pattanaik** [comment]
> > @Achin-verma I have been able to increase host controls and powers to some extent in the meeting as well as outside the meeting through different ways which are not the most efficient ones, but I have not succeeded in doing it completely because in the plugin some feature flags aren't working in the latest version, so am still waiting for them to fix it.
> > I have done what you want in my app [Just Meet](https://play.google.com/store/apps/details?id=com.jaguweb.jagu_meet) . Check it out if this is what you want. If yes I can provide you the repo link because it's too much to explain, if you still won't be able to get it then I will explain.
> 
> Thanks for your reply. Yes you can share the Just Meet repo for flutter.

@Achin-verma Welcome. [Just Meet Repo](https://github.com/jagadish-pattanaik/just-meet-public) . Its a lot of code to read and understand, so you can start a discussion on the above repo and I can help you by explaining.
