### ISSUE TITLE
Option to hide lobby mode button

### ISSUE THREAD

**Issue by SushantGautam** [gunschu/jitsi_meet#274]
We need to add an option to hide the **lobby mode** button in **FeatureFlag**.
Lobby mode feature has been in Jitsi and configs can be seen here https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js

There are some use cases where we would like to hide Lobby options. For eg, to the guests. If they are in the room but are not moderators we can hide it for them.

**Comment by expeed-rajesh** [comment]
@SushantGautam  Any option to hide from mobile side?
Ii it possible through server configuration ?
