### ISSUE TITLE
[BUG]: Unable to listen to generic listerners

### ISSUE THREAD

**Issue by thewall4095** [gunschu/jitsi_meet#280]
**jitsi_meet plugin version**
jitsi_meet: ^4.0.0

**Describe the bug**
Been trying to listen to some generic events like on comment, or on raise hands, etc. For that I figured I'd have to subscribe to what's called external events using genericListeners from JitsiMeetingListener.

**To Reproduce**

Here is the code : 
`    var options = JitsiMeetingOptions(room: 'roomTexttext') // ll be trimmed
      ..serverURL = "https://xyz.host.com"
      ..subject = "Meeting with Gunschu"
      ..userDisplayName = "My Name"
      ..userEmail = "myemail@email.com"
      ..userAvatarURL = "https://someimageurl.com/image.jpg" // or .png
      ..audioOnly = true
      ..audioMuted = true
      ..videoMuted = true
      ..featureFlags.addAll(featureFlags);`

`    await JitsiMeet.joinMeeting(
      options,
      listener: JitsiMeetingListener(
          onConferenceWillJoin: (message) {
            debugPrint("${options.room} will join with message: $message");
          },
          onConferenceJoined: (message) {
            debugPrint("${options.room} joined with message: $message");
          },
          onConferenceTerminated: (message) {
            debugPrint("${options.room} terminated with message: $message");
          },
          genericListeners: [
            JitsiGenericListener(
                eventName: 'readyToClose',
                callback: (dynamic message) {
                  print("readyToClose callback");
                }),
            JitsiGenericListener(
                eventName: 'chatUpdated',
                callback: (dynamic message) {
                  print("chatUpdated callback");
                }),
            JitsiGenericListener(
                eventName: 'endpointTextMessageReceived',
                callback: (dynamic message) {
                  print("endpointTextMessageReceived callback");
                }),
            JitsiGenericListener(
                eventName: 'incomingMessage',
                callback: (dynamic message) {
                  print("incomingMessage callback");
                }),
            JitsiGenericListener(
                eventName: 'outgoingMessage',
                callback: (dynamic message) {
                  print("outgoingMessage callback");
                }),
            JitsiGenericListener(
                eventName: 'raiseHandUpdated',
                callback: (dynamic message) {
                  print("raiseHandUpdated callback");
                }),
          ]),
    );`

**Flutter doctor -v**
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.3.1 20E241 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)

• No issues found!
`

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiomi Redmi 6]
 - Physical device
 - OS: Android 9

**Error Logs**
`D/JitsiMeetSDK(14888): ExternalAPI Sending event: CHAT_MESSAGE_RECEIVED with data: { NativeMap: {"senderId":"6a5789d3","message":"Cjvjv","isPrivate":false} }` 

I get the above printed on console ( clearly from jitsimeetSDK) but unable to catch the same event on flutter side of event catcher.

**Comment by tuantvu** [comment]
Make unstale

**Comment by tuantvu** [comment]
Not stale

**Comment by Tore93** [comment]
[UNSTALE]

**Same here!!** Trying to listen to "CHAT_MESSAGE_RECEIVED" or "incomingMessage" but no callback is triggered.
Even though i get the event log in my console, flutter cannot catch the event.

Console log is:

D/JitsiMeetSDK(20661): ExternalAPI Sending event: CHAT_MESSAGE_RECEIVED with data: { NativeMap: {"isPrivate":false,"message":"test message text","senderId":"afdc9da0"} } 

Thanks!!!!

**Comment by tuantvu** [comment]
Keep open

**Comment by tuantvu** [comment]
Not stale

**Comment by susdorf** [comment]
Please fix. Can not listen for 'audioMuteStatusChanged' events.

**Comment by chetu-ko** [comment]
Not stale

Events are perfectly working in debug mode but when I build it to release mode it's giving me the error of function not found with obfuscated code can anyone know the solution or have tried to fix it?.
