### ISSUE TITLE
[BUG]:  proguard-rules.pro file link is broken

### ISSUE THREAD

**Issue by sachin-dahal** [gunschu/jitsi_meet#281]
**jitsi_meet plugin version**
jitsi_meet: ^4.0.0

**Describe the bug**
Redirecting link of proguard-rules.pro file is broken in the main documentation page

**Additional context**
> documentation needs to get fixed

**Comment by fnoceda** [comment]
i hope help anything, temporaly can you acced to the example app and see, this solve the crash in release mode
https://raw.githubusercontent.com/gunschu/jitsi_meet/master/jitsi_meet/example/android/app/proguard-rules.pro

**Comment by sachin-dahal** [comment]
> i hope help anything, temporaly can you acced to the example app and see, this solve the crash in release mode
> https://raw.githubusercontent.com/gunschu/jitsi_meet/master/jitsi_meet/example/android/app/proguard-rules.pro

this one is fixed in the PR #282
