### ISSUE TITLE
Call doesn't end when user picked call from outside app

### ISSUE THREAD

**Issue by ibrahimxcool** [gunschu/jitsi_meet#289]
When User1 is in meeting with User2 in my JITSI APP. And User1 receives a call from outside the app and when user1 picks up the call... User1 connection doesn't end with User2

**Comment by jagadish-pattanaik** [comment]
@ibrahimxcool so in your app, a user can call another user and that user can pick up the call and talk? The picku up action can also be done from background right I mean outside the app. May I know how did you do it? The concept or your repo?

**Comment by sumitsharansatsangi** [comment]
@ibrahimxcool , I have also faced this issue with flutter android app. I haven't checked for ios. I  have checked for web and it is working fine.
The issue faced is that end call button(the red button ) is not working, and so call won't be able to be disconected .

I think this is the issue faced by @jagadish-pattanaik. 

The app is nothing but the example app. So, no need to share the github link or to show code, as it is already available in this repository

**Comment by jagadish-pattanaik** [comment]
@sumitsharansatsangi I am not facing any problem on android, I just wanted to know how he made the call feature with jitsi. This issue seems to happen with some people and not all.
