### ISSUE TITLE
Update Android Jitsi SDK to 2.8.1

### ISSUE THREAD

**Issue by nilsreichardt** [gunschu/jitsi_meet#29]
Currently this package is using `2.5.1`. But meanwhile `2.8.2` is already available.

**Comment by TBG-FR** [comment]
Agree. However, `2.8.0` seems more reasonable, considering `2.8.1` has an Android bug which forces to use `2.8.2`, and `2.8.2` has a bug on languages (language not detected, everything is displayed in english).

`2.8.0` has improved features, improved translations and less bugs
