### ISSUE TITLE
[FEATURE]: Implement Jitsi IFrame API Functions

### ISSUE THREAD

**Issue by mauricioluz** [gunschu/jitsi_meet#290]
Looking to Jitsi IFrame API Documentation (https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe) we can see some functions that are available to use.
Will these functions be implemented in this package?

**Comment by mauricioluz** [comment]
Any news?
If you want, I can help with this implementation.

**Comment by buzzwin** [comment]
It would be great if you would like to contribute , please make a branch and a pull request
