### ISSUE TITLE
Change on going conference notification title, body and icon

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#292]
When you start a meeting a notification pops up, which has a round icon saying <app name> is running, tap to stop and the channel of the notification is on going conference notification. How to changes its icon, title, and body or remove it completely and have my own.

**Comment by jagadish-pattanaik** [comment]
How to change the icon of ongoing conference notification icon to my app icon, it just shows a grey circle.

Steps to reproduce:
Start a meeting
then a notification will come which will stay until the meeting has been ended
I need to change the details and icon of that notififcation

**Comment by shabanov-krl** [comment]
any solutions?
