### ISSUE TITLE
Localize Interface

### ISSUE THREAD

**Issue by premy** [gunschu/jitsi_meet#30]
Thanks for this awesome plugin. Could you pls point out how I would go about translating the English text in the interface? Would like to show it in Portuguese, since we're using it here in Brazil.

**Comment by TBG-FR** [comment]
Hello,

Translation are made in the [Jitsi Meet SDK ](https://github.com/jitsi/jitsi-meet). I'm pretty sure they already have a complete list of translation for [portuguese ](https://github.com/jitsi/jitsi-meet/blob/master/lang/main-pt.json) and/or [Brazilian portuguese](https://github.com/jitsi/jitsi-meet/blob/master/lang/main-ptBR.json).

However, there is a bug with the latest version, I suggest you to use the `2.8.0` and not the `2.8.2`, because this latter one displays everything in english (that should be fixed in the next version, I've seen a [commit about it](https://github.com/jitsi/jitsi-meet/commit/9be78c60ebed6ce5a8f62dd3baf8132b31ebd870))

You need to change that inside this plugin's `build.gradle` :
```
implementation ('org.jitsi.react:jitsi-meet-sdk:2.8.0') { transitive = true }
```

**Comment by premy** [comment]
@TBG-FR thank u for your answer. I deployed jitsi on a Ubuntu server and there I changed the config to load the ptBR language file. And it's working fine if I connect to the server with chrome on my laptop. But I have not been able to find these configs in this plugin. The only thing I'm able to see is jitsi_meet.dart and jitsi_meeting_listener.dart'.
Looking into C:\Users\SunnySys\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\jitsi_meet-0.1.8\ did not reveal anything useful to me either. Where would this build.gradle you're referring to be and how would I go about referencing ptBR inside Jitsi Meet SDK from my flutter app? As you can see I'm not very familiar with the way plugins are integrated into flutter, so please bear with me.

**Comment by TBG-FR** [comment]
You're welcome.
The plugin itself isn't managing the language, it's using the Jitsi Meet SDK, which uses the language, and has an automatic detection of user's language. 

The plugin references a "link" and a version of the SDK to use, you'll find that in that file : https://github.com/gunschu/jitsi_meet/blob/master/android/build.gradle
So, assuming you work with Android Studio, you just have to go to "External Libraries", then "Flutter Plugin" and "jitsi_meet" and modify that file.

Be aware in that way, you modifiy the plugin but it's not included in version control, so the best option is probably either to fork this repo and use it as a submodule in your app repo, or just download the content of this repo and put it in your project (for example in `lib/external/jitsi_meet`) and then edit it's files as needed (+ modifying your `pubspec.yaml` to reference that folder, not using anymore automatic finding of `jitsi_meet` from pub.dev)

**Comment by premy** [comment]
Well my friend, just by doing:
`//implementation ('org.jitsi.react:jitsi-meet-sdk:2.5.1') { transitive = true }`
  `implementation ('org.jitsi.react:jitsi-meet-sdk:2.8.0') { transitive = true }`
Crashes the app:
[jitsimeetErr.txt](https://github.com/gunschu/jitsi_meet/files/4607029/jitsimeetErr.txt)

**Comment by premy** [comment]
This thread [jitsi.org](https://community.jitsi.org/t/jitsi-meet-displayname-via-url-param/32281/8) says we can now pass language thru querystring like so: 
`meet.myserver.com/meeting-refererence#config.defaultLanguage="ptBR"`
I tried to add it in joinMeeting like this:
```
.invokeMethod<String>('joinMeeting', <String, dynamic>{
          'room': options.room?.trim(),
          'serverURL': options.serverURL?.trim(),
          'subject': options.subject,
          'token': options.token,
          'audioMuted': options.audioMuted,
          'audioOnly': options.audioOnly,
          'videoMuted': options.videoMuted,
          'userDisplayName': options.userDisplayName,
          'userEmail': options.userEmail,
          'config.defaultLanguage':"ptBR"
        }
```
but it still loads english.

**Comment by premy** [comment]
@TBG-FR, If you can find the time, could you pls check out the errlog listed above to see if u can tell why your suggested modification (implementation ('org.jitsi.react:jitsi-meet-sdk:2.8.0') { transitive = true }) crashes my app? I've been trying all sorts of things to get the mobile interface localized, with no success so far, and without proper localization it's quite useless to our users here in Brazil

**Comment by LucasManerich** [comment]
same problem here, server configuration in portuguese but application still loads english.

**Comment by TBG-FR** [comment]
@premy Hey, I suggest you clone this repository, modify it to put `implementation ('org.jitsi.react:jitsi-meet-sdk:2.8.0') { transitive = true }` and then launch the app located in `/example` on your device, to see if you still have these crashes. You can also try (if not already done) another version between these two, Tell me how it goes !

@LucasManerich As said earlier, get SDK version `2.8.0` et wait for next version to be released, `2.8.2` seems definitely buggy on language detection...

**Comment by premy** [comment]
@LucasManerich Hey did you manage to make it work? No such luck for me (yet).

**Comment by LucasManerich** [comment]
@premy add this repository to your pubspec.yaml and follow the README.md configuration instructions:
```
jitsi_meet:
    git: git://github.com/gunschu/jitsi_meet.git
```

**Comment by tuantvu** [comment]
@premy We are on implementation ('org.jitsi.react:jitsi-meet-sdk:2.9.0') { transitive = true } now. Has your issue been resolved?

**Comment by premy** [comment]
Sorry for the late answer, I kind a missed this comment somehow. But yes it WORKS! Thanks a lot! Guess I can close this now.

**Comment by pishguy** [comment]
> 
> 
> This thread [jitsi.org](https://community.jitsi.org/t/jitsi-meet-displayname-via-url-param/32281/8) says we can now pass language thru querystring like so:
> `meet.myserver.com/meeting-refererence#config.defaultLanguage="ptBR"`
> I tried to add it in joinMeeting like this:
> 
> ```
> .invokeMethod<String>('joinMeeting', <String, dynamic>{
>           'room': options.room?.trim(),
>           'serverURL': options.serverURL?.trim(),
>           'subject': options.subject,
>           'token': options.token,
>           'audioMuted': options.audioMuted,
>           'audioOnly': options.audioOnly,
>           'videoMuted': options.videoMuted,
>           'userDisplayName': options.userDisplayName,
>           'userEmail': options.userEmail,
>           'config.defaultLanguage':"ptBR"
>         }
> ```
> 
> but it still loads english.

can we change Locale or language in join meeting options? i can't find any feature in new version of this library
