### ISSUE TITLE
Jitsi_meet session sound is having echo effect.

### ISSUE THREAD

**Issue by subhra9326** [gunschu/jitsi_meet#300]
**jitsi_meet plugin version**
  jitsi_meet 4.0.0

**Describe the bug**
 Jitsi_meet flutter integration gives a sound echo effect in the running session. It stops automatically when we start the Recording Option. and again echo effect starts when Recording is stoped.

I have tried. So many mobile phones in different internet connections with different locations. 

Flutter 2.2.3 • channel stable
Tools • Dart 2.13.4
environment:
  sdk: ">=2.12.0 <3.0.0"

**Comment by pulstar** [comment]
I am experiencing this problem too, while making simple calls between two peers.

**Comment by Mohamed-Gibreel** [comment]
@pulstar @subhra9326 were you able to find any solution for this ? It is currently one of our biggest problems. I tried disabling peer to peer mode but the echo is still there.
