### ISSUE TITLE
[BUG]: Not able to add KICK_OUT_ENABLED and VIDEO_SHARE_BUTTON_ENABLED

### ISSUE THREAD

**Issue by raju12974** [gunschu/jitsi_meet#302]
**jitsi_meet plugin version**

**Describe the bug**

**To Reproduce**

**Screenshots**

**Flutter doctor -v**

**Web (please complete the following information):**
 - OS: [e.g. Mac, Windows, Linux]

**Smartphone (please complete the following information):**
 - Physical or Emulator

**Additional context**

**Error Logs**

**Comment by Muhammad-Ullah** [comment]
@raju12974  having same issue in flutter, "There's no constant named 'KICK_OUT_ENABLED' in 'FeatureFlagEnum'. " 
Any idea how to solve it?

**Comment by ALBERT14143** [comment]
Same issue, I cannot set FeatureFlag to KICK_OUT_ENABLED
