### ISSUE TITLE
[BUG]: IOS "onPictureInPictureTerminated" callback not working

### ISSUE THREAD

**Issue by bharathraj-e** [gunschu/jitsi_meet#305]
jitsi_meet: 4.0.0 

**Describe the bug**
Jitsi IOS : JitsiMeetingListener - [onPictureInPictureTerminated] callback not working in both Broadcast listener and individual meeting listener

**To Reproduce**
1. Run the example folder with IOS Simulator / Real device
2. Set Listener for onPictureInPictureWillEnter in JitsiMeet.joinMeeting()
3. Set Listener for onPictureInPictureTerminated in JitsiMeet.joinMeeting()
4. Start meeting & Enter into pip mode : will receive callback in onPictureInPictureWillEnter
5. Exit from PIP (thats full screen view) : Not receiving any callback in onPictureInPictureTerminated

**Flutter doctor -v**
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/css/Development/src/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/css/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/css/Library/Java/JavaVirtualMachines/corretto-1.8.0_292/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 1BB88DBC-9428-49F5-9BAA-82BAF2372661 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.5.2 20G95
      darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      92.0.4515.159
  

**Smartphone:**
 - Device: iPhone 11 / Physical / iOS 14.7.1
 - Device: iPhone 12 pro max / Simulator / iOS 14.5
 

**Additional context**
- Followed this steps for PIP gets works [SOLVED - IOS PIP BLACK BACKGROUND #218](https://github.com/gunschu/jitsi_meet/issues/218)
- [onPictureInPictureWillEnter] & [onPictureInPictureTerminated] works fine on Android
- [onPictureInPictureWillEnter] works fine on iOS
- [onPictureInPictureTerminated] not works.

**Comment by mithunadhikari40** [comment]
Hi, I am facing this issue again. On android everything works fine. In iOS, onPictureInPictureWillEnter works fine, but onPictureInPictureTerminated is never called. Has anyone found any solution?
