### ISSUE TITLE
[BUG]: Crashing after building the app for release

### ISSUE THREAD

**Issue by pulstar** [gunschu/jitsi_meet#307]
**jitsi_meet plugin version**
jitsi_meet: 4.0.0

**Describe the bug**
Everything works fine in debug mode, but after building the app for release, Jitsi crashes and the app reloads.

**To Reproduce**
1. Run **flutter build apk**
2. Run **flutter install**
3. Test the app making a call

**Screenshots**
Not available

**Flutter doctor -v**
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [version 10.0.19042.1165], locale pt-BR)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\pulst\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\pulst\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (4 available)
    • Vivo XI (mobile)  • PRUCHYWGG6HYSK4H • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.1165]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 92.0.902.73

**Web (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 92.0.4515.159  64 bits

**Smartphone (please complete the following information):**
 - Device: Blu Vivo XI+
 - Physical or Emulator: Physical
 - OS: Android
 - Version: 9.0

**Additional context**
Do I need to buy a license for a release?

**Error Logs**
Not available

**Comment by binhitmobile** [comment]
Same issue!
flutter doctor -v
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.22449.1000], locale vi-VN)
    • Flutter version 2.2.0 at C:\src\flutter
    • Framework revision b22742018b (4 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\AORUS\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!

**Comment by matheusneumanndev** [comment]
same issue

**Comment by itsdani121** [comment]
have any found this issue solution?

**Comment by mojtabaghiasi** [comment]
same issue

**Comment by mojtabaghiasi** [comment]
@pulstar this solve my problem
Jitsi's SDK enables proguard, you should enable proguard and keep jitsi SDK,
this link maybe helps you :
[https://stackoverflow.com/questions/67184547/flutter-jitsi-stopping-in-release-mode](https://stackoverflow.com/questions/67184547/flutter-jitsi-stopping-in-release-mode)

**Comment by pulstar** [comment]
@mojtabaghiasi Thank you for the feedback! The original proguard-rules.pro file can be found here:

https://raw.githubusercontent.com/gunschu/jitsi_meet/master/jitsi_meet/example/android/app/proguard-rules.pro

**Comment by itsdani121** [comment]
I will try
