### ISSUE TITLE
[BUG]: Building application for Android fails

### ISSUE THREAD

**Issue by Juanixou** [gunschu/jitsi_meet#310]
I was working on my project, compiling as always to check my changes, and suddenly, jitsi stop working and now i can't compile it. I didn't change my gradle configuration or something similar, as i say, it stop working by it's own.

Here you have the error message when try to compile:
```
> Could not resolve all task dependencies for configuration ':app:prodDebugRuntimeClasspath'.
   > Could not resolve org.jitsi.react:jitsi-meet-sdk:2.+.
     Required by:
         project :app
      > Failed to list versions for org.jitsi.react:jitsi-meet-sdk.
         > Unable to load Maven meta-data from https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/maven-metadata.xml.
            > Could not get resource 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/maven-metadata.xml'.
               > Could not GET 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/maven-metadata.xml'.
                  > Connect to www.jitpack.io:443 [www.jitpack.io/149.56.28.39] failed: Connection refused: connect
      > Failed to list versions for org.jitsi.react:jitsi-meet-sdk.
         > Unable to load Maven meta-data from https://jitpack.io/org/jitsi/react/jitsi-meet-sdk/maven-metadata.xml.
            > Could not get resource 'https://jitpack.io/org/jitsi/react/jitsi-meet-sdk/maven-metadata.xml'.
               > Could not GET 'https://jitpack.io/org/jitsi/react/jitsi-meet-sdk/maven-metadata.xml'. Received status code 521 from server: 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s
Exception: Gradle task assembleProdDebug failed with exit code 1
```
I open an [issue ](https://github.com/jitsi/jitsi-meet/issues/9946) in jitsi-meet and they said to ask here.

**Comment by matheusneumanndev** [comment]
I have the same error

**Comment by DivyanshuCaremonitor** [comment]
Same error 

`FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':app:mergeReleaseResources'.

> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.

   > Could not resolve com.facebook.react:react-native-webview:11.0.2-jitsi-7097494.

     Required by:

         project :app > project :jitsi_meet > org.jitsi.react:jitsi-meet-sdk:3.3.0

      > Could not resolve com.facebook.react:react-native-webview:11.0.2-jitsi-7097494.

         > Could not get resource 'https://jcenter.bintray.com/com/facebook/react/react-native-webview/11.0.2-jitsi-7097494/react-native-webview-11.0.2-jitsi-7097494.pom'.

            > Could not GET 'https://jcenter.bintray.com/com/facebook/react/react-native-webview/11.0.2-jitsi-7097494/react-native-webview-11.0.2-jitsi-7097494.pom'.

               > Read timed out

   > Could not resolve com.facebook.react:react-native-splash-screen:3.2.0-jitsi-7097494.

     Required by:

         project :app > project :jitsi_meet > org.jitsi.react:jitsi-meet-sdk:3.3.0

      > Could not resolve com.facebook.react:react-native-splash-screen:3.2.0-jitsi-7097494.

         > Could not get resource 'https://jcenter.bintray.com/com/facebook/react/react-native-splash-screen/3.2.0-jitsi-7097494/react-native-splash-screen-3.2.0-jitsi-7097494.pom'.

            > Could not GET 'https://jcenter.bintray.com/com/facebook/react/react-native-splash-screen/3.2.0-jitsi-7097494/react-native-splash-screen-3.2.0-jitsi-7097494.pom'.

               > Read timed out

`
