### ISSUE TITLE
[BUG]: iOS video call screen not switch nicely to landscape mode after rotate phone

### ISSUE THREAD

**Issue by kmoreau** [gunschu/jitsi_meet#323]
Hello,

I have the same problem as this post : https://github.com/jitsi/jitsi-meet/issues/4802
He has problem in Cordova by using the iOS SDK (what this flutter library does in 'Jitsi_meet/iOS' ).

The problem occurs on iOS when you are in video conference, and you switch from portrait to landscape mode. The screen is cut in 2 with a black screen on one side and the video "truncated" on the other.

Do you have this problem too? And if yes how to solve it?

I tried to force the portrait mode in my iOS project and also in the iOS code of the "Jitsi_meet" lib (fork) but I only manage to keep the layout in "Portrait" ... the camera continues to rotate with a weird behavior...

thx

**Comment by saibotma** [comment]
Fixed in my clone of the plugin: https://pub.dev/packages/jitsi_meet_wrapper
