### ISSUE TITLE
Problems with sound

### ISSUE THREAD

**Issue by tunopendientes** [gunschu/jitsi_meet#33]
Hi and thanks for your work!

I have proved the jitsu original application from google and works fine without problem. I mean, it is not a problem from the server. I installed my own jitsi server and works perfectly.

But something happens when I run your application. The others can not hear to me but I can listen to them.

FOUND THE PROBLEM!!!!

I had an application to record all my calls and so soon as I uninstalled, no problem. But there is something that should investigate because as I said it workd perfectly with the original app from Jitsi.

I hope it can help you to improve this wonderfull job tht you did.

Have a good day

**Comment by TBG-FR** [comment]
Interesting issue ! Thanks for coming back to post your solution.

I know that the Jitsi Meet official app disabled the use of `ConnectionService` (https://github.com/jitsi/jitsi-meet/commit/95eb551156c6769e25be9855dd2bc21adf71ac76), I can't say for sure but maybe the conflict was here

What was the name of the app to record your calls ?
