### ISSUE TITLE
[BUG]: UNABLE TO INSTALL ON IOS

### ISSUE THREAD

**Issue by truly6ve** [gunschu/jitsi_meet#330]
I am getting the following error when I try to install app on iOS. I have tried to search everywhere but couldn't get any solution and found it's actually a long outstanding issue. I am using latest versions of flutter (2.5.3) and Xcode (13.0) and I get the same list errors even if I download and install the example project without any change. Can this be solved please?

`Xcode's output:
↳
    ....../flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.5/ios/Classes/strategies/PhonePermissio
    nStrategy.m:50:35: warning: 'subscriberCellularProvider' is deprecated: first deprecated in iOS 12.0 [-Wdeprecated-declarations]
        CTCarrier *carrier = [netInfo subscriberCellularProvider];
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                      serviceSubscriberCellularProviders
    In module 'CoreTelephony' imported from
    ..../flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.5/ios/Classes/strategies/PhonePermissio
    nStrategy.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/System/Library/Frameworks/
    CoreTelephony.framework/Headers/CTTelephonyNetworkInfo.h:112:50: note: property 'subscriberCellularProvider' is declared deprecated here
    @property(readonly, retain, nullable) CTCarrier *subscriberCellularProvider
    API_DEPRECATED_WITH_REPLACEMENT("serviceSubscriberCellularProviders", ios(4.0, 12.0)) API_UNAVAILABLE(macos);
                                                     ^
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/System/Library/Frameworks/
    CoreTelephony.framework/Headers/CTTelephonyNetworkInfo.h:112:50: note: 'subscriberCellularProvider' has been explicitly marked deprecated here
    1 warning generated.
    ....../flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.5/ios/Classes/strategies/PhonePermissio
    nStrategy.m:50:35: warning: 'subscriberCellularProvider' is deprecated: first deprecated in iOS 12.0 [-Wdeprecated-declarations]
        CTCarrier *carrier = [netInfo subscriberCellularProvider];
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                      serviceSubscriberCellularProviders
    In module 'CoreTelephony' imported from
    ....../flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.5/ios/Classes/strategies/PhonePermissio
    nStrategy.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/System/Library/Frameworks/
    CoreTelephony.framework/Headers/CTTelephonyNetworkInfo.h:112:50: note: property 'subscriberCellularProvider' is declared deprecated here
    @property(readonly, retain, nullable) CTCarrier *subscriberCellularProvider
    API_DEPRECATED_WITH_REPLACEMENT("serviceSubscriberCellularProviders", ios(4.0, 12.0)) API_UNAVAILABLE(macos);
                                                     ^
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/System/Library/Frameworks/
    CoreTelephony.framework/Headers/CTTelephonyNetworkInfo.h:112:50: note: 'subscriberCellularProvider' has been explicitly marked deprecated here
    1 warning generated.
    Command CompileSwiftSources failed with a nonzero exit code
    ....../flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:8:41:
    error: cannot find type 'PiPViewCoordinator' in scope
        fileprivate var pipViewCoordinator: PiPViewCoordinator?
                                            ^~~~~~~~~~~~~~~~~~
    ...../flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:87:30:
    error: cannot find 'PiPViewCoordinator' in scope
            pipViewCoordinator = PiPViewCoordinator(withView: jitsiMeetView)
                                 ^~~~~~~~~~~~~~~~~~
    ..../flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:102:30:
    error: 'nil' requires a contextual type
            pipViewCoordinator = nil
                                 ^
    ....flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:8:41:
    error: cannot find type 'PiPViewCoordinator' in scope
        fileprivate var pipViewCoordinator: PiPViewCoordinator?
                                            ^~~~~~~~~~~~~~~~~~
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

Could not build the application for the simulator.
`

**Comment by ltoenjes** [comment]
I too have this problem. Only happens on simulator for me.

**Comment by truly6ve** [comment]
> I too have this problem. Only happens on simulator for me.

Hi,

Finally, I got the solution to it. I edited the podfile with the following line: 

config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"

=======AS SHOWN IN THE EXAMPLE========
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

=======================================

Then:

1-> Open your project in Xcode 12 (or higher) and click on the targets
2-> Navigate to Build Settings of your project.
3-> Add Any iOS Simulator SDK with value arm64 inside Excluded Architectures.

then run "pod install" inside the ios folder and run build iOS app from xCode and it'll solve the issue.

Below is the link for full instructions which I follow...

https://milanpanchal24.medium.com/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios-file-for-8c0cc28ec832

You can use all other general commands like cleaning the flutter, repairing the packages etc. Let me know if you need any help.

I AM USING M1 WITH MACOS MONTEREY, VERSION 12.0.1 AND XCODE VERSION Version 13.1 (13A1030d).
