### ISSUE TITLE
[BUG]: Can't use FeatureFlagEnum.SERVER_URL_CHANGE_ENABLED

### ISSUE THREAD

**Issue by Jonas-Sander** [gunschu/jitsi_meet#332]
**jitsi_meet plugin version**
jitsi_meet: 4.0.0

**Describe the bug**
The `FeatureFlagEnum.SERVER_URL_CHANGE_ENABLED` is not exported by `'package:jitsi_meet/jitsi_meet.dart'` but by `'package:jitsi_meet/feature_flag/feature_flag_enum.dart'`.     
`JitsiMeetingOptions` only accept the `FeatureFlagEnum` defined in `'package:jitsi_meet/jitsi_meet.dart'` which means I can't use it. 

**To Reproduce**
```dart
import 'package:jitsi_meet/jitsi_meet.dart';

Future<void> bug() async {
  final featureFlags = {
    // Error here - see below
    FeatureFlagEnum.SERVER_URL_CHANGE_ENABLED: false,
  };

  final options = JitsiMeetingOptions(room: 'meetingId')
    ..featureFlags.addAll(featureFlags);

  await JitsiMeet.joinMeeting(options);
}
```
results in
```
There's no constant named 'SERVER_URL_CHANGE_ENABLED' in 'FeatureFlagEnum'.
```

```dart
import 'package:jitsi_meet/feature_flag/feature_flag_enum.dart';
import 'package:jitsi_meet/jitsi_meet.dart' as meet;

Future<void> bug() async {
  final featureFlags = {
    FeatureFlagEnum.SERVER_URL_CHANGE_ENABLED: false,
  };

  final options = meet.JitsiMeetingOptions(room: 'meetingId')
    // Error here - see below
    ..featureFlags.addAll(featureFlags);

  await meet.JitsiMeet.joinMeeting(options);
}
```

results in the following error
```
The argument type 'Map<FeatureFlagEnum, bool> (where FeatureFlagEnum is defined in ...\hosted\pub.dartlang.org\jitsi_meet-4.0.0\lib\feature_flag\feature_flag_enum.dart)' can't be assigned to the parameter type 'Map<FeatureFlagEnum, bool> (where FeatureFlagEnum is defined in ...\hosted\pub.dartlang.org\jitsi_meet_platform_interface-2.0.0\lib\feature_flag\feature_flag_enum.dart)'.
```

**Flutter doctor -v**
<details>
  <summary>Click to expand</summary>
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1288], locale de-DE)
    • Flutter version 2.5.2 at D:\Development\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (5 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Development\tools\Android_SDK
    • Platform android-31, build-tools 31.0.0
    • Java binary at: D:\Development\tools\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2)
    • Android Studio at D:\Development\tools\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\jonas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.54
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.40
</details>

**Comment by tuantvu** [comment]
Unstale

**Comment by Jonas-Sander** [comment]
This seems to be not fixed :(
