### ISSUE TITLE
[FEATURE]: Still maintained?

### ISSUE THREAD

**Issue by saibotma** [gunschu/jitsi_meet#334]
Is this repository still maintained?
I see that there are many open PRs and the last commits were months ago.

Just curious because I need to make business decisions based on that information.

**Comment by jagadish-pattanaik** [comment]
Please answer is it still being maintained? If yes when the new update for the plugin will be available? Present version has lot of bugs and with time has got depriciated.

**Comment by saibotma** [comment]
I cloned this repo, cleaned up the code and fixed many bugs. The new package is available here: https://pub.dev/packages/jitsi_meet_wrapper

**Comment by jagadish-pattanaik** [comment]
> I cloned this repo, cleaned up the code, and fixed many bugs. The new package is available here: https://pub.dev/packages/jitsi_meet_wrapper

That's great @saibotma but you have changed some basic class names and other things, if I use your package now I have to change a lot of stuff all around my application code and my application is very big, still, it's not that big problem I can do that if it's worth it. 

Btw, I wanted to ask what all changes you have made, have you fixed the bug in the latest version in which after adding web support lot of feature flags stopped working? Also, are all SDKs on their latest version?

Btw great job buddy!

**Comment by saibotma** [comment]
Yes, upgrading to my package is indeed a breaking upgrade. However, this is on purpose, as I wanted to clean up some naming & API issues. It should not be a huge effort to migrate, though.

If you need web support, then my package is not an option for you (at the moment) because I dropped it completely, as you can just launch a Jitsi URL using [`url_launcher`](https://pub.dev/packages/url_launcher) and this is sufficient for my use case.

I fixed a lot of bugs, I think you just need to try whether the bug you are thinking of is also fixed now. If not, then I can probably fix it.
All SDKs are on their latest version (updated last week).

**Comment by jagadish-pattanaik** [comment]
Great lemme check out!

**Comment by zionnite** [comment]
hello @saibotma 
does your package have the option to hide the overflowing menu?

**Comment by saibotma** [comment]
You can basically do everything that you can do with the official SDKs.

**Comment by zionnite** [comment]
please show me, how do integrate it into my flutter app?

**Comment by saibotma** [comment]
Please first explain to me what you mean with "overflowing menu"?

**Comment by zionnite** [comment]
![IMG-20220503-WA0000.jpg](https://user-images.githubusercontent.com/10984801/166418149-fa34a55b-1be2-4e9e-9429-09e6fb57a4f4.jpg)

**Comment by zionnite** [comment]
I want there to option to disable or enable the following

1) Lobby Mode
2) Screen Sharing 
3) Youtube Sharing
4) Mute everyone
5) Disable everyone's camera



it would have been easier if there was an option to set Moderator to `TRUE` based on user admin privileges

**Comment by saibotma** [comment]
Here are all the options that you can toggle: https://pub.dev/documentation/jitsi_meet_wrapper_platform_interface/latest/feature_flag/FeatureFlag.html.

In addition to that you can also supply those (https://community.jitsi.org/t/how-to-how-to-customize-meeting-options/74665) config overrides either over the URL or the `configOverrides` parameter of `JitsiMeetingOptions`.

**Comment by zionnite** [comment]
> Here are all the options that you can toggle: https://pub.dev/documentation/jitsi_meet_wrapper_platform_interface/latest/feature_flag/FeatureFlag.html.
> 
> In addition to that you can also supply those (https://community.jitsi.org/t/how-to-how-to-customize-meeting-options/74665) config overrides either over the URL or the `configOverrides` parameter of `JitsiMeetingOptions`.

Thank you very much,
I just set the configuration for the the jitsi_wrapper,
though I dropped a question on your repo.

thanks for this package @saibotma
