### ISSUE TITLE
Flutter build is failing on jitsi_meet: ^2.1.0

### ISSUE THREAD

**Issue by laxmansahni** [gunschu/jitsi_meet#337]
We added `jitsi_meet: ^2.1.0` in pubspec.yaml.  Output of `flutter doctor -v`

[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-IN)
    • Flutter version 2.0.4 at /Users/laxmansahni/Documents/Workspace/flutter-2.0.4
    • Framework revision b1395592de (8 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/laxmansahni/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

However, we get 👇 errors:
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:lintVitalRelease'.   
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.jitsi.react:jitsi-meet-sdk:3.2.0.            
     Required by:                                                       
         project :app > project :jitsi_meet                             
      > Could not resolve org.jitsi.react:jitsi-meet-sdk:3.2.0.         
         > Could not get resource 'https://google.bintray.com/exoplayer/org/jitsi/react/jitsi-meet-sdk/3.2.0/jitsi-meet-sdk-3.2.0.pom'.
            > Could not HEAD 'https://google.bintray.com/exoplayer/org/jitsi/react/jitsi-meet-sdk/3.2.0/jitsi-meet-sdk-3.2.0.pom'. Received status code 502 from server: Bad Gateway

**Comment by NikhilKukreja26** [comment]
Hello,

I am also facing this issue did you got any work around for this issue?

**Comment by J3thr0-6** [comment]
This worked for me,

put this in allprojects>repositories in build.gradle

maven{
      url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
}

**Comment by pulstar** [comment]
Worked for me too.

**Comment by snmn** [comment]
worked for me too
also add 
minSdkVersion = 24 in build.gradle
