### ISSUE TITLE
iOS Build problem

### ISSUE THREAD

**Issue by orkwizard** [gunschu/jitsi_meet#34]
Im running XCode 11.3.1

I did the pod update and pod install --repo-udpate  and get:

CocoaPods 1.9.1 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.9.1

Analyzing dependencies
Downloading dependencies
Installing Firebase (6.24.0)
Installing FirebaseAnalytics (6.5.0)
Installing FirebaseAnalyticsInterop (1.5.0)
Installing FirebaseCore (6.7.0)
Installing FirebaseCoreDiagnostics (1.3.0)
Installing FirebaseCoreDiagnosticsInterop (1.2.0)
Installing FirebaseInstallations (1.2.0)
Installing FirebaseInstanceID (4.3.4)
Installing FirebaseMessaging (4.4.0)
Installing Flutter (1.0.0)
Installing GoogleAppMeasurement (6.5.0)
Installing GoogleDataTransport (6.1.0)
Installing GoogleDataTransportCCTSupport (3.1.0)
Installing GoogleUtilities (6.6.0)
Installing JitsiMeetSDK (2.8.1)
Installing PromisesObjC (1.2.8)
Installing Protobuf (3.11.4)
Installing camera (0.0.1)
Installing firebase_messaging (0.0.1)
Installing flutter_plugin_android_lifecycle (0.0.1)
Installing image_picker (0.0.1)
Installing jitsi_meet (0.0.1)
Installing nanopb (1.30905.0)
Installing path_provider (0.0.1)
Installing path_provider_macos (0.0.1)
Installing url_launcher (0.0.1)
Installing url_launcher_macos (0.0.1)
Installing url_launcher_web (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 11 dependencies from the Podfile and 28 total pods installed.

When i try to build for iOS i get the following errors

<module-includes>:1:1: error: umbrella header for module 'GoogleDataTransport' does not include header 'GDTCORDataFuture.h' [-Werror,-Wincomplete-umbrella]
    #import "Headers/GoogleDataTransport-umbrella.h"
    ^
    <module-includes>:1:1: error: umbrella header for module 'GoogleDataTransport' does not include header 'GDTCORStoredEvent.h' [-Werror,-Wincomplete-umbrella]
    2 errors generated.
    In file included from /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCOREvent+NetworkConnectionInfo.m:17:
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCOREvent+NetworkConnectionInfo.h:17:9: fatal error: could not build module 'GoogleDataTransport'
    #import <GoogleDataTransport/GDTCOREvent.h>

I have AndroidStudio 3.5.3
Mojave 10.14.6

Any ideas?

**Comment by buzzwin** [comment]
Please try updating all your firebase pods and see if the error goes away .. 
    On Monday, May 11, 2020, 08:39:48 AM CDT, orkwizard <notifications@github.com> wrote:  
 
 


Im running XCode 11.3.1

I did the pod update and pod install --repo-udpate and get:

CocoaPods 1.9.1 is available.
To update use: sudo gem install cocoapods

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.9.1

Analyzing dependencies
Downloading dependencies
Installing Firebase (6.24.0)
Installing FirebaseAnalytics (6.5.0)
Installing FirebaseAnalyticsInterop (1.5.0)
Installing FirebaseCore (6.7.0)
Installing FirebaseCoreDiagnostics (1.3.0)
Installing FirebaseCoreDiagnosticsInterop (1.2.0)
Installing FirebaseInstallations (1.2.0)
Installing FirebaseInstanceID (4.3.4)
Installing FirebaseMessaging (4.4.0)
Installing Flutter (1.0.0)
Installing GoogleAppMeasurement (6.5.0)
Installing GoogleDataTransport (6.1.0)
Installing GoogleDataTransportCCTSupport (3.1.0)
Installing GoogleUtilities (6.6.0)
Installing JitsiMeetSDK (2.8.1)
Installing PromisesObjC (1.2.8)
Installing Protobuf (3.11.4)
Installing camera (0.0.1)
Installing firebase_messaging (0.0.1)
Installing flutter_plugin_android_lifecycle (0.0.1)
Installing image_picker (0.0.1)
Installing jitsi_meet (0.0.1)
Installing nanopb (1.30905.0)
Installing path_provider (0.0.1)
Installing path_provider_macos (0.0.1)
Installing url_launcher (0.0.1)
Installing url_launcher_macos (0.0.1)
Installing url_launcher_web (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 11 dependencies from the Podfile and 28 total pods installed.

When i try to build for iOS i get the following errors

:1:1: error: umbrella header for module 'GoogleDataTransport' does not include header 'GDTCORDataFuture.h' [-Werror,-Wincomplete-umbrella]
#import "Headers/GoogleDataTransport-umbrella.h"
^
:1:1: error: umbrella header for module 'GoogleDataTransport' does not include header 'GDTCORStoredEvent.h' [-Werror,-Wincomplete-umbrella]
2 errors generated.
In file included from /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCOREvent+NetworkConnectionInfo.m:17:
/Users/edgar/StudioProjects/spheresDoctor/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCOREvent+NetworkConnectionInfo.h:17:9: fatal error: could not build module 'GoogleDataTransport'
#import <GoogleDataTransport/GDTCOREvent.h>

I have AndroidStudio 3.5.3
Mojave 10.14.6

Any ideas?

**Comment by orkwizard** [comment]
I get this 

Xcode's output:
↳
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:23:41: error: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'
        public static func == (a: JitsiMeet.PiPViewCoordinator.Position, b: JitsiMeet.PiPViewCoordinator.Position) -> Swift.Bool
                                  ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:23:83: error: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'
        public static func == (a: JitsiMeet.PiPViewCoordinator.Position, b: JitsiMeet.PiPViewCoordinator.Position) -> Swift.Bool
                                                                            ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:29:52: error: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'
      public var initialPositionInSuperview: JitsiMeet.PiPViewCoordinator.Position
                                             ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:31:39: error: 'PiPViewCoordinatorDelegate' is not a member type of 'JitsiMeet'
      weak public var delegate: JitsiMeet.PiPViewCoordinatorDelegate?
                                ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:34:42: error: 'AnimationCompletion' is not a member type of 'JitsiMeet'
      public func show(completion: JitsiMeet.AnimationCompletion? = nil)
                                   ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:35:42: error: 'AnimationCompletion' is not a member type of 'JitsiMeet'
      public func hide(completion: JitsiMeet.AnimationCompletion? = nil)
                                   ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:50:62: error: 'JMCallKitListener' is not a member type of 'JitsiMeet'
      @objc public static func addListener(_ listener: JitsiMeet.JMCallKitListener)
                                                       ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:51:65: error: 'JMCallKitListener' is not a member type of 'JitsiMeet'
      @objc public static func removeListener(_ listener: JitsiMeet.JMCallKitListener)
                                                          ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:43:35: error: unknown attribute '_hasMissingDesignatedInitializers'
    @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class JMCallKitProxy : ObjectiveC.NSObject {
                                      ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:43:1: error: unknown attribute '_inheritsConvenienceInitializers'
    @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class JMCallKitProxy : ObjectiveC.NSObject {
    ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:71:21: error: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'
    extension JitsiMeet.PiPViewCoordinator.Position : Swift.Equatable {}
              ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:72:21: error: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'
    extension JitsiMeet.PiPViewCoordinator.Position : Swift.Hashable {}
              ~~~~~~~~~ ^
    /Users/edgar/development/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.2.0/ios/Classes/JitsiViewController.swift:2:8: error: failed to load module 'JitsiMeet'
    import JitsiMeet
           ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:23:41: error: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'
        public static func == (a: JitsiMeet.PiPViewCoordinator.Position, b: JitsiMeet.PiPViewCoordinator.Position) -> Swift.Bool
                                  ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:23:83: error: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'
        public static func == (a: JitsiMeet.PiPViewCoordinator.Position, b: JitsiMeet.PiPViewCoordinator.Position) -> Swift.Bool
                                                                            ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:29:52: error: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'
      public var initialPositionInSuperview: JitsiMeet.PiPViewCoordinator.Position
                                             ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:31:39: error: 'PiPViewCoordinatorDelegate' is not a member type of 'JitsiMeet'
      weak public var delegate: JitsiMeet.PiPViewCoordinatorDelegate?
                                ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:34:42: error: 'AnimationCompletion' is not a member type of 'JitsiMeet'
      public func show(completion: JitsiMeet.AnimationCompletion? = nil)
                                   ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:35:42: error: 'AnimationCompletion' is not a member type of 'JitsiMeet'
      public func hide(completion: JitsiMeet.AnimationCompletion? = nil)
                                   ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:50:62: error: 'JMCallKitListener' is not a member type of 'JitsiMeet'
      @objc public static func addListener(_ listener: JitsiMeet.JMCallKitListener)
                                                       ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:51:65: error: 'JMCallKitListener' is not a member type of 'JitsiMeet'
      @objc public static func removeListener(_ listener: JitsiMeet.JMCallKitListener)
                                                          ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:43:35: error: unknown attribute '_hasMissingDesignatedInitializers'
    @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class JMCallKitProxy : ObjectiveC.NSObject {
                                      ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:43:1: error: unknown attribute '_inheritsConvenienceInitializers'
    @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class JMCallKitProxy : ObjectiveC.NSObject {
    ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:71:21: error: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'
    extension JitsiMeet.PiPViewCoordinator.Position : Swift.Equatable {}
              ~~~~~~~~~ ^
    /Users/edgar/StudioProjects/spheresDoctor/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:72:21: error: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'
    extension JitsiMeet.PiPViewCoordinator.Position : Swift.Hashable {}
              ~~~~~~~~~ ^
    /Users/edgar/development/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.2.0/ios/Classes/JitsiViewController.swift:2:8: error: failed to load module 'JitsiMeet'
    import JitsiMeet


I belive some people are having the same issue am i correct ?

**Comment by jayeshpansheriya** [comment]
i have same issue

i have also try to change flutter channel stable to beta

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.0)
[✓] Connected device (3 available)

**Comment by dreampowder** [comment]
I have fixed this issue by updating the jitsi meeting pod by running "pod update" inside the example/ios directory.

**Comment by jayeshpansheriya** [comment]
jisti meet sdk  2.5.2 is working fine

**Comment by jayeshpansheriya** [comment]
update xcode to 11.4 its working fine.

**Comment by orkwizard** [comment]
Updating fix the problems
