### ISSUE TITLE
[FEATURE]: disable audio processing

### ISSUE THREAD

**Issue by alanorder** [gunschu/jitsi_meet#340]
According to Jitsi, the default noise cancellation feature can be disabled by figuring the URL as follow:

https://meet.jit.si/mytestroom#config.disableAP=true

Is it possible to achieve the same effect when using the jitsi_meet plugin in Flutter?

I have looked through JitsiMeetingOptions and FeatureFlag and found nothing relevant. 

Is this something that can be included as an enhancement? Or the only solution is to host my own Jitsi and configure it through config.js?

**Comment by MohamedSci** [comment]
> According to Jitsi, the default noise cancellation feature can be disabled by figuring the URL as follow:
> 
> https://meet.jit.si/mytestroom#config.disableAP=true
> 
> Is it possible to achieve the same effect when using the jitsi_meet plugin in Flutter?
> 
> I have looked through JitsiMeetingOptions and FeatureFlag and found nothing relevant.
> 
> Is this something that can be included as an enhancement? Or the only solution is to host my own Jitsi and configure it through config.js?

I think it is great problem should be fixed soon.
