### ISSUE TITLE
The camera does not work properly

### ISSUE THREAD

**Issue by ebelloross** [gunschu/jitsi_meet#354]
**jitsi_meet plugin version**
 jitsi_meet: 4.0.0 Flutter 2.8.1

**Describe the bug**
When I start a meeting, the camera is active as the initial parameter, sometimes the screen stays black, the camera does not start.

**Screenshots**
<img width="414" alt="Screen Shot 2022-02-02 at 12 35 30 PM" src="https://user-images.githubusercontent.com/49915391/152207956-48fb53fd-ff94-4672-832a-caeaf73b706d.png">

**Flutter doctor -v**
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.0.1 20B29 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/zonitel/Development/flutter2.8/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/zonitel/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 62.0.3
    • Dart plugin version 212.5632

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Mi A3 (mobile)  • e0ba49b4ca7d              • android-arm64  • Android 11 (API 30)
    • iPhone (mobile) • 00008030-000E78140AD8402E • ios            • iOS 14.4 18D52
    • macOS (desktop) • macos                     • darwin-x64     • macOS 11.0.1 20B29 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 1 category.

**Comment by ebelloross** [comment]
By the way, the screenshot is from an emulator, but it also fails on a real device.

**Comment by snmn** [comment]
i am facing the same issue and sometimes the app crashes while video is enabled.
