### ISSUE TITLE
[BUG]: eko_jitsi build problem

### ISSUE THREAD

**Issue by alperbayata** [gunschu/jitsi_meet#355]
**jitsi_meet plugin version**

**Describe the bug**
I get an error when i start compiling the app

e: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\eko_jitsi-1.3.3\android\src\main\kotlin\com\ekodemy\eko_jitsi\EkoJitsiPluginActivity.kt: (224, 28): Type mismatch: inferred type is String? but String was expected

**Flutter doctor -v**
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19042.1466], locale tr-TR)
    • Flutter version 2.8.0 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (8 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Alper-DNB'\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: \Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Android Studio
    • Android Studio at \Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = \Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\Alper-DNB'\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1466]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)
**Web (please complete the following information):**
 - OS: [e.g. Mac, Windows, Linux]

 - Physical or Emulator
 - OS: android 10

**Error Logs**
e: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\eko_jitsi-1.3.3\android\src\main\kotlin\com\ekodemy\eko_jitsi\EkoJitsiPluginActivity.kt: (224, 28): Type mismatch: inferred type is String? but String was expected

**Comment by AbirAhsan** [comment]
In your error message EkoJitsiPluginActivity.kt (224, 28), 224 refers to the line number. So that's how you can find out where the error is. If I'm not mistaken that should be on the line that says

`wv.loadUrl(whiteboardUrl) `

loadUrl needs a String but whiteboardUrl is a String?. To promote it to a String you can write

`wv.loadUrl(whiteboardUrl!!)`
