### ISSUE TITLE
Draw widget over video screen

### ISSUE THREAD

**Issue by usamawork61** [gunschu/jitsi_meet#357]
Hi, im using jitsi meet in flutter, is there a way to draw a widget over the video meet screen? it covers the whole screen. i want a button over this for my custom functionality.

**Comment by iamtechmanish** [comment]
When overlaying Flutter widgets on top of HtmlElementView widgets that respond to mouse gestures (handle clicks, for example), the clicks will be consumed by the HtmlElementView, and not relayed to Flutter.

The result is that Flutter widget's onTap (and other) handlers won't fire as expected, but they'll affect the underlying webview.

To fix this you can use : [pointer_interceptor](https://pub.dev/packages/pointer_interceptor)

[Sample Code](https://stackoverflow.com/a/75513689/16952036)
