### ISSUE TITLE
iOS Build error 

### ISSUE THREAD

**Issue by jayeshpansheriya** [gunschu/jitsi_meet#36]
when i open my flutter project in xcode i got this error.

Documentation/Source/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:23:41: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'

Documentation/Source/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:29:52: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'

Documentation/Source/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:31:39: 'PiPViewCoordinatorDelegate' is not a member type of 'JitsiMeet'

Documentation/Source/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:34:42: 'AnimationCompletion' is not a member type of 'JitsiMeet'

Documentation/Source/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:35:42: 'AnimationCompletion' is not a member type of 'JitsiMeet'

Documentation/Source/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:50:62: 'JMCallKitListener' is not a member type of 'JitsiMeet'

Documentation/Source/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:51:65: 'JMCallKitListener' is not a member type of 'JitsiMeet'

Documentation/Source/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:43:35: Unknown attribute '_hasMissingDesignatedInitializers'

Documentation/Source/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:43:1: Unknown attribute '_inheritsConvenienceInitializers'

Documentation/Source/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:71:21: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'

Documentation/Source/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:72:21: 'PiPViewCoordinator' is not a member type of 'JitsiMeet'
flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.1.9/ios/Classes/JitsiViewController.swift:2:8: Failed to load module 'JitsiMeet'

**Comment by jayeshpansheriya** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.0)
[✓] Connected device (3 available)


name: videocall
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


 cupertino_icons: ^0.1.2
  jitsi_meet: ^0.1.6
  permission_handler: ^3.0.0
  provider: ^4.0.5
  dots_indicator: ^0.0.4
  dynamic_theme: ^1.0.1
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  flutter_native_splash: ^0.1.9
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.4.4
  share: ^0.6.4
  url_launcher: ^5.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.7.3"
  
flutter_icons:
    android: true
    ios: true
    image_path_ios: "lib/images/app_icon.png"
    image_path_android: "lib/images/app_icon_android.png"


flutter_native_splash:
  image: lib/images/app_icon_android.png
  color: fafafa


flutter:

  uses-material-design: true

  assets:
    - lib/images/get_connecting.png
    - lib/images/share_content.png
    - lib/images/start_meeting.png
    - lib/images/enter_code.png
    - lib/images/register.png
    - lib/images/login.png
    - lib/images/app_icon.png
    - lib/images/google_logo.png
    - lib/images/facebook_logo.png
    - lib/images/app_icon_android.png

**Comment by jayeshpansheriya** [comment]
i have already update sdk version 
`pod update JitsiMeetSDK  `  
but get same issues

**Comment by dreampowder** [comment]
Same here, started to show after i upgrade xcode to 11.4 from 11.3

**Comment by dreampowder** [comment]
The issue is related to this problem shown in original jitsi repository:
https://github.com/jitsi/jitsi-meet/issues/5389

**Comment by piyushrathodIn** [comment]
@jayeshpansheriya you can try to use lower version of JistiMeet SDK i.e. 2.7.0. It should work with XCode 11.3.

**Comment by jayeshpansheriya** [comment]
JistiMeet SDK 2.5.2. is working fine

**Comment by piyushrathodIn** [comment]
Great, I think for using the latest SDK you might need to update Xcode to 11.4

**Comment by buzzwin** [comment]
What Xcode version are you using ? 


Sent from Yahoo Mail for iPhone


On Saturday, May 23, 2020, 6:01 AM, Piyush Rathod <notifications@github.com> wrote:




Great, I think for using the latest SDK you might need to update Xcode to 11.4

**Comment by piyushrathodIn** [comment]
@buzzwin I am using xcode 11.3 with lower sdk version of JistiMeet.
