### ISSUE TITLE
[BUG]: Jitsi meet and Stripe not working at same time

### ISSUE THREAD

**Issue by ektapadaliya** [gunschu/jitsi_meet#360]
I'm facing issue while making release APK for android. 

In my app I used 
jitsi_meet : ^4.0.0
flutter_stripe: ^2.2.0

When I remove jitsi from app then release apk is working fine, but when both are there and try to make release apk then its giving me error.

`ERROR:/Users/ekta/.gradle/caches/transforms-3/3f7e8c51001519f7331a141b87c1ab6d/transformed/jetified-react-native-0.61.5-jitsi.2-runtime.jar: R8: Type com.facebook.react.bridge.ActivityEventListener is defined multiple times: /Users/ekta/.gradle/caches/transforms-3/3f7e8c51001519f7331a141b87c1ab6d/transformed/jetified-react-native-0.61.5-jitsi.2-runtime.jar:com/facebook/react/bridge/ActivityEventListener.class, /Users/ekta/Downloads/flueny_fair_start/build/stripe_android/intermediates/runtime_library_classes_jar/release/classes.jar:com/facebook/react/bridge/ActivityEventListener.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/ekta/.gradle/caches/transforms-3/3f7e8c51001519f7331a141b87c1ab6d/transformed/jetified-react-native-0.61.5-jitsi.2-runtime.jar:com/facebook/react/bridge/ActivityEventListener.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 4s
Running Gradle task 'assembleRelease'...                          366.5s
[!] The shrinker may have failed to optimize the Java bytecode.
    To disable the shrinker, pass the `--no-shrink` flag to this command.
    To learn more, see: https://developer.android.com/studio/build/shrink-code
Gradle task assembleRelease failed with exit code 1`

**Comment by Harishwarrior** [comment]
`To disable the shrinker, pass the --no-shrink flag to this command.` 

As the error mentioned for now or try `flutter clean`
