### ISSUE TITLE
cannot find 'PiPViewCoordinator' in scope

### ISSUE THREAD

**Issue by alabbasiDev** [gunschu/jitsi_meet#361]
error: cannot find 'PiPViewCoordinator' in scope
            pipViewCoordinator = PiPViewCoordinator(withView: jitsiMeetView)
 

my xcode version  is 12.5

<img width="742" alt="err" src="https://user-images.githubusercontent.com/50507978/155883631-2cade37e-4f6b-4a63-badf-129b40e8336e.png">

**Comment by RivaanRanawat** [comment]
I had the same error. I fixed it by adding below code to podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
       # Required by jitsi
     target.build_configurations.each do |config|
     config.build_settings['ENABLE_BITCODE'] = 'NO'
         config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
 end
end
```

**Comment by alabbasiDev** [comment]
I have tried that but it does not work. I still got the same error

**Comment by ayanbabi90** [comment]
same issue

**Comment by popekabu** [comment]
@ayanbabi90 It worked for me try this as stated, replace this chunk of code with yours inside your podfile. 

post_install do |installer|
  installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
       # Required by jitsi
     target.build_configurations.each do |config|
     config.build_settings['ENABLE_BITCODE'] = 'NO'
         config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
 end
end

All the best brother
