### ISSUE TITLE
Cannot find type 'PiPViewCoordinator' in scope

### ISSUE THREAD

**Issue by bhaviksoni12** [gunschu/jitsi_meet#362]
![image](https://user-images.githubusercontent.com/89898587/156114749-96636b9e-7a57-446f-9d25-225a33b5611a.png)

I am getting following error when i install JitsiMeetSDK in flutter but i am unable to run app. Can somebody suggest me how can i resolve this issue?

I am using following:

Xcode : 13.1

Swift : 5

jitsi_meet: ^4.0.0

Android Studio Bumblebee

**Comment by ayanbabi90** [comment]
I'm also getting the same error

**Comment by popekabu** [comment]
same issue using Flutter

**Comment by popekabu** [comment]
@ayanbabi90 replace this chunk of code with yours inside your podfile. 

post_install do |installer|
  installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
       # Required by jitsi
     target.build_configurations.each do |config|
     config.build_settings['ENABLE_BITCODE'] = 'NO'
         config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
 end
end

All the best brother

**Comment by bhaviksoni12** [comment]
Not worked for me.

**Comment by AkhilSajiCodzoc** [comment]
is there any improvements on this?

**Comment by bhaviksoni12** [comment]
Not yet. I have tried above mentioned thing but that did not worked.

**Comment by fikribasa** [comment]
thanks mate, it worked for me with https://github.com/gunschu/jitsi_meet/issues/362#issuecomment-1058010804,
but i need to do `flutter clean` first and delete `Podfile.lock` file, then `flutter pub get` and `pod install --repo-update`

**Comment by bhaviksoni12** [comment]
![image](https://user-images.githubusercontent.com/89898587/162369167-0441b856-d3cf-482a-b103-7c1e9b58c553.png)

I have put this in my podfile but still it didn't worked for me.

**Comment by ahmadzt** [comment]
I was able to resolve the issue with @popekabu comment

1.  add `config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"` inside your podfile
2. flutter clean
3. delete podfile.lock
4. flutter run

> @ayanbabi90 replace this chunk of code with yours inside your podfile.
> 
> post_install do |installer| installer.pods_project.targets.each do |target| flutter_additional_ios_build_settings(target) # Required by jitsi target.build_configurations.each do |config| config.build_settings['ENABLE_BITCODE'] = 'NO' config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64" end end end
> 
> All the best brother
