### ISSUE TITLE
Is this library supported to android 12? 

### ISSUE THREAD

**Issue by Meri994** [gunschu/jitsi_meet#366]
Here, I am testing the app in android 12 device but getting following issue.
 
 adb: failed to install E:\Flutter\flutter_jitsi\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl502165721.tmp/base.apk (at Binary XML file line #110): org.jitsi.meet.sdk.ConnectionService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]
Error launching application on sdk gphone64 x86 64.

Anyone can help to fix this issue?

**Comment by saibotma** [comment]
I created a rewrite of the package. It should support Android 12: https://pub.dev/packages/jitsi_meet_wrapper
