### ISSUE TITLE
[BUG]: This library is not supported in Android version 12.0

### ISSUE THREAD

**Issue by RajChavda** [gunschu/jitsi_meet#368]
**jitsi_meet plugin version**
jitsi_meet: ^4.0.

**Describe the bug**
A black screen appears or crashes into some Android devices while I was trying to make a meeting

**Error Logs**
init start
D/SoLoader( 7776): adding system library source: /vendor/lib
D/SoLoader( 7776): adding system library source: /system/lib
D/SoLoader( 7776): adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/~~Yz9uSeNN8HRjscxqglA9iA==/com.teksun.ichjitsi-dRl_hKiFdsd_xJz2U667Gg==/lib/x86_64 flags = 0]
D/SoLoader( 7776): adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/user/0/com.teksun.ichjitsi/lib-main flags = 1]
D/SoLoader( 7776): Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
D/SoLoader( 7776): Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
D/SoLoader( 7776): Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/~~Yz9uSeNN8HRjscxqglA9iA==/com.teksun.ichjitsi-dRl_hKiFdsd_xJz2U667Gg==/lib/x86_64 flags = 0]
D/SoLoader( 7776): Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/user/0/com.teksun.ichjitsi/lib-main flags = 1]
V/fb-UnpackingSoSource( 7776): locked dso store /data/user/0/com.teksun.ichjitsi/lib-main
I/fb-UnpackingSoSource( 7776): dso store is up-to-date: /data/user/0/com.teksun.ichjitsi/lib-main
V/fb-UnpackingSoSource( 7776): releasing dso store lock for /data/user/0/com.teksun.ichjitsi/lib-main
D/SoLoader( 7776): init finish: 4 SO sources prepared
D/SoLoader( 7776): init exiting
D/ReactNative( 7776): ReactInstanceManager.ctor()
D/SoLoader( 7776): init exiting
D/ReactNative( 7776): ReactInstanceManager.createReactContextInBackground()
D/ReactNative( 7776): ReactInstanceManager.recreateReactContextInBackgroundInner()
D/ReactNative( 7776): ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
D/ReactNative( 7776): ReactInstanceManager.recreateReactContextInBackground()
D/ReactNative( 7776): ReactInstanceManager.runCreateReactContextOnNewThread()
D/SoLoader( 7776): About to load: libreactnativejni.so
D/SoLoader( 7776): libreactnativejni.so found on /data/user/0/com.teksun.ichjitsi/lib-main
D/SoLoader( 7776): Loading lib dependencies: [libglog_init.so, libyoga.so, libfb.so, libjsinspector.so, libfolly_json.so, libglog.so, libc++_shared.so, libandroid.so, liblog.so, libc.so, libm.so, libdl.so]
D/SoLoader( 7776): About to load: libglog_init.so
D/SoLoader( 7776): libglog_init.so found on /data/user/0/com.teksun.ichjitsi/lib-main
D/SoLoader( 7776): Loading lib dependencies: [libglog.so, libc++_shared.so, liblog.so, libc.so, libm.so, libdl.so]
D/SoLoader( 7776): About to load: libglog.so
D/SoLoader( 7776): libglog.so found on /data/user/0/com.teksun.ichjitsi/lib-main
D/SoLoader( 7776): Loading lib dependencies: [libc++_shared.so, libc.so, libm.so, libdl.so]
D/SoLoader( 7776): About to load: libc++_shared.so
D/SoLoader( 7776): libc++_shared.so found on /data/user/0/com.teksun.ichjitsi/lib-main
D/SoLoader( 7776): Loading lib dependencies: [libc.so, libdl.so]
D/SoLoader( 7776): About to load: libc.so
D/SoLoader( 7776): libc.so not found on /data/user/0/com.teksun.ichjitsi/lib-main
D/SoLoader( 7776): libc.so not found on /data/app/~~Yz9uSeNN8HRjscxqglA9iA==/com.teksun.ichjitsi-dRl_hKiFdsd_xJz2U667Gg==/lib/x86_64
D/SoLoader( 7776): libc.so not found on /vendor/lib
D/SoLoader( 7776): libc.so not found on /system/lib 

Thanks in advance for your help.

**Comment by saibotma** [comment]
I created a rewrite of this package. It should support Android 12: https://pub.dev/packages/jitsi_meet_wrapper

**Comment by Meri994** [comment]
@saibotma Thanks for the library. I have checked in and it's working on Pixel XL API 31. It has saved me lots of time. Thanks again.

 I am also getting logs for when any participants join, left, or any message arrives in the meeting. 
 Here is the logs for that:
 
 ```
 D/JitsiMeetSDK( 7218): ExternalAPI Sending event: PARTICIPANT_LEFT with data: { NativeMap: {"participantId":"515e6b41"} }
D/JitsiMeetSDK( 7218): ExternalAPI Sending event: CHAT_MESSAGE_RECEIVED with data: { NativeMap: {"senderId":"83409ad1","isPrivate":false,"message":"yes please"} }
D/JitsiMeetSDK( 7218): ExternalAPI Sending event: PARTICIPANT_JOINED with data: { NativeMap: {"name":"tester meri","participantId":"cbc8a823","role":"moderator"} }
```
Are there any methods available for getting all these longs in your flutter example project? I like to store meetings and participants' data in my application. It will be great if you find it. Thank you.
