### ISSUE TITLE
Type mismatch: inferred type is Activity? but Activity was expected

### ISSUE THREAD

**Issue by elirehema** [gunschu/jitsi_meet#385]
**jitsi_meet plugin version**

jitsi_meet:4.0.0

**Describe the bug**

The error appeared immediately after upgrading to flutter version 3.0

**To Reproduce**

**Screenshots**

![image](https://user-images.githubusercontent.com/29277048/168441804-ad0644a5-6c21-4684-84bd-3b3f9200b167.png)

**Flutter doctor -v**

![image](https://user-images.githubusercontent.com/29277048/168441853-1302d977-9c25-4d85-aca5-562d123c3a13.png)

**Web (please complete the following information):**
 - OS: [e.g. Mac, Windows, Linux]

**Smartphone (please complete the following information):**
 - Device: Android
 - Emulator
 - OS: 
 - Version 23

**Additional context**

**Error Logs**

```                  ^
e: /home/eli/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt: (66, 42): Type mismatch: inferred type is Activity? but Activity was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jitsi_meet:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

````

**Comment by dispersik** [comment]
same

**Comment by umairshah143** [comment]
Same

**Comment by umairshah143** [comment]
Please fix it as fast as possible

**Comment by wh120** [comment]
Same

**Comment by Ali-ite** [comment]
Same

**Comment by dispersik** [comment]
```
jitsi_meet:
    git:
      url: https://github.com/dispersik/jitsi_meet_fork
      ref: master
```

Let me know if that works for you

I've fixed compile time error, but I'm not sure about other stuff

**Comment by elirehema** [comment]
> ```
> jitsi_meet:
>     git:
>       url: https://github.com/dispersik/jitsi_meet_fork
>       ref: master
> ```
> 
> Let me know if that works for you
> 
> I've fixed compile time error, but I'm not sure about other stuff

It works. I just tested with `flutter run` and works fine. Hope  @gunschu will fix this

**Comment by elirehema** [comment]
> ```
> jitsi_meet:
>     git:
>       url: https://github.com/dispersik/jitsi_meet_fork
>       ref: master
> ```
> 
> Let me know if that works for you
> 
> I've fixed compile time error, but I'm not sure about other stuff

It works. I just tested with `flutter run` and works fine. Hope  @gunschu will fix this

**Comment by elirehema** [comment]
> ```
> jitsi_meet:
>     git:
>       url: https://github.com/dispersik/jitsi_meet_fork
>       ref: master
> ```
> 
> Let me know if that works for you
> 
> I've fixed compile time error, but I'm not sure about other stuff

It works. I just tested with `flutter run` and works fine. Hope  @gunschu will fix this

**Comment by elirehema** [comment]
> ```
> jitsi_meet:
>     git:
>       url: https://github.com/dispersik/jitsi_meet_fork
>       ref: master
> ```
> 
> Let me know if that works for you
> 
> I've fixed compile time error, but I'm not sure about other stuff

It works. I just tested with `flutter run` and works fine. Hope  @gunschu will fix this

**Comment by elirehema** [comment]
> ```
> jitsi_meet:
>     git:
>       url: https://github.com/dispersik/jitsi_meet_fork
>       ref: master
> ```
> 
> Let me know if that works for you
> 
> I've fixed compile time error, but I'm not sure about other stuff

It works. I just tested with `flutter run` and works fine. Hope  @gunschu will fix this

**Comment by umairshah143** [comment]
Not Fixed for the latest version of flutter. Flutter 3.00 showing this error and not fixed till now
Please Fix it

**Comment by wh120** [comment]
> ```
> jitsi_meet:
>     git:
>       url: https://github.com/dispersik/jitsi_meet_fork
>       ref: master
> ```
> 
> Let me know if that works for you
> 
> I've fixed compile time error, but I'm not sure about other stuff

It's work only for flutter run , and not work in flutter build apk

**Comment by dispersik** [comment]
` Flutter (Channel stable, 3.0.0, on macOS 12.2.1 21D62 darwin-arm, locale en-DE)
    • Flutter version 3.0.0 at /Users/user/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
`

works for me

**Comment by anirudhrao-github** [comment]
@gunschu. Please fix this issue

**Comment by wh120** [comment]
same

**Comment by wh120** [comment]
I used https://pub.dev/packages/jitsi_meet_wrapper and worked for me

**Comment by bhattabhi013** [comment]
I think this issue is still not fixed.
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/47862474/185172486-fb24632e-3a9d-45ec-9e11-1cfbc1d0a1af.png">

**Comment by RohanSengupta326** [comment]
> ```
> jitsi_meet:
>     git:
>       url: https://github.com/dispersik/jitsi_meet_fork
>       ref: master
> ```
> 
> Let me know if that works for you
> 
> I've fixed compile time error, but I'm not sure about other stuff

This solved the issue.

**Comment by bhattabhi013** [comment]
> > ```
> > jitsi_meet:
> >     git:
> >       url: https://github.com/dispersik/jitsi_meet_fork
> >       ref: master
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know if that works for you
> > I've fixed compile time error, but I'm not sure about other stuff
> 
> This solved the issue.

Thanks @RohanSengupta326 , this solves it.

**Comment by rwbr** [comment]
Why isn't any of the maintainers of the package able to include it in their code?

**Comment by brutev** [comment]
issue still exist !!
