### ISSUE TITLE
Mismatch Data type in kotlin -> JitsiMeetPlugin.kt: (66, 42) 

### ISSUE THREAD

**Issue by ctkqiang** [gunschu/jitsi_meet#393]
**jitsi_meet plugin version**
jitmi_meet:4.0.0

**Describe the bug**
the code return 
```
jitsi_meet-4.0.0\android\src\main\kotlin\com\gunschu\jitsi_meet\JitsiMeetPlugin.kt: (32, 38): Null can not be a value of a non-null type Activity
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\jitsi_meet-4.0.0\andr

```

suspect that the error caused by 
```
    private var activity: Activity? = null
```

@jimmyjose-dev @rwbr @mosleim @buzzwin @agfeo

**Comment by ctkqiang** [comment]
Error: 
```
JitsiMeetPlugin.kt C:\src\flutter.pub-cache\hosted\pub.dartlang.org\
jitsi_meet-4.0.0\android\src\main\kotlin\com\gunschu\jitsi_meet\
JitsiMeetPlugin.kt: (66, 42): 
Type mismatch: inferred type is Activity? but Activity was expected
```

Problem : 

https://github.com/gunschu/jitsi_meet/blob/97154d582969af1155489bd066d280d85054e5c7/jitsi_meet/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt#L34

Solved it by 

```kotlin
constructor(activity: Activity?) : this() {
        this.activity = activity
}
```

**Comment by arcechava** [comment]
Thanks !!!

**Comment by anonnothing** [comment]
> Error: 
> ```
> JitsiMeetPlugin.kt C:\src\flutter.pub-cache\hosted\pub.dartlang.org\
> jitsi_meet-4.0.0\android\src\main\kotlin\com\gunschu\jitsi_meet\
> JitsiMeetPlugin.kt: (66, 42): 
> Type mismatch: inferred type is Activity? but Activity was expected
> ```
> 
> Problem : 
> 
> https://github.com/gunschu/jitsi_meet/blob/97154d582969af1155489bd066d280d85054e5c7/jitsi_meet/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt#L34
> 
> Solved it by 
> 
> ```kotlin
> constructor(activity: Activity?) : this() {
>         this.activity = activity
> }
> ```
> 

You saved my life. 💪👍

**Comment by rwbr** [comment]
It's nice, that you could solve this problem. So what does hold you back publishing a corrected version of that package?

**Comment by ctkqiang** [comment]
> It's nice, that you could solve this problem. So what does hold you back publishing a corrected version of that package?

Permission. I don't have the permission yet.
