### ISSUE TITLE
[BUG]: ANDROID: When user is initiate or Accept Call from Android device the App Crashes

### ISSUE THREAD

**Issue by gajanan-shinde-godeskless** [gunschu/jitsi_meet#399]
**jitsi_meet plugin version**
 jitsi_meet: 4.0.0

**Describe the bug**
When user is initiate or Accept Call from Android device the App Crashes

**To Reproduce**
1.in android app click to initiate call
2. app crashed
and
1.When i call from ios with same code it works
2.i try to call from ios to android
3.accept the call in android app crashed

**Screenshots**

**Flutter doctor -v**

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-arm, locale
    en-US)
    • Flutter version 2.10.4 at /Users/godeskless/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/godeskless/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 13 mini (mobile)     • 31A06A0D-FD68-44C5-9D43-F423B31CCFF9 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Web (please complete the following information):**
 - OS: Mac

**Smartphone (please complete the following information):**
 - Device: [e.g. any Android device]
 - Physical or Emulator
 - OS: [11]

**Additional context**

**Error Logs**

/JitsiMeetSDK( 5626): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK( 5626): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.abc.xyz/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK( 5626): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3639)
E/JitsiMeetSDK( 5626): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3796)
E/JitsiMeetSDK( 5626): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/JitsiMeetSDK( 5626): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK( 5626): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK( 5626): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
E/JitsiMeetSDK( 5626): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK( 5626): 	at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK( 5626): 	at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK( 5626): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/JitsiMeetSDK( 5626): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 5626): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK( 5626): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/JitsiMeetSDK( 5626): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK( 5626): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
E/JitsiMeetSDK( 5626): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
E/JitsiMeetSDK( 5626): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
E/JitsiMeetSDK( 5626): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/JitsiMeetSDK( 5626): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:93)
E/JitsiMeetSDK( 5626): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/JitsiMeetSDK( 5626): 	at android.app.Activity.performCreate(Activity.java:8051)
E/JitsiMeetSDK( 5626): 	at android.app.Activity.performCreate(Activity.java:8031)
E/JitsiMeetSDK( 5626): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
E/JitsiMeetSDK( 5626): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3612)
E/JitsiMeetSDK( 5626): 	... 12 more
E/JitsiMeetSDK( 5626): 
E/JitsiMeetSDK( 5626): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.audetemi.trackhelp/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK( 5626): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3639)
E/JitsiMeetSDK( 5626): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3796)
E/JitsiMeetSDK( 5626): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/JitsiMeetSDK( 5626): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK( 5626): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK( 5626): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
E/JitsiMeetSDK( 5626): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK( 5626): 	at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK( 5626): 	at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK( 5626): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/JitsiMeetSDK( 5626): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 5626): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK( 5626): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/JitsiMeetSDK( 5626): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK( 5626): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
E/JitsiMeetSDK( 5626): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
E/JitsiMeetSDK( 5626): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
E/JitsiMeetSDK( 5626): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/JitsiMeetSDK( 5626): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:93)
E/JitsiMeetSDK( 5626): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/JitsiMeetSDK( 5626): 	at android.app.Activity.performCreate(Activity.java:8051)
E/JitsiMeetSDK( 5626): 	at android.app.Activity.performCreate(Activity.java:8031)
E/JitsiMeetSDK( 5626): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
E/JitsiMeetSDK( 5626): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3612)
E/JitsiMeetSDK( 5626): 	... 12 more
I/Process ( 5626): Sending signal. PID: 5626 SIG: 9
Lost connection to device.

**Comment by Gokulkannan08** [comment]
same issue
