### ISSUE TITLE
Stratup Android Error: Execution failed for task ':jitsi_meet:compileDebugKotlin'.

### ISSUE THREAD

**Issue by litzbalane2017** [gunschu/jitsi_meet#4]
Good Day.

First off, thank you for this plugin. I have been waiting to implement Jitsi on flutter. I encounter this error on startup for android.

I have the following flutter doctor:

[✓] Flutter (Channel dev, v1.14.6, on Linux, locale en_PH.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.2)
[✓] IntelliJ IDEA Community Edition (version 2019.3)

Please see the error logs:

username.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.1.1/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt: (19, 11): Conflicting declarations: public const val TAG: String, public const val TAG: String
username.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.1.1/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt: (22, 14): Redeclaration: JitsiMeetPlugin
username.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.1.1/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt: (58, 15): Overload resolution ambiguity: 
public const val TAG: String defined in com.gunschu.jitsi_meet in file JitsiMeetPlugin.kt
public const val TAG: String defined in com.gunschu.jitsi_meet in file JitsiMeetPlugin.kt
username.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.1.1/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt: (59, 15): Overload resolution ambiguity: 
public const val TAG: String defined in com.gunschu.jitsi_meet in file JitsiMeetPlugin.kt
public const val TAG: String defined in com.gunschu.jitsi_meet in file JitsiMeetPlugin.kt
username.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.1.1/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt: (86, 15): Overload resolution ambiguity: 
public const val TAG: String defined in com.gunschu.jitsi_meet in file JitsiMeetPlugin.kt
public const val TAG: String defined in com.gunschu.jitsi_meet in file JitsiMeetPlugin.kt
username.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.1.3/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt: (19, 11): Conflicting declarations: public const val TAG: String, public const val TAG: String
username.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.1.3/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt: (22, 14): Redeclaration: JitsiMeetPlugin
username.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.1.3/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt: (58, 15): Overload resolution ambiguity: 
public const val TAG: String defined in com.gunschu.jitsi_meet in file JitsiMeetPlugin.kt
public const val TAG: String defined in com.gunschu.jitsi_meet in file JitsiMeetPlugin.kt
username.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.1.3/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt: (59, 15): Overload resolution ambiguity: 
public const val TAG: String defined in com.gunschu.jitsi_meet in file JitsiMeetPlugin.kt
public const val TAG: String defined in com.gunschu.jitsi_meet in file JitsiMeetPlugin.kt
username.pub-cache/hosted/pub.dartlang.org/jitsi_meet-0.1.3/android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPlugin.kt: (86, 15): Overload resolution ambiguity: 
public const val TAG: String defined in com.gunschu.jitsi_meet in file JitsiMeetPlugin.kt
public const val TAG: String defined in com.gunschu.jitsi_meet in file JitsiMeetPlugin.kt

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jitsi_meet:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Finished with error: Gradle task assembleDebug failed with exit code 1

Thank you.

**Comment by tuantvu** [comment]
Im wondering if you have customized your Android app in flutter and have any constants in called TAG already? If not, maybe it's a conflict with another package you've pulled in (maybe list packages you pull in if you haven't customized your Android app)? I'm asking to see how to recreate. Thanks

**Comment by litzbalane2017** [comment]
I think the issue was because I tried installing Jitsi before with the following entries:

maven {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }

implementation ('org.jitsi.react:jitsi-meet-sdk:2.+') { transitive = true }

In addition, before the required minSDK is 21, but now its minSDK 24.

Thank you. Will be trying the plugin out today.

**Comment by tuantvu** [comment]
I'm new to Kotlin and apparently I put the TAG outside of the class, so it's a global variable with no namespace. TAG is a very generic term that I'm sure some one else has made the same mistake as me in another package. I'll be making a change and updating our version in a bit, so there's no chance of conflict in the future.

**Comment by tuantvu** [comment]
version 0.1.4 is out. try that out.

**Comment by litzbalane2017** [comment]
I can confirm that I am not encountering this error anymore. Thank you.
