### ISSUE TITLE
Application closes when starting a call

### ISSUE THREAD

**Issue by Lucas15andrade** [gunschu/jitsi_meet#40]
I have a problem when starting a call on IOS, the application simply closes. On Android the same code works normally. Has anyone been through this or have any idea how to solve it?

There is no exception.

**Comment by Lucas15andrade** [comment]
I can only start a call when audioOnly, audioMuted and videoMuted are set to true. However, after starting the call when enabling / disabling audio or video, the application continues to close unexpectedly without any error.

This problem only happens on iOS.

**Comment by LucasManerich** [comment]
Add NSCameraUsageDescription and NSMicrophoneUsageDescription permissions to your info.plist

**Comment by Lucas15andrade** [comment]
That was the problem, thank you very much. You should have more information about the iOS configuration in the readme.

**Comment by tuantvu** [comment]
Thanks for the suggestion. I've committed to the README. Will update with the next publish.
