### ISSUE TITLE
Manifest merger failed : android:exported needs to be explicitly specified for element <service#org.jitsi.meet.sdk.ConnectionService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. 

### ISSUE THREAD

**Issue by DangHung301** [gunschu/jitsi_meet#409]
Platform: Android

 
I have installed the lib then config into the app but can't run it due to this problem

![image](https://user-images.githubusercontent.com/72400210/196578531-4647fe2b-d95f-4fc6-9284-1615c1d1ffb0.png)

**Comment by osamasaeed** [comment]
I tried this package first but I am facing same issue above.

**Comment by denes16** [comment]
same here, any workaround?

**Comment by ghost** [comment]
same  issue but it does work on the ios its only not working for android

**Comment by isnaenimus** [comment]
Have you added in manifest **android:exported="true"**?

and try this

    <service
           android:name="org.jitsi.meet.sdk.ConnectionService"
           android:permission="android.permission.BIND_TELECOM_CONNECTION_SERVICE"
           android:exported="true">
           <intent-filter>
               <action android:name="android.telecom.ConnectionService" />
           </intent-filter>
    </service>
