### ISSUE TITLE
[BUG]: App build failed due to jitsi artifacts not downloading 

### ISSUE THREAD

**Issue by Yogesh-333** [gunschu/jitsi_meet#410]
**jitsi_meet plugin version**
jitsi_meet: ^4.0.0

**Describe the bug**
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.jitsi.react:jitsi-meet-sdk:5.1.0.
     Required by:
         project :app > project :jitsi_meet
      > Could not resolve org.jitsi.react:jitsi-meet-sdk:5.1.0.
         > Could not get resource 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/5.1.0/jitsi-meet-sdk-5.1.0.pom'.
            > Could not HEAD 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/5.1.0/jitsi-meet-sdk-5.1.0.pom'.
               > Read timed out

**To Reproduce**

**Screenshots**

**Flutter doctor -v**

**Web (please complete the following information):**
 - OS: [e.g. Mac, Windows, Linux]

**Smartphone (please complete the following information):**
 - Physical or Emulator

**Additional context**

**Error Logs**

**Comment by saravananravi08** [comment]
> **jitsi_meet plugin version** jitsi_meet: ^4.0.0
> 
> **Describe the bug** FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:checkDebugAarMetadata'.
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Could not resolve org.jitsi.react:jitsi-meet-sdk:5.1.0.
> > Required by:
> > project :app > project :jitsi_meet
> > > Could not resolve org.jitsi.react:jitsi-meet-sdk:5.1.0.
> > > Could not get resource 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/5.1.0/jitsi-meet-sdk-5.1.0.pom'.
> > > Could not HEAD 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/5.1.0/jitsi-meet-sdk-5.1.0.pom'.
> > > Read timed out
> 
> **To Reproduce**
> 
> **Screenshots**
> 
> **Flutter doctor -v**
> 
> **Web (please complete the following information):**
> 
> * OS: [e.g. Mac, Windows, Linux]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * Physical or Emulator
> * OS: [e.g. iOS8.1]
> * Version [e.g. 22]
> 
> **Additional context**
> 
> **Error Logs**
