### ISSUE TITLE
App crashes while joining meeting

### ISSUE THREAD

**Issue by Gokulkannan08** [gunschu/jitsi_meet#418]
**jitsi_meet plugin version**

**Describe the bug**

**To Reproduce**

**Screenshots**

**Flutter doctor -v**

**Web (please complete the following information):**
 - OS: [e.g. Mac, Windows, Linux]

**Smartphone (please complete the following information):**
 - Physical or Emulator

**Additional context**

**Error Logs**

**Comment by NifalNizar** [comment]
I'm also facing the same issue, but this is only happening in Android 12.

**Comment by e-SAME** [comment]
* verify if participant have the autorization to enter in this meeting
* Test with other phone
* test with real device

**Comment by Joseph-Nathan** [comment]
I'm also facing the same issue, but this is only happening in Android 12 ?
any news ?

**Comment by e-SAME** [comment]
yes i have the same issue too... but any update
