### ISSUE TITLE
[BUG] Flutter, I can't make a call using android 13

### ISSUE THREAD

**Issue by thaliachitziou99** [gunschu/jitsi_meet#426]
I am using an emulator with api level 33 and I get this error
```
java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@79699cd with Intent { act=JitsiMeetOngoingConferenceService:START cmp=eu.test/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService }: java.lang.IllegalArgumentException: eu.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/JitsiMeetSDK( 8357): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```
Can anyone help me?

**Comment by Joseph-Nathan** [comment]
how can we handle this ?

**Comment by MuksithMRA** [comment]
> I am using an emulator with api level 33 and I get this error
> 
> ```
> java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@79699cd with Intent { act=JitsiMeetOngoingConferenceService:START cmp=eu.test/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService }: java.lang.IllegalArgumentException: eu.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
> E/JitsiMeetSDK( 8357): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
> ```
> 
> Can anyone help me?

add this two lines  inside  dependencies  in /android/app/build.gradle   

    implementation 'androidx.work:work-runtime:2.7.1'
    implementation 'androidx.work:work-runtime-ktx:2.7.1'

**Comment by subhra9326** [comment]
I have added these two lines but still, no luck is there any alternative option?

**Comment by thaliachitziou99** [comment]
I added the following line to the file app\build.gradle on dependencies and it worked for me

`implementation ('org.jitsi.react:jitsi-meet-sdk:3.10.2') { transitive = true }`

**Comment by subhra9326** [comment]
> I added the following line to the file app\build.gradle on dependencies and it worked for me
> 
> `implementation ('org.jitsi.react:jitsi-meet-sdk:3.10.2') { transitive = true }`

Thanks for the help, it saves me a lot of time. Problem fixed.
