### ISSUE TITLE
After upgrading from build.gradle 3.6.3 to 7.1.2, I get "Lost connection to device." when joining meeting

### ISSUE THREAD

**Issue by mosta95** [gunschu/jitsi_meet#427]
**jitsi_meet plugin version**

**Describe the bug**
After upgrading from build.gradle 3.6.3 to 7.1.2, I get "Lost connection to device." when joining meeting

**To Reproduce**
<!-- 
1. Isstalled jitsi_meet
2. JoinMeeting
3. Lost connection to device

**Smartphone (please complete the following information):**
 - Device: Pixel 5 API 33, Redmi 9 Pro, Oppo A54
 - Emulator, Physical and Physical

**Error Logs**
D/JITSI_MEET_PLUGIN(18519): method: joinMeeting
D/JITSI_MEET_PLUGIN(18519): arguments: {videoMuted=true, subject=null, iosAppBarRGBAColor=null, serverURL=null, audioOnly=null, audioMuted=true, userDisplayName=dd, userEmail=tino@gmail.com, room=A1fManqTTzeZppazumz2ojEobAA3QG0D7QYa49dgc35KVukLUmvlqkN2, token=null, featureFlags={}}
D/JITSI_MEET_PLUGIN(18519): Joining Room: A1fManqTTzeZppazumz2ojEobAA3QG0D7QYa49dgc35KVukLUmvlqkN2
D/JITSI_MEET_PLUGIN(18519): Server URL: https://meet.jit.si, https://meet.jit.si
D/OrientationModule(18519): onActivityPaused
D/OrientationModule(18519): onActivityCreated
W/.mostastudy_app(18519): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
W/.mostastudy_app(18519): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
D/CompatibilityChangeReporter(18519): Compat change id reported: 210923482; UID 10158; state: DISABLED
D/CompatibilityChangeReporter(18519): Compat change id reported: 37756858; UID 10158; state: ENABLED
D/org.jitsi.meet.sdk.ReactInstanceManagerHolder(18519): initializing RN with Activity
D/AndroidRuntime(18519): Shutting down VM
E/AndroidRuntime(18519): FATAL EXCEPTION: main
E/AndroidRuntime(18519): Process: com.example.mostastudy_app, PID: 18519
E/AndroidRuntime(18519): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mostastudy_app/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: android.view.InflateException: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/AndroidRuntime(18519):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
E/AndroidRuntime(18519):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/AndroidRuntime(18519):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime(18519):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(18519):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(18519):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/AndroidRuntime(18519):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(18519):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(18519):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(18519):        at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(18519):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18519):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(18519):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(18519): Caused by: android.view.InflateException: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/AndroidRuntime(18519): Caused by: android.view.InflateException: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView  
E/AndroidRuntime(18519): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(18519):        at java.lang.reflect.Constructor.newInstance0(Native Method)
E/AndroidRuntime(18519):        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/AndroidRuntime(18519):        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
E/AndroidRuntime(18519):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
E/AndroidRuntime(18519):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
E/AndroidRuntime(18519):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
E/AndroidRuntime(18519):        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/AndroidRuntime(18519):        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
E/AndroidRuntime(18519):        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
E/AndroidRuntime(18519):        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
E/AndroidRuntime(18519):        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:710)
E/AndroidRuntime(18519):        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/AndroidRuntime(18519):        at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:102)
E/AndroidRuntime(18519):        at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/AndroidRuntime(18519):        at android.app.Activity.performCreate(Activity.java:8290)
E/AndroidRuntime(18519):        at android.app.Activity.performCreate(Activity.java:8269)
E/AndroidRuntime(18519):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
E/AndroidRuntime(18519):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
E/AndroidRuntime(18519):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/AndroidRuntime(18519):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime(18519):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(18519):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(18519):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/AndroidRuntime(18519):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(18519):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(18519):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(18519):        at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(18519):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18519):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(18519):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(18519): Caused by: java.lang.VerifyError: Verifier rejected class com.facebook.react.uimanager.DisplayMetricsHolder: com.facebook.react.bridge.WritableMap com.facebook.react.uimanager.DisplayMetricsHolder.getDisplayMetricsWritableMap(double) failed to verify: com.facebook.react.bridge.WritableMap com.facebook.react.uimanager.DisplayMetricsHolder.getDisplayMetricsWritableMap(double): [0x1E] register v1 has type Reference: com.facebook.react.bridge.WritableMap but expected Reference: com.facebook.react.bridge.ReadableMap (declaration of 'com.facebook.react.uimanager.DisplayMetricsHolder' appears in /data/app/~~-kZJjV0zxyFlwxAPxPzxTA==/com.example.mostastudy_app-nmGlqnPCIJIwLITCQp88ow==/base.apk!classes21.dex)
E/AndroidRuntime(18519):        at com.facebook.react.uimanager.DisplayMetricsHolder.initDisplayMetricsIfNotInitialized(DisplayMetricsHolder.java:41)
E/AndroidRuntime(18519):        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:245)
E/AndroidRuntime(18519):        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:358)
E/AndroidRuntime(18519):        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:298)
E/AndroidRuntime(18519):        at org.jitsi.meet.sdk.JitsiMeetView.initialize(JitsiMeetView.java:192)
E/AndroidRuntime(18519):        at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:101)
E/AndroidRuntime(18519):        ... 30 more
E/JitsiMeetSDK(18519): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK(18519): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mostastudy_app/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: android.view.InflateException: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/JitsiMeetSDK(18519):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/JitsiMeetSDK(18519):  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/JitsiMeetSDK(18519):  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(18519):  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/JitsiMeetSDK(18519):  at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(18519):  at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK(18519):  at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread.main(ActivityThread.java:7898)
E/JitsiMeetSDK(18519):  at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(18519):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK(18519):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/JitsiMeetSDK(18519): Caused by: android.view.InflateException: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/JitsiMeetSDK(18519): Caused by: android.view.InflateException: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView    
E/JitsiMeetSDK(18519): Caused by: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK(18519):  at java.lang.reflect.Constructor.newInstance0(Native Method)
E/JitsiMeetSDK(18519):  at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.createView(LayoutInflater.java:858)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
E/JitsiMeetSDK(18519):  at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:710)
E/JitsiMeetSDK(18519):  at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/JitsiMeetSDK(18519):  at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:102)
E/JitsiMeetSDK(18519):  at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/JitsiMeetSDK(18519):  at android.app.Activity.performCreate(Activity.java:8290)
E/JitsiMeetSDK(18519):  at android.app.Activity.performCreate(Activity.java:8269)
E/JitsiMeetSDK(18519):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/JitsiMeetSDK(18519):  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/JitsiMeetSDK(18519):  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(18519):  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/JitsiMeetSDK(18519):  at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(18519):  at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK(18519):  at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread.main(ActivityThread.java:7898)
E/JitsiMeetSDK(18519):  at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(18519):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK(18519):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/JitsiMeetSDK(18519): Caused by: java.lang.VerifyError: Verifier rejected class com.facebook.react.uimanager.DisplayMetricsHolder: com.facebook.react.bridge.WritableMap com.facebook.react.uimanager.DisplayMetricsHolder.getDisplayMetricsWritableMap(double) failed to verify: com.facebook.react.bridge.WritableMap com.facebook.react.uimanager.DisplayMetricsHolder.getDisplayMetricsWritableMap(double): [0x1E] register v1 has type Reference: com.facebook.react.bridge.WritableMap but expected Reference: com.facebook.react.bridge.ReadableMap (declaration of 'com.facebook.react.uimanager.DisplayMetricsHolder' appears in /data/app/~~-kZJjV0zxyFlwxAPxPzxTA==/com.example.mostastudy_app-nmGlqnPCIJIwLITCQp88ow==/base.apk!classes21.dex)
E/JitsiMeetSDK(18519):  at com.facebook.react.uimanager.DisplayMetricsHolder.initDisplayMetricsIfNotInitialized(DisplayMetricsHolder.java:41)
E/JitsiMeetSDK(18519):  at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:245)
E/JitsiMeetSDK(18519):  at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:358)
E/JitsiMeetSDK(18519):  at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:298)
E/JitsiMeetSDK(18519):  at org.jitsi.meet.sdk.JitsiMeetView.initialize(JitsiMeetView.java:192)
E/JitsiMeetSDK(18519):  at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:101)
E/JitsiMeetSDK(18519):  ... 30 more
E/JitsiMeetSDK(18519):
E/JitsiMeetSDK(18519): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mostastudy_app/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: android.view.InflateException: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/JitsiMeetSDK(18519):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/JitsiMeetSDK(18519):  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/JitsiMeetSDK(18519):  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(18519):  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/JitsiMeetSDK(18519):  at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(18519):  at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK(18519):  at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread.main(ActivityThread.java:7898)
E/JitsiMeetSDK(18519):  at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(18519):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK(18519):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/JitsiMeetSDK(18519): Caused by: android.view.InflateException: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/JitsiMeetSDK(18519): Caused by: android.view.InflateException: Binary XML file line #9 in com.example.mostastudy_app:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView    
E/JitsiMeetSDK(18519): Caused by: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK(18519):  at java.lang.reflect.Constructor.newInstance0(Native Method)
E/JitsiMeetSDK(18519):  at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.createView(LayoutInflater.java:858)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
E/JitsiMeetSDK(18519):  at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
E/JitsiMeetSDK(18519):  at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:710)
E/JitsiMeetSDK(18519):  at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/JitsiMeetSDK(18519):  at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:102)
E/JitsiMeetSDK(18519):  at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/JitsiMeetSDK(18519):  at android.app.Activity.performCreate(Activity.java:8290)
E/JitsiMeetSDK(18519):  at android.app.Activity.performCreate(Activity.java:8269)
E/JitsiMeetSDK(18519):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/JitsiMeetSDK(18519):  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/JitsiMeetSDK(18519):  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(18519):  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/JitsiMeetSDK(18519):  at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(18519):  at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK(18519):  at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK(18519):  at android.app.ActivityThread.main(ActivityThread.java:7898)
E/JitsiMeetSDK(18519):  at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(18519):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK(18519):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/JitsiMeetSDK(18519): Caused by: java.lang.VerifyError: Verifier rejected class com.facebook.react.uimanager.DisplayMetricsHolder: com.facebook.react.bridge.WritableMap com.facebook.react.uimanager.DisplayMetricsHolder.getDisplayMetricsWritableMap(double) failed to verify: com.facebook.react.bridge.WritableMap com.facebook.react.uimanager.DisplayMetricsHolder.getDisplayMetricsWritableMap(double): [0x1E] register v1 has type Reference: com.facebook.react.bridge.WritableMap but expected Reference: com.facebook.react.bridge.ReadableMap (declaration of 'com.facebook.react.uimanager.DisplayMetricsHolder' appears in /data/app/~~-kZJjV0zxyFlwxAPxPzxTA==/com.example.mostastudy_app-nmGlqnPCIJIwLITCQp88ow==/base.apk!classes21.dex)
E/JitsiMeetSDK(18519):  at com.facebook.react.uimanager.DisplayMetricsHolder.initDisplayMetricsIfNotInitialized(DisplayMetricsHolder.java:41)
E/JitsiMeetSDK(18519):  at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:245)
E/JitsiMeetSDK(18519):  at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:358)
E/JitsiMeetSDK(18519):  at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:298)
E/JitsiMeetSDK(18519):  at org.jitsi.meet.sdk.JitsiMeetView.initialize(JitsiMeetView.java:192)
E/JitsiMeetSDK(18519):  at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:101)
E/JitsiMeetSDK(18519):  ... 30 more
D/EGL_emulation(18519): app_time_stats: avg=25.46ms min=12.36ms max=91.53ms count=40
D/EGL_emulation(18519): app_time_stats: avg=18.81ms min=10.93ms max=38.96ms count=54
D/EGL_emulation(18519): app_time_stats: avg=16.93ms min=12.52ms max=25.55ms count=60
W/GmsClient(18519): IGmsServiceBroker.getService failed
W/GmsClient(18519): android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
W/GmsClient(18519):     at android.os.BinderProxy.transactNative(Native Method)
W/GmsClient(18519):     at android.os.BinderProxy.transact(BinderProxy.java:584)
W/GmsClient(18519):     at WE.b(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:288)
W/GmsClient(18519):     at com.google.android.gms.common.internal.BaseGmsClient.p(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:53)
W/GmsClient(18519):     at BB.run(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:1849)
W/GmsClient(18519):     at android.os.Handler.handleCallback(Handler.java:942)
W/GmsClient(18519):     at android.os.Handler.dispatchMessage(Handler.java:99)
W/GmsClient(18519):     at Sp0.dispatchMessage(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:223)
E/JavaBinder(18519): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 336)
W/GmsClient(18519): IGmsServiceBroker.getService failed
W/GmsClient(18519): android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
W/GmsClient(18519):     at android.os.BinderProxy.transactNative(Native Method)
W/GmsClient(18519):     at android.os.BinderProxy.transact(BinderProxy.java:584)
W/GmsClient(18519):     at WE.b(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:288)
W/GmsClient(18519):     at com.google.android.gms.common.internal.BaseGmsClient.p(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:53)
W/GmsClient(18519):     at BB.run(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:1849)
W/GmsClient(18519):     at android.os.Handler.handleCallback(Handler.java:942)
W/GmsClient(18519):     at android.os.Handler.dispatchMessage(Handler.java:99)
W/GmsClient(18519):     at Sp0.dispatchMessage(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:223)
W/GmsClient(18519):     at android.os.Looper.loopOnce(Looper.java:201)
W/GmsClient(18519):     at android.os.Looper.loop(Looper.java:288)
W/GmsClient(18519):     at android.os.HandlerThread.run(HandlerThread.java:67)
D/EGL_emulation(18519): app_time_stats: avg=7.46ms min=2.09ms max=38.75ms count=61
Lost connection to device.

**Comment by ndizihiwesimon** [comment]
Anyone who managed to fix this? app closes immediately when user tries to join
