### ISSUE TITLE
Any type of video communication is not working(eg: Video, youtube sharing, screen sharing, whiteboard)

### ISSUE THREAD

**Issue by KumarOrohit** [gunschu/jitsi_meet#429]
**jitsi_meet plugin version**
 jitsi_meet: 4.0.0

**Describe the bug**
I have followed the documentation and my app is working pretty fine on android in case of voice. But when  i turn my video on it's visible to me but not other users. Same case for screen sharing or youtube sharing, visible to but not others. Even others video is not visible to me. Same case for screen sharing, withboard or any video streaming.

**To Reproduce**
I'm using 
compile sdk 31 
target sdk 30
minSdkVersion 24

com.android.tools.build:gradle:4.1.0

tried running on 10 - 12 android version. It's same.

Even logs seems to be working fine.

Please help me to resolve this. My app is in production.

**Comment by Arjun3492** [comment]
Any update regarding the bug?

**Comment by kcibdev** [comment]
Have you fixed it?

**Comment by KumarOrohit** [comment]
> Have you fixed it?

no i switched to another app
