### ISSUE TITLE
Need Min SDK 24 When Code set to Min SDK 21

### ISSUE THREAD

**Issue by chandrabezzo** [gunschu/jitsi_meet#43]
I was send pull request to min SDK 21, when I use this library from my github it's can min SDK 21, but, when I choose to this library from this repository min SDK 24. My code was merged to this repository but not working in min SDK 21. Maybe you need update version?

What went wrong:
Execution failed for task ':app:processDebugManifest'.

Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [:jitsi_meet] {ProjectLocation}/build/jitsi_meet/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 21
  	Suggestion: use a compatible library with a minSdk of at most 21,
  		or increase this project's minSdk version to at least 24,
  		or use tools:overrideLibrary="com.gunschu.jitsi_meet" to force usage (may lead to runtime failures)

**Comment by nilsreichardt** [comment]
It seems that no new update has been published 😬

![image](https://user-images.githubusercontent.com/24459435/83874156-50dd3100-a735-11ea-9591-89cc2439a382.png)

**Comment by chandrabezzo** [comment]
@AndroidNils My change request has been merged, but min SDK still 24.

**Comment by tuantvu** [comment]
@chandrabezzo Hi, sorry late publishing. Are you still having the issue? We are on 0.2.3 now.

**Comment by chandrabezzo** [comment]
> @chandrabezzo Hi, sorry late publishing. Are you still having the issue? We are on 0.2.3 now.

Hi @tuantvu done, now I can use this package using Min 21. Thank You.

**Comment by nilsreichardt** [comment]
I can't run the example app with API level 21...

```
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [org.jitsi.react:jitsi-meet-sdk:2.11.0] /Users/nils/.gradle/caches/transforms-2/files-2.1/1bcb6cf5d6294db9694c5c0e1e65a036/jetified-jitsi-meet-sdk-2.11.0/AndroidManifest.xml as the library might be using APIs not available in 21
  	Suggestion: use a compatible library with a minSdk of at most 21,
  		or increase this project's minSdk version to at least 23,
  		or use tools:overrideLibrary="org.jitsi.meet.sdk" to force usage (may lead to runtime failures)
```

@chandrabezzo How did you mange to run Jitsi with API Level 21?

**Comment by chandrabezzo** [comment]
@nilsreichardt you must use old version of jitsi_meet, or you must change to the old version of jitsi SDK. Because the latest jitsi SDK and jitsi_meet required by version 23.
