### ISSUE TITLE
Please use git tags to mark the releases in the history

### ISSUE THREAD

**Issue by rwbr** [gunschu/jitsi_meet#44]
When using the package in a Flutter project, you have different options, how to set the dependency in your pubspec.yaml. If you use the `path`-syntax, it would be incredibly useful, if it was possible to checkout exactly the code, that belongs to e.g. version 0.2.0.

It's common practice to set tags for releases in git. So please set tags for future release versions.

**Comment by tuantvu** [comment]
Thanks for reminder about git tags. Could you link to documentation about the path syntax. I found this: https://dart.dev/tools/pub/dependencies#path-packages, but that may be wrong because I can't correlate the benefit you mention with this.

**Comment by rwbr** [comment]
The pub tool supports different dependency sources. Among them there is the possibility to use git packages. The documentation https://dart.dev/tools/pub/dependencies#git-packages refers to a parameter called **ref**. This can be set to a specific branch, commit-id or tag. 

The current version of the package is 0.2.3. I wish, that the associated source code would get a tag `v0.2.3`. There are not special requirements in the documentation about the format of tags. But I suggest tagging the code associated with a version. The it would make it easier to include it as a git-dependency.

**Comment by tuantvu** [comment]
@rwbr I retroactively added tags, hopefully all of them point to the correct commits. Close issue if it is good enough.

**Comment by rwbr** [comment]
Perfect. Thank you.

**Comment by rwbr** [comment]
Closing Issue now.
