### ISSUE TITLE
Could you please implement an end meeting functionality from the dart code ?

### ISSUE THREAD

**Issue by devidasm** [gunschu/jitsi_meet#45]
In my app, there is a functionality to end the meeting programmatically when the host stopped the meeting. Please check about this https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#leave

**Comment by tuantvu** [comment]
Duplicate of #39

**Comment by devidasm** [comment]
Sorry ? It seems you misunderstand the question. Anyway I already solved this problem by editing the plugin source.
