### ISSUE TITLE
Enable Token

### ISSUE THREAD

**Issue by tuantvu** [gunschu/jitsi_meet#5]
Enable clients to pass in JWT authentication token. There will be limited testing with this and it will only work with private Jitsi server installations.

**Comment by gnusagit** [comment]
Hi Tuanvu,
when will the JWT 'token' in jitsi flutter plugin is available?

**Comment by DenisMrGnusa** [comment]
+1
same with me, how to do that?

**Comment by matheusagnes** [comment]
+1
same with me, how to do that?

**Comment by CeeZe** [comment]
+1 
this token will greatly help the security of the conference

**Comment by cyriacbijun** [comment]
@tuantvu  If you can provide some help to start off with implementing JWT token, it would be greatly appreciated. Many others would also be benefited from this feature.

**Comment by tuantvu** [comment]
Hi all, the token implementation should be straight forward. Add the field to meeting options as a string and pass it to the back end methodhandler. In iOS and Android, just read that field and set it in the Meeting options object field that jitsi provides. 

2/3 of this is already done actually. There's already a field called token in dart and Android code. Just need to implement it in Swift. The reason why I call it unsupported is because I'm not able to test it. So if any of you are able to implement the Swift and test both, then please create a pull request.

**Comment by singingplayer** [comment]
> Hi all, the token implementation should be straight forward. Add the field to meeting options as a string and pass it to the back end methodhandler. In iOS and Android, just read that field and set it in the Meeting options object field that jitsi provides.
> 
> 2/3 of this is already done actually. There's already a field called token in dart and Android code. Just need to implement it in Swift. The reason why I call it unsupported is because I'm not able to test it. So if any of you are able to implement the Swift and test both, then please create a pull request.
--------------
Thanks a lot

**Comment by DenisMrGnusa** [comment]
> Hi all, the token implementation should be straight forward. Add the field to meeting options as a string and pass it to the back end methodhandler. In iOS and Android, just read that field and set it in the Meeting options object field that jitsi provides.
> 
> 2/3 of this is already done actually. There's already a field called token in dart and Android code. Just need to implement it in Swift. The reason why I call it unsupported is because I'm not able to test it. So if any of you are able to implement the Swift and test both, then please create a pull request.

greate, thank you

**Comment by cyriacbijun** [comment]
@tuantvu  thank you for the info. I have been successful in using it for Android, opening the app from a link via deep linking. For those of you trying to do the same....

1 first add [uni_links package](https://pub.dev/packages/uni_links) and import it in `main.dart` as per their docs.
2 I am explaining using the example given by jitsi_meet plugin itself.Inside your `main.dart`, do the following
```
Widget build(BuildContext context) {
    return MaterialApp(
      home: StreamBuilder(
        stream: getLinksStream(),
        builder: (context , snapshot){
          if( snapshot.hasData ) {
            var uri = Uri.parse(snapshot.data);
            roomText = uri.path.replaceAll('/', '');
            var list =uri.queryParameters.entries.toList();
            token = list[0].value;
            return Scaffold()
            //also take care of else condition,i.e, user opens app without clicking your URL
```
StreamBuilder is used by `uni_links` to get the complete url which leads it to app.
3 go down to the section `_joinMeeting() async `  in main.dart itself and add the token option
```_joinMeeting() async {
    String serverUrl = serverText;

    try {
      var options = JitsiMeetingOptions()
        ..room = roomText
        ..serverURL = serverUrl
        ..token = token
        ..audioOnly = isAudioOnly
        ..audioMuted = isAudioMuted
        ..videoMuted = isVideoMuted;
```
4 Then, inside your android project go to `android\app\src\main\AndroidManifest.xml` and create the intent filters if not done
```<intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:host="your.domain.com" android:scheme="https" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:host="your.domain.com" android:scheme="com.package.app" />
            </intent-filter>
        </activity>
```

Now, when you click a link of the type `https://your.domain/roomName?jwt=<token>` it would take you directly to conference

I hope I have described everything correctly, feel free to ask.

**Comment by DenisMrGnusa** [comment]
> Hi all, the token implementation should be straight forward. Add the field to meeting options as a string and pass it to the back end methodhandler. In iOS and Android, just read that field and set it in the Meeting options object field that jitsi provides.
> 
> 2/3 of this is already done actually. There's already a field called token in dart and Android code. Just need to implement it in Swift. The reason why I call it unsupported is because I'm not able to test it. So if any of you are able to implement the Swift and test both, then please create a pull request.

thank you for your info

**Comment by tdwelsh28** [comment]
Passing the token the the underlying Jitsi SDK was working.
I've pushed #58 to add iOS support, tested and working against our Jitsi server.

**Comment by tuantvu** [comment]
Thanks @tdwelsh28

**Comment by ashishranjan-dev** [comment]
> 
Hey i didint understood what ur r geeting in resposnse form getlinks method used in your stream builder,,,,can u share the codeor just explain that part..it would be really helful
