### ISSUE TITLE
i got android keyboard issues after adding jitsi_meet: ^0.2.2

### ISSUE THREAD

**Issue by jayeshpansheriya** [gunschu/jitsi_meet#51]
android screenshot in normal design.
![Screenshot_1592208236](https://user-images.githubusercontent.com/31765271/84632901-3e20e400-af0d-11ea-98f1-05601935e6c5.png)
![Screenshot_1592208240](https://user-images.githubusercontent.com/31765271/84632923-4547f200-af0d-11ea-8bb6-957104693d75.png)

after adding jitsi_meet: ^0.2.2. library i face this issues,
![Screenshot_1592208312](https://user-images.githubusercontent.com/31765271/84633067-7cb69e80-af0d-11ea-8cd4-7d473ed4f555.png)
![Screenshot_1592208314](https://user-images.githubusercontent.com/31765271/84633093-82ac7f80-af0d-11ea-92d5-55cbd8302d06.png)

keybord hide my screen, i have try many option but get same issues.

**Comment by tuantvu** [comment]
@jayeshpansheriya Document what you have tried please. This may be related to #57

**Comment by jayeshpansheriya** [comment]
final bottom = MediaQuery.of(context).viewInsets.bottom;
Then use a SingleChildScrollView() to wrap around the main widget (whatever you're using, e.g. Column, ListView, etc) like this...

You need "reverse: true"

Widget build{
return Scaffold(
body: SingleChildScrollView(
reverse: true;
child: Container(...
You also need these two lines of code for the Scaffold as well..

return Scaffold(
resizeToAvoidBottomInset: false,
resizeToAvoidBottomPadding: false,
body: SingleChildScrollView(...
and finally, reference the 'bottom' for your EdgeInsets..

body: SingleChildScrollView(
reverse: true,
child: Padding(
padding: EdgeInsets.only(bottom: bottom),
child: Container(...




i have make multi  try to solve this like above example.
but when i remove this library its working fine after adding jisti_meet i face keyboard overlaping issues also in my own designed login screen.

**Comment by tuantvu** [comment]
I haven't tried this yet, but I saw some online settings like this in their AndroidManifest. Could you try this:

<activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:windowSoftInputMode="adjustResize"

**Comment by jayeshpansheriya** [comment]
I have already added,
```
 <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">

```

**Comment by jayeshpansheriya** [comment]
> @jayeshpansheriya Document what you have tried please. This may be related to #57

i face this issues only on android device.

**Comment by jimmyjose-dev** [comment]
Please reopen if you are facing the same problem with the latest version
