### ISSUE TITLE
Is it possible to have the jitsi_meet in background?

### ISSUE THREAD

**Issue by subhendukundu** [gunschu/jitsi_meet#52]
How likely this is possible to have the jitsi module in the background when the app opens up a different screen on the app?

The idea is to have the voice in the background while someone is explaining on the whiteboard in the app? Also if we want to have picture in picture to have the other person talking on floating?

**Comment by tuantvu** [comment]
@subhendukundu I'm a bit confused with your explanation. Could you clarify? PIP is supported by Jitsi already, is it different than what you are looking for?
