### ISSUE TITLE
Screen share

### ISSUE THREAD

**Issue by ziasultan2** [gunschu/jitsi_meet#53]
Will you please add screen share functionality ASAP. Very much interested to add in my application once it has functionality

**Comment by TBG-FR** [comment]
Hello

This plugin is an integration of the Jitsi Meet SDK, and isn't responsible for these functionnalities.
The SDK repository is here : https://github.com/jitsi/jitsi-meet

I suggest you to search through commits and issues to see if that feature is already available, or under development
You can also contribute and help them, if you really need that feature :wink:

**Comment by nilsreichardt** [comment]
There is already a ticket for iOS Screen sharing: https://github.com/jitsi/jitsi-meet/issues/5252

**Comment by ziasultan2** [comment]
Thank you dear for your effort and reply.
