### ISSUE TITLE
Flutter Calling Screen Problem

### ISSUE THREAD

**Issue by FarhanAli001** [gunschu/jitsi_meet#55]
I was able to make audio conference call but the problem is that whenever the call connects the given below screen shows up, but i want to hide it and display my own custom UI, kindly help me, i will be very thankful to you

**Comment by rwbr** [comment]
I don’t fully understand your problem. It seems, that you want to show a custom view when having a conference call. This plugin just embeds the Jitsi mobile SDK for Flutter. 


The SDK repository is here : https://github.com/jitsi/jitsi-meet

You should take a look at the code there. Hopefully you find a way to customize the view. This project is not responsible for the Jitsi UI.  😉

**Comment by FarhanAli001** [comment]
i am using jitsi but i want to show my own custom ui screen for calling instead of jitsi default calling screen, kindly help me i will be very thankful to you

**Comment by rwbr** [comment]
As I wrote, the purpose of this project is to embed the Jitsi SDK in a Flutter app. This project is not about changing the UI. If you want to change the UI, you have to manipulate the Jitsi SDK itself, then compile it and link it to your application.

**Comment by FarhanAli001** [comment]
can you please prefer any other platform that can be modified easily with the new custom UI

**Comment by FarhanAli001** [comment]
I will be very thankful to you if you help

**Comment by tuantvu** [comment]
@FarhanAli001 I unfortunately do not know an alternative that has a Flutter plugin or is easily customizable, sorry.

**Comment by tuantvu** [comment]
Duplicate to #22
