### ISSUE TITLE
Android: keyboard overlapping in chat part

### ISSUE THREAD

**Issue by kaushaldeligence** [gunschu/jitsi_meet#57]
### Description:

The keyboard overlaps message box on the chat ui of jisti meet sdk.
This issue is on android part only. On iOS it is working fine.

### Steps to reproduce:

1. Open the jisti chat feature.
2. Click on the message box to type something.

### Expected behaviour:

No overlapping should have occurred.

### Additional information:
![85013510-50f01e80-b182-11ea-892f-e3054ab41dac](https://user-images.githubusercontent.com/58382387/85372158-0fc78800-b54f-11ea-99f8-2cece7d49c03.jpeg)
![85013521-564d6900-b182-11ea-8bed-bc399eb503b9](https://user-images.githubusercontent.com/58382387/85372167-135b0f00-b54f-11ea-9e48-bf882cf2e723.jpeg)
![85013535-5baab380-b182-11ea-91df-da598daeebd2](https://user-images.githubusercontent.com/58382387/85372176-1524d280-b54f-11ea-92e3-db9d05c34de5.jpeg)

**Comment by coder-Aayush** [comment]
Same Issue. Also when the chat screen is closed the keyboard overlap the button actions like mute, end call ,.....

**Comment by jimmyjose-dev** [comment]
Please reopen if you are facing the same problem with the latest version
