### ISSUE TITLE
dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by luckymehndiratta** [gunschu/jitsi_meet#59]
Hi Team we face this issue in iOS please look into this

[!] CocoaPods could not find compatible versions for pod "jitsi_meet":
  In Podfile:
    jitsi_meet (from `.symlinks/plugins/jitsi_meet/ios`)

Specs satisfying the `jitsi_meet (from `.symlinks/plugins/jitsi_meet/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by rwbr** [comment]
Please take a look at #41. You need to set the deployment target to iOS 11.0.

**Comment by tuantvu** [comment]
@luckymehndiratta Have you been able to resolve the issue?
