### ISSUE TITLE
Enable feature flags, colorscheme, and avatarURL

### ISSUE THREAD

**Issue by tuantvu** [gunschu/jitsi_meet#6]
Need research and testing with these fields that the SDK takes in. Research for feature flags and color scheme because there is not great documentation on Jitsi site on what to pass in. AvatarURL was tried, but did nothing on the UI (like email address).

**Comment by gunschu** [comment]
Added a param for IOS App Bar only . Now you can change the color of the IOS AppBar based on your color scheme.

**Comment by TBG-FR** [comment]
You can review my feature flags implementation here : #54 , hoping that it fit your needs

**Comment by tuantvu** [comment]
Closing this issue and will break it out the other two issues separately
