### ISSUE TITLE
Failed to load module 'JitsiMeet' in xcode 11.3

### ISSUE THREAD

**Issue by maneesh12345** [gunschu/jitsi_meet#61]

**Comment by tuantvu** [comment]
@maneesh12345 Please provide logs and how to recreate.

**Comment by mirmahfuz99** [comment]
I have also faced this problem . It works fine in ios Simulator But When I try to archive issue happened like that :
parse error :  Module Jitsi Meet Not Found .

My Xcode : 11.5 
Jitsi Meet Sdk : 2.9.0
I have updated pods like :  platform :ios, '11.0' 
My Flutter Version 1.17.4
Dart: 2.8.4
Note: I have enabled Bitcode to No
Here details Error again when I tried to archive from Terminal .
I have run project successfully  from Android Studio to Simulator .
Also run successfully from Runner.xcworkspace 

CompileC /Users/mirmahfuz/Library/Developer/Xcode/DerivedData/Runner-buyldnewombglufwypkvaafhubpf/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/GeneratedPluginRegistrant.o /Users/SpaGreenCreative/meet_air/ios/Runner/GeneratedPluginRegistrant.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by tuantvu** [comment]
Please update Xcode to at least 11.4
