### ISSUE TITLE
How can I remove appBar when I am at meeting?

### ISSUE THREAD

**Issue by coder-Aayush** [gunschu/jitsi_meet#64]
When User Join Room there is top appBar with App Label. Is there any way I can remove that appBar?

**Comment by abrito92** [comment]
Same problem here. Have you found anything?

**Comment by coder-Aayush** [comment]
@abrito92 no brother not found yet :(

**Comment by jimmyjose-dev** [comment]
Inside Jitsiviewcontroller.swift add these lines

```
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
    // Hide the Navigation Bar
            self.navigationController?.setNavigationBarHidden(true, animated: true)
        }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(true)
    // Show the Navigation Bar
            self.navigationController?.setNavigationBarHidden(false, animated: false)
        }
```

It will hide Navigationbar.



![Flutter_Jitsi_without_navbar](https://user-images.githubusercontent.com/1427616/88927918-c678ff80-d295-11ea-9637-88de213017d1.png)

**Comment by buzzwin** [comment]
Currently there is no way to remove it in IOS but you can change the color.

Sent from Yahoo Mail for iPhone


On Thursday, July 30, 2020, 8:22 AM, Jimmy Jose <notifications@github.com> wrote:




Inside Jitsiviewcontroller.swift add these lines
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
    // Hide the Navigation Bar
            self.navigationController?.setNavigationBarHidden(true, animated: true)
        }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(true)
    // Show the Navigation Bar
            self.navigationController?.setNavigationBarHidden(false, animated: false)
        }

It will hide Navigationbar.

**Comment by jimmyjose-dev** [comment]
I can do a PR that removes the navigationbar in iOS if needed.

**Comment by coder-Aayush** [comment]
can anyone can verify and close this issue. I don't have mac
