### ISSUE TITLE
Sound issue on speaker & Call Kit testing

### ISSUE THREAD

**Issue by Faiyyaz** [gunschu/jitsi_meet#67]
Hey,

Thanks for such a great library 

I just had an issue on android that after disconnecting my headphone i am not able to hear the other person on speakerphone.

And how to test call kit integration in iOS

Can you help?

**Comment by tuantvu** [comment]
Sorry, not a call kit expert. That may gain more traction if you create a different bug for it with its own title. As for the defect, has anyone else encountered the same issue?
