### ISSUE TITLE
I have build jitsi meet sdk from source how can i use in these plugin

### ISSUE THREAD

**Issue by ashiqmcmmc** [gunschu/jitsi_meet#68]
I have build jitsi meet sdk from source code, how can i use build sdk in these plugin

**Comment by tuantvu** [comment]
Fork this repository (ashiqmcmmc/jitsi_meet), then change the Android and IOS Jitsi Meet dependencies to your built source of the Jitsi SDK. Then in your main project, you can reference your forked flutter jitsi_meet plugin repository (ashiqmcmmc/jitsi_meet) like this: https://dart.dev/tools/pub/dependencies#git-packages
