### ISSUE TITLE
Is there any way to Change Text inside Invite Other Button?

### ISSUE THREAD

**Issue by coder-Aayush** [gunschu/jitsi_meet#71]
Is there any way I can change text inside **Invite Other.** 
Invite Other Button is inside meeting. 

![20200716_083903](https://user-images.githubusercontent.com/47755613/87622068-01315280-c742-11ea-96f5-840bfecac1b6.jpg)

Thanks For Help!

**Comment by TBG-FR** [comment]
This element belongs to the Jitsi Meet SDK, and this Flutter plugin is "only an integration" of it. I think you would have no other choice than modifying the SDK and recompiling it, to modify a such thing

=> https://github.com/jitsi/jitsi-meet (subdirectories `android` and `ios` both have a `sdk` subdirectory)

**Comment by coder-Aayush** [comment]
@TBG-FR Thanks for information
