### ISSUE TITLE
Be able to see users and remove them

### ISSUE THREAD

**Issue by boucoding** [gunschu/jitsi_meet#72]
Hi,

this plugin sounds great! but I have a question which can I give a user permission to see the connected users and kick out a user if he wants?

**Comment by TBG-FR** [comment]
I don't know how it works for iOS, but for Android I used `onPictureInPictureModeChanged` method, you can check what I've done with that here : https://github.com/gunschu/jitsi_meet/commit/8d04e54e0e74a7d53b36e35cd7feefb504292f14 .

I assume that yuu could then add here some Android code, or trigger a callback or something like that is in your Dart code.

**Comment by boucoding** [comment]
Will it work if pip isn't in enabled?

**Comment by TBG-FR** [comment]
@boucoding I don't know, you'll have to try... If I find some time I'll try and tell you !

**Comment by boucoding** [comment]
Ok, I appreciate your time!
