### ISSUE TITLE
Is there any callback function when video goes to PIP? 

### ISSUE THREAD

**Issue by prabhatsdp** [gunschu/jitsi_meet#76]

**Comment by jimmyjose-dev** [comment]
Currently there isn't... but should be easy to implement if you want to. 
Lets say you wanna do it for android....

In this class JitsiMeetingListener add

`final Function({Map<dynamic, dynamic> message}) onPictureInPictureWillEnter;
  final Function({Map<dynamic, dynamic> message}) onPictureInPictureTerminated;`
pass in the constructor as well..

Then in Jitsimeet
_broadcastToPerMeetingListeners & _broadcastToGlobalListeners function add

```
case "onPictureInPictureWillEnter":
          if (listener.onPictureInPictureWillEnter != null)
            listener.onPictureInPictureWillEnter(message: message);
          break;

        case "onPictureInPictureTerminated":
          if (listener.onPictureInPictureTerminated != null)
            listener.onPictureInPictureTerminated(message: message);
          break;
```

then in plugin activity.kt do this inside
onPictureInPictureModeChanged

 ```
if (isInPictureInPictureMode){

            JitsiMeetEventStreamHandler.instance.onPictureInPictureWillEnter()

        }else{


            JitsiMeetEventStreamHandler.instance.onPictureInPictureTerminated()
        }
```

In JitsiMeetEventStreamHandler add these

```
fun onPictureInPictureWillEnter() {
        Log.d(JITSI_PLUGIN_TAG, "JitsiMeetEventStreamHandler.onPictureInPictureWillEnter")
        var data : HashMap<String, String>
                = HashMap<String, String> ()
        data?.put("event", "onPictureInPictureWillEnter")
        eventSink?.success(data)
    }

    fun onPictureInPictureTerminated() {
        Log.d(JITSI_PLUGIN_TAG, "JitsiMeetEventStreamHandler.onPictureInPictureTerminated")
        var data : HashMap<String, String>
                = HashMap<String, String> ()
        data?.put("event", "onPictureInPictureTerminated")
        eventSink?.success(data)
    }
```

Now you can use the listener in your dart code... like this

```
JitsiMeet.addListener(JitsiMeetingListener(
        onConferenceWillJoin: _onConferenceWillJoin,
        onConferenceJoined: _onConferenceJoined,
        onConferenceTerminated: _onConferenceTerminated,
        onPictureInPictureWillEnter: _onPictureInPictureWillEnter,
        onPictureInPictureTerminated: _onPictureInPictureTerminated,
        onError: _onError));
```

Hope this makes sense.....

For iOS enterPIP callback will be straightforward but for exitPIP we might have to call from viewWillTransition... there might be cleaner way too

Let me see if I can do a PR for this

**Comment by jimmyjose-dev** [comment]
Turns out there was indeed a cleaner way for iOS
PR #82 Callback for PIP mode

**Comment by jimmyjose-dev** [comment]
This feature exists now...closing this issue.

**Comment by Aida-ops** [comment]
is there any way to disable pip and Press back button without leave (pip enable only for back button) on andorid?
