### ISSUE TITLE
Password for meeting

### ISSUE THREAD

**Issue by SudeshAK** [gunschu/jitsi_meet#78]
Hi,
Can we provide password for the meeting along with the room name?

**Comment by TBG-FR** [comment]
Hi,

It is currently not possible, the Jitsi Meet SDK isn't providing an option for that (see [JitsiMeetConferenceOptions.java](https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetConferenceOptions.java))

However, you could improve that and submit a pull request to the [SDK repository](https://github.com/jitsi/jitsi-meet) and then the plugin could rely on it !
