### ISSUE TITLE
[FEATURE]: Embed JitsiMeet within a PlatformView to enable Custom Layouts

### ISSUE THREAD

**Issue by kleeb** [gunschu/jitsi_meet#79]
Currently when joininig or creating a room, the fullscreen view is opened on top of the app.
Is it possible to allow for some flutter widget interaction, to give small example - show some footer with Flutter button that would open a modal.

**Comment by tuantvu** [comment]
I believe some one was hoping to put the jitsi views within a PlatformView, that would be cool, though I haven't heard how successful that was. That would be a cool pull requests, but I think it needs a lot of testing with multiple layouts.

**Comment by abnerh69** [comment]
Hi,  is there some progress on using this package inside another widget (lets say PlatformView)?

**Comment by kleeb** [comment]
I guess noone is working on it. Hell of a task!

**Comment by wvffle** [comment]
I don't think that a pinned issue should be stale

**Comment by tuantvu** [comment]
Keep open

**Comment by tuantvu** [comment]
Bump again

**Comment by ShreshtaRupa** [comment]
I hope we get a customisable UI for Flutter

**Comment by tuantvu** [comment]
Not stale

**Comment by deepak-gehlot** [comment]
I have used platform view in my app, and performance is Good.

**Comment by kleeb** [comment]
> I have used platform view in my app, and performance is Good.

can you share some code snippet ?

**Comment by deepak-gehlot** [comment]
I have used platform view, below code is for iOS side, I will try to send my full code for both side.

`//
//  FLNativeView.swift
//  Runner
//
//  Created by mac on 07/10/21.
//
import JitsiMeetSDK
import Flutter
import UIKit

class FLNativeViewFactory: NSObject, FlutterPlatformViewFactory {
    private var messenger: FlutterBinaryMessenger

    init(messenger: FlutterBinaryMessenger) {
        self.messenger = messenger
        super.init()
    }

    func create(
        withFrame frame: CGRect,
        viewIdentifier viewId: Int64,
        arguments args: Any?
    ) -> FlutterPlatformView {
        return FLNativeView(
            frame: frame,
            viewIdentifier: viewId,
            arguments: args,
            binaryMessenger: messenger)
    }
}

class FLNativeView: NSObject, FlutterPlatformView {
    private var _view: UIView
    var jitsiMeetView: JitsiMeetView?
    
    let viewId: Int64
     let messenger: FlutterBinaryMessenger
     let channel: FlutterMethodChannel
    
    init(
        frame: CGRect,
        viewIdentifier viewId: Int64,
        arguments args: Any?,
        binaryMessenger messenger: FlutterBinaryMessenger?
    ) {
        self.messenger = messenger
          self.viewId = viewId
        
        _view = UIView()
        super.init()
        // iOS views can be created here
        createNativeView(view: _view)
        
        let channel = FlutterMethodChannel(name: "JitsiView/\(Id)",
                                              binaryMessenger: messenger)
        
           channel.setMethodCallHandler({ (call: FlutterMethodCall, result: FlutterResult) -> Void in
             switch call.method {
             case "receiveFromFlutter":
              guard let args = call.arguments as? [String: Any],
                let text = args["text"] as? String, else {
                result(FlutterError(code: "-1", message: "Error"))
                return
              }
               self.magicView.receiveFromFlutter(text)
               result("receiveFromFlutter success")
             default:
                 result(FlutterMethodNotImplemented)
             }
           })
    }

    public func sendFromNative(_ text: String) {
        channel.invokeMethod("sendFromNative", arguments: text)
      }
    
    func view() -> UIView {
        return _view
    }

    func createNativeView(view _view: UIView){
        _view.backgroundColor = UIColor.blue
        
        // create and configure jitsimeet view
                let jitsiMeetView = JitsiMeetView()
          //      jitsiMeetView.delegate = self
                self.jitsiMeetView = jitsiMeetView
                let options = JitsiMeetConferenceOptions.fromBuilder { (builder) in
                    // for JaaS use <tenant>/<roomName> format
                    builder.room = "worty43543"
                    builder.serverURL = URL(string: "https://meet.jit.si")
                   // builder.setFeatureFlag("toolbox.enabled", withBoolean: true)
                                //builder.setFeatureFlag("filmstrip.enabled", withBoolean: true)
                    builder.setFeatureFlag("call-integration.enabled", withBoolean: false)
                    // Settings for audio and video
                     builder.audioMuted = true;
                     builder.videoMuted = true;
                }
                
        
        self.jitsiMeetView?.frame = CGRect(x: 0, y: 0, width: 380, height: 450)
        
        jitsiMeetView.delegate = self
        
        // join room and display jitsi-call
        jitsiMeetView.join(options)
        
        _view.addSubview(jitsiMeetView)
        
       
    }
    
    fileprivate func cleanUp() {
            if(jitsiMeetView != nil) {
                dismiss(animated: true, completion: nil)
                jitsiMeetView = nil
            }
        }
}


extension FLNativeView: JitsiMeetViewDelegate {
    func conferenceTerminated(_ data: [AnyHashable : Any]!) {
        cleanUp()
    }
    func chatMessaageReceived(_ data: [AnyHashable : Any]!) {
        sendFromNative(data["message"])
    }
}
`

**Comment by deepak-gehlot** [comment]
`//
//  FLNativeView.swift
//  Runner
//
//  Created by mac on 07/10/21.
//
import JitsiMeetSDK
import Flutter
import UIKit

class FLNativeViewFactory: NSObject, FlutterPlatformViewFactory {
    private var messenger: FlutterBinaryMessenger

    init(messenger: FlutterBinaryMessenger) {
        self.messenger = messenger
        super.init()
    }

    func create(
        withFrame frame: CGRect,
        viewIdentifier viewId: Int64,
        arguments args: Any?
    ) -> FlutterPlatformView {
        return FLNativeView(
            frame: frame,
            viewIdentifier: viewId,
            arguments: args,
            binaryMessenger: messenger)
    }
}

class FLNativeView: NSObject, FlutterPlatformView {
    private var _view: UIView
    var jitsiMeetView: JitsiMeetView?
    
    let viewId: Int64
     let messenger: FlutterBinaryMessenger
     let channel: FlutterMethodChannel
    
    init(
        frame: CGRect,
        viewIdentifier viewId: Int64,
        arguments args: Any?,
        binaryMessenger messenger: FlutterBinaryMessenger?
    ) {
        self.messenger = messenger
          self.viewId = viewId
        
        _view = UIView()
        super.init()
        // iOS views can be created here
        createNativeView(view: _view)
        
        let channel = FlutterMethodChannel(name: "JitsiView/\(Id)",
                                              binaryMessenger: messenger)
        
           channel.setMethodCallHandler({ (call: FlutterMethodCall, result: FlutterResult) -> Void in
             switch call.method {
             case "receiveFromFlutter":
              guard let args = call.arguments as? [String: Any],
                let text = args["text"] as? String, else {
                result(FlutterError(code: "-1", message: "Error"))
                return
              }
               self.magicView.receiveFromFlutter(text)
               result("receiveFromFlutter success")
             default:
                 result(FlutterMethodNotImplemented)
             }
           })
    }

    public func sendFromNative(_ text: String) {
        channel.invokeMethod("sendFromNative", arguments: text)
      }
    
    func view() -> UIView {
        return _view
    }

    func createNativeView(view _view: UIView){
        _view.backgroundColor = UIColor.blue
        
        // create and configure jitsimeet view
                let jitsiMeetView = JitsiMeetView()
          //      jitsiMeetView.delegate = self
                self.jitsiMeetView = jitsiMeetView
                let options = JitsiMeetConferenceOptions.fromBuilder { (builder) in
                    // for JaaS use <tenant>/<roomName> format
                    builder.room = "worty43543"
                    builder.serverURL = URL(string: "https://meet.jit.si")
                   // builder.setFeatureFlag("toolbox.enabled", withBoolean: true)
                                //builder.setFeatureFlag("filmstrip.enabled", withBoolean: true)
                    builder.setFeatureFlag("call-integration.enabled", withBoolean: false)
                    // Settings for audio and video
                     builder.audioMuted = true;
                     builder.videoMuted = true;
                }
        self.jitsiMeetView?.frame = CGRect(x: 0, y: 0, width: 380, height: 450)
        
        jitsiMeetView.delegate = self
        
        // join room and display jitsi-call
        jitsiMeetView.join(options)
        
        _view.addSubview(jitsiMeetView)
    }
    
    fileprivate func cleanUp() {
            if(jitsiMeetView != nil) {
                dismiss(animated: true, completion: nil)
                jitsiMeetView = nil
            }
        }
}

extension FLNativeView: JitsiMeetViewDelegate {
    func conferenceTerminated(_ data: [AnyHashable : Any]!) {
        cleanUp()
    }
    func chatMessaageReceived(_ data: [AnyHashable : Any]!) {
        sendFromNative(data["message"])
    }
}
`

**Comment by deepak-gehlot** [comment]
`import JitsiMeetSDK
import Flutter
import UIKit

class FLNativeViewFactory: NSObject, FlutterPlatformViewFactory {
    private var messenger: FlutterBinaryMessenger

    init(messenger: FlutterBinaryMessenger) {
        self.messenger = messenger
        super.init()
    }

    func create(
        withFrame frame: CGRect,
        viewIdentifier viewId: Int64,
        arguments args: Any?
    ) -> FlutterPlatformView {
        return FLNativeView(
            frame: frame,
            viewIdentifier: viewId,
            arguments: args,
            binaryMessenger: messenger)
    }
}

class FLNativeView: NSObject, FlutterPlatformView {
    private var _view: UIView
    var jitsiMeetView: JitsiMeetView?
    
    let viewId: Int64
     let messenger: FlutterBinaryMessenger
     let channel: FlutterMethodChannel
    
    init(
        frame: CGRect,
        viewIdentifier viewId: Int64,
        arguments args: Any?,
        binaryMessenger messenger: FlutterBinaryMessenger?
    ) {
        self.messenger = messenger
          self.viewId = viewId
        
        _view = UIView()
        super.init()
        // iOS views can be created here
        createNativeView(view: _view)
        
        let channel = FlutterMethodChannel(name: "JitsiView/\(Id)",
                                              binaryMessenger: messenger)
        
           channel.setMethodCallHandler({ (call: FlutterMethodCall, result: FlutterResult) -> Void in
             switch call.method {
             case "receiveFromFlutter":
              guard let args = call.arguments as? [String: Any],
                let text = args["text"] as? String, else {
                result(FlutterError(code: "-1", message: "Error"))
                return
              }
               self.magicView.receiveFromFlutter(text)
               result("receiveFromFlutter success")
             default:
                 result(FlutterMethodNotImplemented)
             }
           })
    }

    public func sendFromNative(_ text: String) {
        channel.invokeMethod("sendFromNative", arguments: text)
      }
    
    func view() -> UIView {
        return _view
    }

    func createNativeView(view _view: UIView){
        _view.backgroundColor = UIColor.blue
        
        // create and configure jitsimeet view
                let jitsiMeetView = JitsiMeetView()
          //      jitsiMeetView.delegate = self
                self.jitsiMeetView = jitsiMeetView
                let options = JitsiMeetConferenceOptions.fromBuilder { (builder) in
                    // for JaaS use <tenant>/<roomName> format
                    builder.room = "worty43543"
                    builder.serverURL = URL(string: "https://meet.jit.si")
                   // builder.setFeatureFlag("toolbox.enabled", withBoolean: true)
                                //builder.setFeatureFlag("filmstrip.enabled", withBoolean: true)
                    builder.setFeatureFlag("call-integration.enabled", withBoolean: false)
                    // Settings for audio and video
                     builder.audioMuted = true;
                     builder.videoMuted = true;
                }
        self.jitsiMeetView?.frame = CGRect(x: 0, y: 0, width: 380, height: 450)
        
        jitsiMeetView.delegate = self
        
        // join room and display jitsi-call
        jitsiMeetView.join(options)
        
        _view.addSubview(jitsiMeetView)
    }
    
    fileprivate func cleanUp() {
            if(jitsiMeetView != nil) {
                dismiss(animated: true, completion: nil)
                jitsiMeetView = nil
            }
        }
}

extension FLNativeView: JitsiMeetViewDelegate {
    func conferenceTerminated(_ data: [AnyHashable : Any]!) {
        cleanUp()
    }
    func chatMessaageReceived(_ data: [AnyHashable : Any]!) {
        sendFromNative(data["message"])
    }
}`

**Comment by swarupbhc** [comment]
Hi @deepak-gehlot can you please share an example project or something? It will help me a lot, thanks.

**Comment by Bilalsk** [comment]
Not stale

**Comment by tanthokg** [comment]
Hello @deepak-gehlot  could you share your example project, please? It will help me a great deal, I've been stucked here for weeks. Thank you so much!

**Comment by zeckem19** [comment]
+1 please
