### ISSUE TITLE
Change Conference Title

### ISSUE THREAD

**Issue by kry0sc0pic** [gunschu/jitsi_meet#85]
Hi , is there anyway to change the title of the meeting? (Not the subject). I mean the instead of the `android:label` as title can we have anything else?

**Comment by jimmyjose-dev** [comment]
Are you looking for this option because you want to keep the navigation bar or you think we cannot remove the navigation bar and so a way to change the title.... if latter is the case maybe this PR will interest you...
Remove Navigation bar for both Android and iOS #87

**Comment by kry0sc0pic** [comment]
Because I want to keep the navigation bar.

**Comment by tuantvu** [comment]
We have gone ahead with removing the navigation bar. It only shows up for a little bit (sometimes not at all if your phone loads fast) and is a strange user experience. I think what we really want is to some how embed Jitsi into a PlatformView and therefore get better layout options.

**Comment by kry0sc0pic** [comment]
Thank You
