### ISSUE TITLE
App Crash - Lobby Room

### ISSUE THREAD

**Issue by amitsdixit** [gunschu/jitsi_meet#86]
App crash when the user try to join a meeting which has lobby room enabled.

**Comment by jimmyjose-dev** [comment]
The current maven repository for mobile sdk that we use to build this framework doesn't have the support for Lobby Room, we would need to wait for official Jitsi team to push it there. [Don't think it will happen soon]

Alternatively: if you need this on an urgent basis, you can build the sdk on your own from their react native code and integrate it in flutter while still using our framework over it.. you would need to change one entry each in our framework's gradle and pod file.
