### ISSUE TITLE
User Limit

### ISSUE THREAD

**Issue by kry0sc0pic** [gunschu/jitsi_meet#89]
Is there anyway to limit the number of users that can join the meeting?

**Comment by jimmyjose-dev** [comment]
Short answer: The current mobile framework does not posses that capability

Long answer: You can approach this two ways...

1) If you have self hosted Jitsi
You can enable the prosody module 
in /etc/prosody/conf.d/yourjitsihostingdomain.cfg.lua
**count should always be +1**, so if you want to have 20 users.. you have to enter 21
```
muc_max_occupants = <whatever number you want> 
modules_enabled = {
#add this to the existing modules
"muc_max_occupants";
}

This will be fixed for all rooms
```

2) If you are using meet.jitsi or cant enable the prosody module
```
Have a remote db and rest api set up which does the following...
a) Before a user joins a room, app initiates a service which checks 
   db for current count of users in that room 
b) If that count is less than the threshold you mark the users entry in the table for that room
c) Let the user join the room

You would have to do error handling and deal with race conditions on your own.. 
but max user can differ for each room

```

**meet.jitsi i think has a hard limit of 75 users per room** you would have to check on their forum for current number if you plan to go beyond that.

**Comment by kry0sc0pic** [comment]
Thank You very much.
