### ISSUE TITLE
Translate and Build with Vietnamese language: not work.

### ISSUE THREAD

**Issue by congduy** [gunschu/jitsi_meet#9]
I have tried with the Vietnamese language and translated it, however it does not work with translated content.
I translated this file:
... / ios / Pods / JitsiMeetSDK / Frameworks / JitsiMeet.framework / assets / lang / main-vi.json
Who has a best solution, please support me,
Thank you.

**Comment by congduy** [comment]
Hi anh @tuantvu,
Can you help me the method for translate this module.
Thanks anh,

**Comment by tuantvu** [comment]
I'm not an IOS expert sorry.

**Comment by tuantvu** [comment]
@congduy It looks like Vietnamese is supported by Jitsi SDK: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/i18n/BuiltinLanguages.native.js. I think you need to change the default language in your phone settings, then launch the app. Try with latest version of this plugin and let me know.
