### ISSUE TITLE
When can Chinese be supported

### ISSUE THREAD

**Issue by GeminiSGX** [gunschu/jitsi_meet#91]
I am using plugin jitsi_meet on flutter development, but it doesn't support Chinese and I want to make a question ,when can Chinese be supported?

**Comment by tuantvu** [comment]
We're using Jitsi meet's mobile sdk, so support whatever jitsi does. Looking at their language support json, I see Chinese has been supported since 2017. I think you need to set the local settings on your phone to be in Chinese/Mandarin, then hopefully Jitsi Meet will automatically detect that?

**Comment by GeminiSGX** [comment]
> We're using Jitsi meet's mobile sdk, so support whatever jitsi does. Looking at their language support json, I see Chinese has been supported since 2017. I think you need to set the local settings on your phone to be in Chinese/Mandarin, then hopefully Jitsi Meet will automatically detect that?

Yes,it dose. But it seems distinguish operating system. When I use App on Android 10 system, it display in Chiness, but English on Android 6. And the option 'Enable low bandwidth mode', 'Help' is still be displayed in English.

**Comment by tuantvu** [comment]
This would then fall out of the assistance we're able to give since it sounds like an issue with JitsiMeet itself or older Android versions. May need to file a but with JitsiMeet repository. https://github.com/jitsi/jitsi-meet
