### ISSUE TITLE
Change lang to EN, it displays all in ES

### ISSUE THREAD

**Issue by IswCesar** [gunschu/jitsi_meet#93]
My jitsi backend is in EN , but the mobile app displays all in ES, can you help me?, Where I have to configure the lang to EN and not ES???

Thanks a lot!!!

**Comment by TBG-FR** [comment]
The Jitsi Meet SDK should detect your phone language and display values according to it

Is your phone configured in spanish ? or maybe they broke the language detection once again...

**Comment by tuantvu** [comment]
@IswCesar Did you see above question? Is this still an issue?

**Comment by pishguy** [comment]
we have the same issue, my phone language is English and i don't want to change phone locale to get my native language inside application, how can i change language and locale instead

**Comment by tuantvu** [comment]
@MahdiPishguy Please search or ask on https://community.jitsi.org/. If you find an answer, open a new feature request and we'll look at it. Thanks.
