### ISSUE TITLE
Xcode 11.2.1 build error 

### ISSUE THREAD

**Issue by mohamedali21** [gunschu/jitsi_meet#97]
Mac Os 10.15
I have these problems

```
Failed to load module 'JitsiMeet' 
'AnimationCompletion' is not a member type of 'JitsiMeet' 
'PiPViewCoordinator' is not a member type of 'JitsiMeet'
```

with the jitsi_meet 0.3.0 package with IOS when I run the app on Xcode 11.2.1 and Swift version 5.2.2.

**Comment by IswCesar** [comment]
Hi !!! It's a error with MacOS and Xcode version, update to Catalina and Xcode then it will compile with no errors!!!
