### ISSUE TITLE
joinMeeting never resolves for iOS

### ISSUE THREAD

**Issue by kleeb** [gunschu/jitsi_meet#99]
JitsiMeet.joinMeeting returns Future<JitsiMeetingResponse>.
It resolves properly on Android, but hangs on iOS, even though conference works like expected.

**Comment by jimmyjose-dev** [comment]
In current iOS implementation, it returns Future only if it encounters an error.. I will try to add the missing piece soon.

**Comment by jimmyjose-dev** [comment]
@kleeb Pushed a PR that will resolve this, waiting for @tuantvu's blessings :)
